# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  #The Stripe REST API. Please see https://stripe.com/docs/api for more details.
  Stripe (Stripe API):
    UUID: 68e1dc69-634d-4b91-8249-f94c9ccdd7c7
    Url: https://api.stripe.com/
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: file:///C:/Users/tvtphuc/Downloads/openapi.json
      Namespace: com.stripe.api.client
