# yaml-language-server: $schema=https://json-schema.axonivy.com/app/13.1.0/rest-clients.json
RestClients:
  #The Stripe REST API. Please see https://stripe.com/docs/api for more details.
  Stripe (Stripe API):
    UUID: ef99b422-1c59-4c30-8e9c-4f528cb1e117
    Url: https://api.stripe.com/
    Features:
    - com.axonivy.connector.stripe.deserializers.StripeDataJsonFeature
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: file:///D:/work/Project/MARKET/stripe-connector/stripe-connector-product/openapi.json
      Namespace: com.stripe.api.client
