# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/rest-clients.json
RestClients:
  #The Stripe REST API. Please see https://stripe.com/docs/api for more details.
  Stripe (Stripe API):
    UUID: 7e1307d8-25b4-49ea-b638-e437f822cbdd
    Url: https://api.stripe.com/
    Features:
    - ch.ivyteam.ivy.rest.client.mapper.JsonFeature
    OpenAPI:
      SpecUrl: file:///C:/Users/tvtphuc/Downloads/spec3.json
      Namespace: com.stripe.api.client
