# yaml-language-server: $schema=https://json-schema.axonivy.com/app/12.0.0/variables.json
Variables:
  stripe-connector:
    auth:
      #[password]
      secretKey: ${decrypt:}
      #[password]
      publishableKey: ${decrypt:}
