# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  stripe:
    auth:
      # Secret key in Stripe account
      #[password]
      secretKey: ${decrypt:}
      # Publishable key in Stripe account
      #[password]
      publishableKey: ${decrypt:}
