/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.AccountMonthlyEstimatedRevenue;

/**
 * AccountBusinessProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class AccountBusinessProfile implements AnyOfaccountBusinessProfile {
  @JsonProperty("annual_revenue")
  private AnyOfaccountBusinessProfileAnnualRevenue annualRevenue = null;

  @JsonProperty("estimated_worker_count")
  private Integer estimatedWorkerCount = null;

  @JsonProperty("mcc")
  private String mcc = null;

  @JsonProperty("monthly_estimated_revenue")
  private AccountMonthlyEstimatedRevenue monthlyEstimatedRevenue = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("product_description")
  private String productDescription = null;

  @JsonProperty("support_address")
  private AnyOfaccountBusinessProfileSupportAddress supportAddress = null;

  @JsonProperty("support_email")
  private String supportEmail = null;

  @JsonProperty("support_phone")
  private String supportPhone = null;

  @JsonProperty("support_url")
  private String supportUrl = null;

  @JsonProperty("url")
  private String url = null;

  public AccountBusinessProfile annualRevenue(AnyOfaccountBusinessProfileAnnualRevenue annualRevenue) {
    this.annualRevenue = annualRevenue;
    return this;
  }

   /**
   * The applicant&#x27;s gross annual revenue for its preceding fiscal year.
   * @return annualRevenue
  **/
  public AnyOfaccountBusinessProfileAnnualRevenue getAnnualRevenue() {
    return annualRevenue;
  }

  public void setAnnualRevenue(AnyOfaccountBusinessProfileAnnualRevenue annualRevenue) {
    this.annualRevenue = annualRevenue;
  }

  public AccountBusinessProfile estimatedWorkerCount(Integer estimatedWorkerCount) {
    this.estimatedWorkerCount = estimatedWorkerCount;
    return this;
  }

   /**
   * An estimated upper bound of employees, contractors, vendors, etc. currently working for the business.
   * @return estimatedWorkerCount
  **/
  public Integer getEstimatedWorkerCount() {
    return estimatedWorkerCount;
  }

  public void setEstimatedWorkerCount(Integer estimatedWorkerCount) {
    this.estimatedWorkerCount = estimatedWorkerCount;
  }

  public AccountBusinessProfile mcc(String mcc) {
    this.mcc = mcc;
    return this;
  }

   /**
   * [The merchant category code for the account](/connect/setting-mcc). MCCs are used to classify businesses based on the goods or services they provide.
   * @return mcc
  **/
  public String getMcc() {
    return mcc;
  }

  public void setMcc(String mcc) {
    this.mcc = mcc;
  }

  public AccountBusinessProfile monthlyEstimatedRevenue(AccountMonthlyEstimatedRevenue monthlyEstimatedRevenue) {
    this.monthlyEstimatedRevenue = monthlyEstimatedRevenue;
    return this;
  }

   /**
   * Get monthlyEstimatedRevenue
   * @return monthlyEstimatedRevenue
  **/
  public AccountMonthlyEstimatedRevenue getMonthlyEstimatedRevenue() {
    return monthlyEstimatedRevenue;
  }

  public void setMonthlyEstimatedRevenue(AccountMonthlyEstimatedRevenue monthlyEstimatedRevenue) {
    this.monthlyEstimatedRevenue = monthlyEstimatedRevenue;
  }

  public AccountBusinessProfile name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The customer-facing business name.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AccountBusinessProfile productDescription(String productDescription) {
    this.productDescription = productDescription;
    return this;
  }

   /**
   * Internal-only description of the product sold or service provided by the business. It&#x27;s used by Stripe for risk and underwriting purposes.
   * @return productDescription
  **/
  public String getProductDescription() {
    return productDescription;
  }

  public void setProductDescription(String productDescription) {
    this.productDescription = productDescription;
  }

  public AccountBusinessProfile supportAddress(AnyOfaccountBusinessProfileSupportAddress supportAddress) {
    this.supportAddress = supportAddress;
    return this;
  }

   /**
   * A publicly available mailing address for sending support issues to.
   * @return supportAddress
  **/
  public AnyOfaccountBusinessProfileSupportAddress getSupportAddress() {
    return supportAddress;
  }

  public void setSupportAddress(AnyOfaccountBusinessProfileSupportAddress supportAddress) {
    this.supportAddress = supportAddress;
  }

  public AccountBusinessProfile supportEmail(String supportEmail) {
    this.supportEmail = supportEmail;
    return this;
  }

   /**
   * A publicly available email address for sending support issues to.
   * @return supportEmail
  **/
  public String getSupportEmail() {
    return supportEmail;
  }

  public void setSupportEmail(String supportEmail) {
    this.supportEmail = supportEmail;
  }

  public AccountBusinessProfile supportPhone(String supportPhone) {
    this.supportPhone = supportPhone;
    return this;
  }

   /**
   * A publicly available phone number to call with support issues.
   * @return supportPhone
  **/
  public String getSupportPhone() {
    return supportPhone;
  }

  public void setSupportPhone(String supportPhone) {
    this.supportPhone = supportPhone;
  }

  public AccountBusinessProfile supportUrl(String supportUrl) {
    this.supportUrl = supportUrl;
    return this;
  }

   /**
   * A publicly available website for handling support issues.
   * @return supportUrl
  **/
  public String getSupportUrl() {
    return supportUrl;
  }

  public void setSupportUrl(String supportUrl) {
    this.supportUrl = supportUrl;
  }

  public AccountBusinessProfile url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The business&#x27;s publicly available website.
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountBusinessProfile accountBusinessProfile = (AccountBusinessProfile) o;
    return Objects.equals(this.annualRevenue, accountBusinessProfile.annualRevenue) &&
        Objects.equals(this.estimatedWorkerCount, accountBusinessProfile.estimatedWorkerCount) &&
        Objects.equals(this.mcc, accountBusinessProfile.mcc) &&
        Objects.equals(this.monthlyEstimatedRevenue, accountBusinessProfile.monthlyEstimatedRevenue) &&
        Objects.equals(this.name, accountBusinessProfile.name) &&
        Objects.equals(this.productDescription, accountBusinessProfile.productDescription) &&
        Objects.equals(this.supportAddress, accountBusinessProfile.supportAddress) &&
        Objects.equals(this.supportEmail, accountBusinessProfile.supportEmail) &&
        Objects.equals(this.supportPhone, accountBusinessProfile.supportPhone) &&
        Objects.equals(this.supportUrl, accountBusinessProfile.supportUrl) &&
        Objects.equals(this.url, accountBusinessProfile.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(annualRevenue, estimatedWorkerCount, mcc, monthlyEstimatedRevenue, name, productDescription, supportAddress, supportEmail, supportPhone, supportUrl, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountBusinessProfile {\n");
    
    sb.append("    annualRevenue: ").append(toIndentedString(annualRevenue)).append("\n");
    sb.append("    estimatedWorkerCount: ").append(toIndentedString(estimatedWorkerCount)).append("\n");
    sb.append("    mcc: ").append(toIndentedString(mcc)).append("\n");
    sb.append("    monthlyEstimatedRevenue: ").append(toIndentedString(monthlyEstimatedRevenue)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    productDescription: ").append(toIndentedString(productDescription)).append("\n");
    sb.append("    supportAddress: ").append(toIndentedString(supportAddress)).append("\n");
    sb.append("    supportEmail: ").append(toIndentedString(supportEmail)).append("\n");
    sb.append("    supportPhone: ").append(toIndentedString(supportPhone)).append("\n");
    sb.append("    supportUrl: ").append(toIndentedString(supportUrl)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
