/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.FleetSpecs1;
import com.stripe.api.client.FuelSpecs;

import java.util.ArrayList;
import java.util.List;
/**
 * AuthorizationFinalizeAmountBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class AuthorizationFinalizeAmountBody {
  @JsonProperty("expand")
  private List<String> expand = null;

  @JsonProperty("final_amount")
  private Integer finalAmount = null;

  @JsonProperty("fleet")
  private FleetSpecs1 fleet = null;

  @JsonProperty("fuel")
  private FuelSpecs fuel = null;

  public AuthorizationFinalizeAmountBody expand(List<String> expand) {
    this.expand = expand;
    return this;
  }

  public AuthorizationFinalizeAmountBody addExpandItem(String expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

   /**
   * Specifies which fields in the response should be expanded.
   * @return expand
  **/
  public List<String> getExpand() {
    return expand;
  }

  public void setExpand(List<String> expand) {
    this.expand = expand;
  }

  public AuthorizationFinalizeAmountBody finalAmount(Integer finalAmount) {
    this.finalAmount = finalAmount;
    return this;
  }

   /**
   * The final authorization amount that will be captured by the merchant. This amount is in the authorization currency and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal).
   * @return finalAmount
  **/
  public Integer getFinalAmount() {
    return finalAmount;
  }

  public void setFinalAmount(Integer finalAmount) {
    this.finalAmount = finalAmount;
  }

  public AuthorizationFinalizeAmountBody fleet(FleetSpecs1 fleet) {
    this.fleet = fleet;
    return this;
  }

   /**
   * Get fleet
   * @return fleet
  **/
  public FleetSpecs1 getFleet() {
    return fleet;
  }

  public void setFleet(FleetSpecs1 fleet) {
    this.fleet = fleet;
  }

  public AuthorizationFinalizeAmountBody fuel(FuelSpecs fuel) {
    this.fuel = fuel;
    return this;
  }

   /**
   * Get fuel
   * @return fuel
  **/
  public FuelSpecs getFuel() {
    return fuel;
  }

  public void setFuel(FuelSpecs fuel) {
    this.fuel = fuel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthorizationFinalizeAmountBody authorizationFinalizeAmountBody = (AuthorizationFinalizeAmountBody) o;
    return Objects.equals(this.expand, authorizationFinalizeAmountBody.expand) &&
        Objects.equals(this.finalAmount, authorizationFinalizeAmountBody.finalAmount) &&
        Objects.equals(this.fleet, authorizationFinalizeAmountBody.fleet) &&
        Objects.equals(this.fuel, authorizationFinalizeAmountBody.fuel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expand, finalAmount, fleet, fuel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthorizationFinalizeAmountBody {\n");
    
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    finalAmount: ").append(toIndentedString(finalAmount)).append("\n");
    sb.append("    fleet: ").append(toIndentedString(fleet)).append("\n");
    sb.append("    fuel: ").append(toIndentedString(fuel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
