/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.EuBankTransferParams;

import java.util.ArrayList;
import java.util.List;
/**
 * BankTransferParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class BankTransferParam {
  @JsonProperty("eu_bank_transfer")
  private EuBankTransferParams euBankTransfer = null;

  /**
   * Gets or Sets requestedAddressTypes
   */
  public enum RequestedAddressTypesEnum {
    ABA("aba"),
    IBAN("iban"),
    SEPA("sepa"),
    SORT_CODE("sort_code"),
    SPEI("spei"),
    SWIFT("swift"),
    ZENGIN("zengin");

    private String value;

    RequestedAddressTypesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RequestedAddressTypesEnum fromValue(String input) {
      for (RequestedAddressTypesEnum b : RequestedAddressTypesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("requested_address_types")
  private List<RequestedAddressTypesEnum> requestedAddressTypes = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    EU_BANK_TRANSFER("eu_bank_transfer"),
    GB_BANK_TRANSFER("gb_bank_transfer"),
    JP_BANK_TRANSFER("jp_bank_transfer"),
    MX_BANK_TRANSFER("mx_bank_transfer"),
    US_BANK_TRANSFER("us_bank_transfer");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public BankTransferParam euBankTransfer(EuBankTransferParams euBankTransfer) {
    this.euBankTransfer = euBankTransfer;
    return this;
  }

   /**
   * Get euBankTransfer
   * @return euBankTransfer
  **/
  public EuBankTransferParams getEuBankTransfer() {
    return euBankTransfer;
  }

  public void setEuBankTransfer(EuBankTransferParams euBankTransfer) {
    this.euBankTransfer = euBankTransfer;
  }

  public BankTransferParam requestedAddressTypes(List<RequestedAddressTypesEnum> requestedAddressTypes) {
    this.requestedAddressTypes = requestedAddressTypes;
    return this;
  }

  public BankTransferParam addRequestedAddressTypesItem(RequestedAddressTypesEnum requestedAddressTypesItem) {
    if (this.requestedAddressTypes == null) {
      this.requestedAddressTypes = new ArrayList<>();
    }
    this.requestedAddressTypes.add(requestedAddressTypesItem);
    return this;
  }

   /**
   * Get requestedAddressTypes
   * @return requestedAddressTypes
  **/
  public List<RequestedAddressTypesEnum> getRequestedAddressTypes() {
    return requestedAddressTypes;
  }

  public void setRequestedAddressTypes(List<RequestedAddressTypesEnum> requestedAddressTypes) {
    this.requestedAddressTypes = requestedAddressTypes;
  }

  public BankTransferParam type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankTransferParam bankTransferParam = (BankTransferParam) o;
    return Objects.equals(this.euBankTransfer, bankTransferParam.euBankTransfer) &&
        Objects.equals(this.requestedAddressTypes, bankTransferParam.requestedAddressTypes) &&
        Objects.equals(this.type, bankTransferParam.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(euBankTransfer, requestedAddressTypes, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankTransferParam {\n");
    
    sb.append("    euBankTransfer: ").append(toIndentedString(euBankTransfer)).append("\n");
    sb.append("    requestedAddressTypes: ").append(toIndentedString(requestedAddressTypes)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
