/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided implements AnyOfbillingCreditGrantsResourceBalanceCreditCreditsApplicationInvoiceVoided {
  @JsonProperty("invoice")
  private AnyOfbillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice invoice = null;

  @JsonProperty("invoice_line_item")
  private String invoiceLineItem = null;

  public BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided invoice(AnyOfbillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice invoice) {
    this.invoice = invoice;
    return this;
  }

   /**
   * The invoice to which the reinstated billing credits were originally applied.
   * @return invoice
  **/
  public AnyOfbillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice getInvoice() {
    return invoice;
  }

  public void setInvoice(AnyOfbillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoidedInvoice invoice) {
    this.invoice = invoice;
  }

  public BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided invoiceLineItem(String invoiceLineItem) {
    this.invoiceLineItem = invoiceLineItem;
    return this;
  }

   /**
   * The invoice line item to which the reinstated billing credits were originally applied.
   * @return invoiceLineItem
  **/
  public String getInvoiceLineItem() {
    return invoiceLineItem;
  }

  public void setInvoiceLineItem(String invoiceLineItem) {
    this.invoiceLineItem = invoiceLineItem;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided billingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided = (BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided) o;
    return Objects.equals(this.invoice, billingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided.invoice) &&
        Objects.equals(this.invoiceLineItem, billingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided.invoiceLineItem);
  }

  @Override
  public int hashCode() {
    return Objects.hash(invoice, invoiceLineItem);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillingCreditGrantsResourceBalanceCreditsApplicationInvoiceVoided {\n");
    
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    invoiceLineItem: ").append(toIndentedString(invoiceLineItem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
