/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.AuthorizationControlsParamV2;
import com.stripe.api.client.BillingSpecs;
import com.stripe.api.client.CompanyParam;
import com.stripe.api.client.IndividualParam;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * CardholdersCardholderBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class CardholdersCardholderBody {
  @JsonProperty("billing")
  private BillingSpecs billing = null;

  @JsonProperty("company")
  private CompanyParam company = null;

  @JsonProperty("email")
  private String email = null;

  @JsonProperty("expand")
  private List<String> expand = null;

  @JsonProperty("individual")
  private IndividualParam individual = null;

  @JsonProperty("metadata")
  private Map<String, String> metadata = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  /**
   * Gets or Sets preferredLocales
   */
  public enum PreferredLocalesEnum {
    DE("de"),
    EN("en"),
    ES("es"),
    FR("fr"),
    IT("it");

    private String value;

    PreferredLocalesEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PreferredLocalesEnum fromValue(String input) {
      for (PreferredLocalesEnum b : PreferredLocalesEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("preferred_locales")
  private List<PreferredLocalesEnum> preferredLocales = null;

  @JsonProperty("spending_controls")
  private AuthorizationControlsParamV2 spendingControls = null;

  /**
   * Specifies whether to permit authorizations on this cardholder&#x27;s cards.
   */
  public enum StatusEnum {
    ACTIVE("active"),
    INACTIVE("inactive");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  public CardholdersCardholderBody billing(BillingSpecs billing) {
    this.billing = billing;
    return this;
  }

   /**
   * Get billing
   * @return billing
  **/
  public BillingSpecs getBilling() {
    return billing;
  }

  public void setBilling(BillingSpecs billing) {
    this.billing = billing;
  }

  public CardholdersCardholderBody company(CompanyParam company) {
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  public CompanyParam getCompany() {
    return company;
  }

  public void setCompany(CompanyParam company) {
    this.company = company;
  }

  public CardholdersCardholderBody email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The cardholder&#x27;s email address.
   * @return email
  **/
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public CardholdersCardholderBody expand(List<String> expand) {
    this.expand = expand;
    return this;
  }

  public CardholdersCardholderBody addExpandItem(String expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

   /**
   * Specifies which fields in the response should be expanded.
   * @return expand
  **/
  public List<String> getExpand() {
    return expand;
  }

  public void setExpand(List<String> expand) {
    this.expand = expand;
  }

  public CardholdersCardholderBody individual(IndividualParam individual) {
    this.individual = individual;
    return this;
  }

   /**
   * Get individual
   * @return individual
  **/
  public IndividualParam getIndividual() {
    return individual;
  }

  public void setIndividual(IndividualParam individual) {
    this.individual = individual;
  }

  public CardholdersCardholderBody metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CardholdersCardholderBody putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &#x60;metadata&#x60;.
   * @return metadata
  **/
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public CardholdersCardholderBody phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * The cardholder&#x27;s phone number. This is required for all cardholders who will be creating EU cards. See the [3D Secure documentation](https://stripe.com/docs/issuing/3d-secure) for more details.
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public CardholdersCardholderBody preferredLocales(List<PreferredLocalesEnum> preferredLocales) {
    this.preferredLocales = preferredLocales;
    return this;
  }

  public CardholdersCardholderBody addPreferredLocalesItem(PreferredLocalesEnum preferredLocalesItem) {
    if (this.preferredLocales == null) {
      this.preferredLocales = new ArrayList<>();
    }
    this.preferredLocales.add(preferredLocalesItem);
    return this;
  }

   /**
   * The cardholder’s preferred locales (languages), ordered by preference. Locales can be &#x60;de&#x60;, &#x60;en&#x60;, &#x60;es&#x60;, &#x60;fr&#x60;, or &#x60;it&#x60;.  This changes the language of the [3D Secure flow](https://stripe.com/docs/issuing/3d-secure) and one-time password messages sent to the cardholder.
   * @return preferredLocales
  **/
  public List<PreferredLocalesEnum> getPreferredLocales() {
    return preferredLocales;
  }

  public void setPreferredLocales(List<PreferredLocalesEnum> preferredLocales) {
    this.preferredLocales = preferredLocales;
  }

  public CardholdersCardholderBody spendingControls(AuthorizationControlsParamV2 spendingControls) {
    this.spendingControls = spendingControls;
    return this;
  }

   /**
   * Get spendingControls
   * @return spendingControls
  **/
  public AuthorizationControlsParamV2 getSpendingControls() {
    return spendingControls;
  }

  public void setSpendingControls(AuthorizationControlsParamV2 spendingControls) {
    this.spendingControls = spendingControls;
  }

  public CardholdersCardholderBody status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Specifies whether to permit authorizations on this cardholder&#x27;s cards.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CardholdersCardholderBody cardholdersCardholderBody = (CardholdersCardholderBody) o;
    return Objects.equals(this.billing, cardholdersCardholderBody.billing) &&
        Objects.equals(this.company, cardholdersCardholderBody.company) &&
        Objects.equals(this.email, cardholdersCardholderBody.email) &&
        Objects.equals(this.expand, cardholdersCardholderBody.expand) &&
        Objects.equals(this.individual, cardholdersCardholderBody.individual) &&
        Objects.equals(this.metadata, cardholdersCardholderBody.metadata) &&
        Objects.equals(this.phoneNumber, cardholdersCardholderBody.phoneNumber) &&
        Objects.equals(this.preferredLocales, cardholdersCardholderBody.preferredLocales) &&
        Objects.equals(this.spendingControls, cardholdersCardholderBody.spendingControls) &&
        Objects.equals(this.status, cardholdersCardholderBody.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(billing, company, email, expand, individual, metadata, phoneNumber, preferredLocales, spendingControls, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CardholdersCardholderBody {\n");
    
    sb.append("    billing: ").append(toIndentedString(billing)).append("\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    individual: ").append(toIndentedString(individual)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    preferredLocales: ").append(toIndentedString(preferredLocales)).append("\n");
    sb.append("    spendingControls: ").append(toIndentedString(spendingControls)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
