/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ConnectEmbeddedIssuingCardFeatures
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class ConnectEmbeddedIssuingCardFeatures {
  @JsonProperty("card_management")
  private Boolean cardManagement = null;

  @JsonProperty("card_spend_dispute_management")
  private Boolean cardSpendDisputeManagement = null;

  @JsonProperty("cardholder_management")
  private Boolean cardholderManagement = null;

  @JsonProperty("spend_control_management")
  private Boolean spendControlManagement = null;

  public ConnectEmbeddedIssuingCardFeatures cardManagement(Boolean cardManagement) {
    this.cardManagement = cardManagement;
    return this;
  }

   /**
   * Whether to allow card management features.
   * @return cardManagement
  **/
  public Boolean isCardManagement() {
    return cardManagement;
  }

  public void setCardManagement(Boolean cardManagement) {
    this.cardManagement = cardManagement;
  }

  public ConnectEmbeddedIssuingCardFeatures cardSpendDisputeManagement(Boolean cardSpendDisputeManagement) {
    this.cardSpendDisputeManagement = cardSpendDisputeManagement;
    return this;
  }

   /**
   * Whether to allow card spend dispute management features.
   * @return cardSpendDisputeManagement
  **/
  public Boolean isCardSpendDisputeManagement() {
    return cardSpendDisputeManagement;
  }

  public void setCardSpendDisputeManagement(Boolean cardSpendDisputeManagement) {
    this.cardSpendDisputeManagement = cardSpendDisputeManagement;
  }

  public ConnectEmbeddedIssuingCardFeatures cardholderManagement(Boolean cardholderManagement) {
    this.cardholderManagement = cardholderManagement;
    return this;
  }

   /**
   * Whether to allow cardholder management features.
   * @return cardholderManagement
  **/
  public Boolean isCardholderManagement() {
    return cardholderManagement;
  }

  public void setCardholderManagement(Boolean cardholderManagement) {
    this.cardholderManagement = cardholderManagement;
  }

  public ConnectEmbeddedIssuingCardFeatures spendControlManagement(Boolean spendControlManagement) {
    this.spendControlManagement = spendControlManagement;
    return this;
  }

   /**
   * Whether to allow spend control management features.
   * @return spendControlManagement
  **/
  public Boolean isSpendControlManagement() {
    return spendControlManagement;
  }

  public void setSpendControlManagement(Boolean spendControlManagement) {
    this.spendControlManagement = spendControlManagement;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectEmbeddedIssuingCardFeatures connectEmbeddedIssuingCardFeatures = (ConnectEmbeddedIssuingCardFeatures) o;
    return Objects.equals(this.cardManagement, connectEmbeddedIssuingCardFeatures.cardManagement) &&
        Objects.equals(this.cardSpendDisputeManagement, connectEmbeddedIssuingCardFeatures.cardSpendDisputeManagement) &&
        Objects.equals(this.cardholderManagement, connectEmbeddedIssuingCardFeatures.cardholderManagement) &&
        Objects.equals(this.spendControlManagement, connectEmbeddedIssuingCardFeatures.spendControlManagement);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardManagement, cardSpendDisputeManagement, cardholderManagement, spendControlManagement);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectEmbeddedIssuingCardFeatures {\n");
    
    sb.append("    cardManagement: ").append(toIndentedString(cardManagement)).append("\n");
    sb.append("    cardSpendDisputeManagement: ").append(toIndentedString(cardSpendDisputeManagement)).append("\n");
    sb.append("    cardholderManagement: ").append(toIndentedString(cardholderManagement)).append("\n");
    sb.append("    spendControlManagement: ").append(toIndentedString(spendControlManagement)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
