/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.ControllerDashboardSpecs;
import com.stripe.api.client.ControllerFeesSpecs;
import com.stripe.api.client.ControllerLossesSpecs;

/**
 * A hash of configuration describing the account controller&#x27;s attributes.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class ControllerSpecs {
  @JsonProperty("fees")
  private ControllerFeesSpecs fees = null;

  @JsonProperty("losses")
  private ControllerLossesSpecs losses = null;

  /**
   * Gets or Sets requirementCollection
   */
  public enum RequirementCollectionEnum {
    APPLICATION("application"),
    STRIPE("stripe");

    private String value;

    RequirementCollectionEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static RequirementCollectionEnum fromValue(String input) {
      for (RequirementCollectionEnum b : RequirementCollectionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("requirement_collection")
  private RequirementCollectionEnum requirementCollection = null;

  @JsonProperty("stripe_dashboard")
  private ControllerDashboardSpecs stripeDashboard = null;

  public ControllerSpecs fees(ControllerFeesSpecs fees) {
    this.fees = fees;
    return this;
  }

   /**
   * Get fees
   * @return fees
  **/
  public ControllerFeesSpecs getFees() {
    return fees;
  }

  public void setFees(ControllerFeesSpecs fees) {
    this.fees = fees;
  }

  public ControllerSpecs losses(ControllerLossesSpecs losses) {
    this.losses = losses;
    return this;
  }

   /**
   * Get losses
   * @return losses
  **/
  public ControllerLossesSpecs getLosses() {
    return losses;
  }

  public void setLosses(ControllerLossesSpecs losses) {
    this.losses = losses;
  }

  public ControllerSpecs requirementCollection(RequirementCollectionEnum requirementCollection) {
    this.requirementCollection = requirementCollection;
    return this;
  }

   /**
   * Get requirementCollection
   * @return requirementCollection
  **/
  public RequirementCollectionEnum getRequirementCollection() {
    return requirementCollection;
  }

  public void setRequirementCollection(RequirementCollectionEnum requirementCollection) {
    this.requirementCollection = requirementCollection;
  }

  public ControllerSpecs stripeDashboard(ControllerDashboardSpecs stripeDashboard) {
    this.stripeDashboard = stripeDashboard;
    return this;
  }

   /**
   * Get stripeDashboard
   * @return stripeDashboard
  **/
  public ControllerDashboardSpecs getStripeDashboard() {
    return stripeDashboard;
  }

  public void setStripeDashboard(ControllerDashboardSpecs stripeDashboard) {
    this.stripeDashboard = stripeDashboard;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ControllerSpecs controllerSpecs = (ControllerSpecs) o;
    return Objects.equals(this.fees, controllerSpecs.fees) &&
        Objects.equals(this.losses, controllerSpecs.losses) &&
        Objects.equals(this.requirementCollection, controllerSpecs.requirementCollection) &&
        Objects.equals(this.stripeDashboard, controllerSpecs.stripeDashboard);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fees, losses, requirementCollection, stripeDashboard);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ControllerSpecs {\n");
    
    sb.append("    fees: ").append(toIndentedString(fees)).append("\n");
    sb.append("    losses: ").append(toIndentedString(losses)).append("\n");
    sb.append("    requirementCollection: ").append(toIndentedString(requirementCollection)).append("\n");
    sb.append("    stripeDashboard: ").append(toIndentedString(stripeDashboard)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
