/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.CreditNoteTaxAmount;
import com.stripe.api.client.CreditNotesPretaxCreditAmount;
import com.stripe.api.client.DiscountsResourceDiscountAmount;
import com.stripe.api.client.TaxRate;

import java.util.ArrayList;
import java.util.List;
/**
 * The credit note line item object
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class CreditNoteLineItem {
  @JsonProperty("amount")
  private Integer amount = null;

  @JsonProperty("amount_excluding_tax")
  private Integer amountExcludingTax = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("discount_amount")
  private Integer discountAmount = null;

  @JsonProperty("discount_amounts")
  private List<DiscountsResourceDiscountAmount> discountAmounts = new ArrayList<>();

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("invoice_line_item")
  private String invoiceLineItem = null;

  @JsonProperty("livemode")
  private Boolean livemode = null;

  /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   */
  public enum ObjectEnum {
    CREDIT_NOTE_LINE_ITEM("credit_note_line_item");

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ObjectEnum fromValue(String input) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("object")
  private ObjectEnum object = null;

  @JsonProperty("pretax_credit_amounts")
  private List<CreditNotesPretaxCreditAmount> pretaxCreditAmounts = new ArrayList<>();

  @JsonProperty("quantity")
  private Integer quantity = null;

  @JsonProperty("tax_amounts")
  private List<CreditNoteTaxAmount> taxAmounts = new ArrayList<>();

  @JsonProperty("tax_rates")
  private List<TaxRate> taxRates = new ArrayList<>();

  /**
   * The type of the credit note line item, one of &#x60;invoice_line_item&#x60; or &#x60;custom_line_item&#x60;. When the type is &#x60;invoice_line_item&#x60; there is an additional &#x60;invoice_line_item&#x60; property on the resource the value of which is the id of the credited line item on the invoice.
   */
  public enum TypeEnum {
    CUSTOM_LINE_ITEM("custom_line_item"),
    INVOICE_LINE_ITEM("invoice_line_item");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  @JsonProperty("unit_amount")
  private Integer unitAmount = null;

  @JsonProperty("unit_amount_decimal")
  private String unitAmountDecimal = null;

  @JsonProperty("unit_amount_excluding_tax")
  private String unitAmountExcludingTax = null;

  public CreditNoteLineItem amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The integer amount in cents (or local equivalent) representing the gross amount being credited for this line item, excluding (exclusive) tax and discounts.
   * @return amount
  **/
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public CreditNoteLineItem amountExcludingTax(Integer amountExcludingTax) {
    this.amountExcludingTax = amountExcludingTax;
    return this;
  }

   /**
   * The integer amount in cents (or local equivalent) representing the amount being credited for this line item, excluding all tax and discounts.
   * @return amountExcludingTax
  **/
  public Integer getAmountExcludingTax() {
    return amountExcludingTax;
  }

  public void setAmountExcludingTax(Integer amountExcludingTax) {
    this.amountExcludingTax = amountExcludingTax;
  }

  public CreditNoteLineItem description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Description of the item being credited.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CreditNoteLineItem discountAmount(Integer discountAmount) {
    this.discountAmount = discountAmount;
    return this;
  }

   /**
   * The integer amount in cents (or local equivalent) representing the discount being credited for this line item.
   * @return discountAmount
  **/
  public Integer getDiscountAmount() {
    return discountAmount;
  }

  public void setDiscountAmount(Integer discountAmount) {
    this.discountAmount = discountAmount;
  }

  public CreditNoteLineItem discountAmounts(List<DiscountsResourceDiscountAmount> discountAmounts) {
    this.discountAmounts = discountAmounts;
    return this;
  }

  public CreditNoteLineItem addDiscountAmountsItem(DiscountsResourceDiscountAmount discountAmountsItem) {
    this.discountAmounts.add(discountAmountsItem);
    return this;
  }

   /**
   * The amount of discount calculated per discount for this line item
   * @return discountAmounts
  **/
  public List<DiscountsResourceDiscountAmount> getDiscountAmounts() {
    return discountAmounts;
  }

  public void setDiscountAmounts(List<DiscountsResourceDiscountAmount> discountAmounts) {
    this.discountAmounts = discountAmounts;
  }

  public CreditNoteLineItem id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the object.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CreditNoteLineItem invoiceLineItem(String invoiceLineItem) {
    this.invoiceLineItem = invoiceLineItem;
    return this;
  }

   /**
   * ID of the invoice line item being credited
   * @return invoiceLineItem
  **/
  public String getInvoiceLineItem() {
    return invoiceLineItem;
  }

  public void setInvoiceLineItem(String invoiceLineItem) {
    this.invoiceLineItem = invoiceLineItem;
  }

  public CreditNoteLineItem livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Has the value &#x60;true&#x60; if the object exists in live mode or the value &#x60;false&#x60; if the object exists in test mode.
   * @return livemode
  **/
  public Boolean isLivemode() {
    return livemode;
  }

  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }

  public CreditNoteLineItem object(ObjectEnum object) {
    this.object = object;
    return this;
  }

   /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   * @return object
  **/
  public ObjectEnum getObject() {
    return object;
  }

  public void setObject(ObjectEnum object) {
    this.object = object;
  }

  public CreditNoteLineItem pretaxCreditAmounts(List<CreditNotesPretaxCreditAmount> pretaxCreditAmounts) {
    this.pretaxCreditAmounts = pretaxCreditAmounts;
    return this;
  }

  public CreditNoteLineItem addPretaxCreditAmountsItem(CreditNotesPretaxCreditAmount pretaxCreditAmountsItem) {
    this.pretaxCreditAmounts.add(pretaxCreditAmountsItem);
    return this;
  }

   /**
   * The pretax credit amounts (ex: discount, credit grants, etc) for this line item.
   * @return pretaxCreditAmounts
  **/
  public List<CreditNotesPretaxCreditAmount> getPretaxCreditAmounts() {
    return pretaxCreditAmounts;
  }

  public void setPretaxCreditAmounts(List<CreditNotesPretaxCreditAmount> pretaxCreditAmounts) {
    this.pretaxCreditAmounts = pretaxCreditAmounts;
  }

  public CreditNoteLineItem quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * The number of units of product being credited.
   * @return quantity
  **/
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }

  public CreditNoteLineItem taxAmounts(List<CreditNoteTaxAmount> taxAmounts) {
    this.taxAmounts = taxAmounts;
    return this;
  }

  public CreditNoteLineItem addTaxAmountsItem(CreditNoteTaxAmount taxAmountsItem) {
    this.taxAmounts.add(taxAmountsItem);
    return this;
  }

   /**
   * The amount of tax calculated per tax rate for this line item
   * @return taxAmounts
  **/
  public List<CreditNoteTaxAmount> getTaxAmounts() {
    return taxAmounts;
  }

  public void setTaxAmounts(List<CreditNoteTaxAmount> taxAmounts) {
    this.taxAmounts = taxAmounts;
  }

  public CreditNoteLineItem taxRates(List<TaxRate> taxRates) {
    this.taxRates = taxRates;
    return this;
  }

  public CreditNoteLineItem addTaxRatesItem(TaxRate taxRatesItem) {
    this.taxRates.add(taxRatesItem);
    return this;
  }

   /**
   * The tax rates which apply to the line item.
   * @return taxRates
  **/
  public List<TaxRate> getTaxRates() {
    return taxRates;
  }

  public void setTaxRates(List<TaxRate> taxRates) {
    this.taxRates = taxRates;
  }

  public CreditNoteLineItem type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The type of the credit note line item, one of &#x60;invoice_line_item&#x60; or &#x60;custom_line_item&#x60;. When the type is &#x60;invoice_line_item&#x60; there is an additional &#x60;invoice_line_item&#x60; property on the resource the value of which is the id of the credited line item on the invoice.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public CreditNoteLineItem unitAmount(Integer unitAmount) {
    this.unitAmount = unitAmount;
    return this;
  }

   /**
   * The cost of each unit of product being credited.
   * @return unitAmount
  **/
  public Integer getUnitAmount() {
    return unitAmount;
  }

  public void setUnitAmount(Integer unitAmount) {
    this.unitAmount = unitAmount;
  }

  public CreditNoteLineItem unitAmountDecimal(String unitAmountDecimal) {
    this.unitAmountDecimal = unitAmountDecimal;
    return this;
  }

   /**
   * Same as &#x60;unit_amount&#x60;, but contains a decimal value with at most 12 decimal places.
   * @return unitAmountDecimal
  **/
  public String getUnitAmountDecimal() {
    return unitAmountDecimal;
  }

  public void setUnitAmountDecimal(String unitAmountDecimal) {
    this.unitAmountDecimal = unitAmountDecimal;
  }

  public CreditNoteLineItem unitAmountExcludingTax(String unitAmountExcludingTax) {
    this.unitAmountExcludingTax = unitAmountExcludingTax;
    return this;
  }

   /**
   * The amount in cents (or local equivalent) representing the unit amount being credited for this line item, excluding all tax and discounts.
   * @return unitAmountExcludingTax
  **/
  public String getUnitAmountExcludingTax() {
    return unitAmountExcludingTax;
  }

  public void setUnitAmountExcludingTax(String unitAmountExcludingTax) {
    this.unitAmountExcludingTax = unitAmountExcludingTax;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditNoteLineItem creditNoteLineItem = (CreditNoteLineItem) o;
    return Objects.equals(this.amount, creditNoteLineItem.amount) &&
        Objects.equals(this.amountExcludingTax, creditNoteLineItem.amountExcludingTax) &&
        Objects.equals(this.description, creditNoteLineItem.description) &&
        Objects.equals(this.discountAmount, creditNoteLineItem.discountAmount) &&
        Objects.equals(this.discountAmounts, creditNoteLineItem.discountAmounts) &&
        Objects.equals(this.id, creditNoteLineItem.id) &&
        Objects.equals(this.invoiceLineItem, creditNoteLineItem.invoiceLineItem) &&
        Objects.equals(this.livemode, creditNoteLineItem.livemode) &&
        Objects.equals(this.object, creditNoteLineItem.object) &&
        Objects.equals(this.pretaxCreditAmounts, creditNoteLineItem.pretaxCreditAmounts) &&
        Objects.equals(this.quantity, creditNoteLineItem.quantity) &&
        Objects.equals(this.taxAmounts, creditNoteLineItem.taxAmounts) &&
        Objects.equals(this.taxRates, creditNoteLineItem.taxRates) &&
        Objects.equals(this.type, creditNoteLineItem.type) &&
        Objects.equals(this.unitAmount, creditNoteLineItem.unitAmount) &&
        Objects.equals(this.unitAmountDecimal, creditNoteLineItem.unitAmountDecimal) &&
        Objects.equals(this.unitAmountExcludingTax, creditNoteLineItem.unitAmountExcludingTax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, amountExcludingTax, description, discountAmount, discountAmounts, id, invoiceLineItem, livemode, object, pretaxCreditAmounts, quantity, taxAmounts, taxRates, type, unitAmount, unitAmountDecimal, unitAmountExcludingTax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditNoteLineItem {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    amountExcludingTax: ").append(toIndentedString(amountExcludingTax)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    discountAmount: ").append(toIndentedString(discountAmount)).append("\n");
    sb.append("    discountAmounts: ").append(toIndentedString(discountAmounts)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoiceLineItem: ").append(toIndentedString(invoiceLineItem)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    pretaxCreditAmounts: ").append(toIndentedString(pretaxCreditAmounts)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    taxAmounts: ").append(toIndentedString(taxAmounts)).append("\n");
    sb.append("    taxRates: ").append(toIndentedString(taxRates)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    unitAmount: ").append(toIndentedString(unitAmount)).append("\n");
    sb.append("    unitAmountDecimal: ").append(toIndentedString(unitAmountDecimal)).append("\n");
    sb.append("    unitAmountExcludingTax: ").append(toIndentedString(unitAmountExcludingTax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
