/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CustomUnitAmount2
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class CustomUnitAmount2 {
  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("maximum")
  private Integer maximum = null;

  @JsonProperty("minimum")
  private Integer minimum = null;

  @JsonProperty("preset")
  private Integer preset = null;

  public CustomUnitAmount2 enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public CustomUnitAmount2 maximum(Integer maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * Get maximum
   * @return maximum
  **/
  public Integer getMaximum() {
    return maximum;
  }

  public void setMaximum(Integer maximum) {
    this.maximum = maximum;
  }

  public CustomUnitAmount2 minimum(Integer minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * Get minimum
   * @return minimum
  **/
  public Integer getMinimum() {
    return minimum;
  }

  public void setMinimum(Integer minimum) {
    this.minimum = minimum;
  }

  public CustomUnitAmount2 preset(Integer preset) {
    this.preset = preset;
    return this;
  }

   /**
   * Get preset
   * @return preset
  **/
  public Integer getPreset() {
    return preset;
  }

  public void setPreset(Integer preset) {
    this.preset = preset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomUnitAmount2 customUnitAmount2 = (CustomUnitAmount2) o;
    return Objects.equals(this.enabled, customUnitAmount2.enabled) &&
        Objects.equals(this.maximum, customUnitAmount2.maximum) &&
        Objects.equals(this.minimum, customUnitAmount2.minimum) &&
        Objects.equals(this.preset, customUnitAmount2.preset);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, maximum, minimum, preset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomUnitAmount2 {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("    preset: ").append(toIndentedString(preset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
