/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * Each customer has a [Balance](https://stripe.com/docs/api/customers/object#customer_object-balance) value, which denotes a debit or credit that&#x27;s automatically applied to their next invoice upon finalization. You may modify the value directly by using the [update customer API](https://stripe.com/docs/api/customers/update), or by creating a Customer Balance Transaction, which increments or decrements the customer&#x27;s &#x60;balance&#x60; by the specified &#x60;amount&#x60;.  Related guide: [Customer balance](https://stripe.com/docs/billing/customer/balance)
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class CustomerBalanceTransaction implements AnyOfcreditNoteCustomerBalanceTransaction {
  @JsonProperty("amount")
  private Integer amount = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("credit_note")
  private AnyOfcustomerBalanceTransactionCreditNote creditNote = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("customer")
  private AnyOfcustomerBalanceTransactionCustomer customer = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("ending_balance")
  private Integer endingBalance = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("invoice")
  private AnyOfcustomerBalanceTransactionInvoice invoice = null;

  @JsonProperty("livemode")
  private Boolean livemode = null;

  @JsonProperty("metadata")
  private Map<String, String> metadata = null;

  /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   */
  public enum ObjectEnum {
    CUSTOMER_BALANCE_TRANSACTION("customer_balance_transaction");

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ObjectEnum fromValue(String input) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("object")
  private ObjectEnum object = null;

  /**
   * Transaction type: &#x60;adjustment&#x60;, &#x60;applied_to_invoice&#x60;, &#x60;credit_note&#x60;, &#x60;initial&#x60;, &#x60;invoice_overpaid&#x60;, &#x60;invoice_too_large&#x60;, &#x60;invoice_too_small&#x60;, &#x60;unspent_receiver_credit&#x60;, or &#x60;unapplied_from_invoice&#x60;. See the [Customer Balance page](https://stripe.com/docs/billing/customer/balance#types) to learn more about transaction types.
   */
  public enum TypeEnum {
    ADJUSTMENT("adjustment"),
    APPLIED_TO_INVOICE("applied_to_invoice"),
    CREDIT_NOTE("credit_note"),
    INITIAL("initial"),
    INVOICE_OVERPAID("invoice_overpaid"),
    INVOICE_TOO_LARGE("invoice_too_large"),
    INVOICE_TOO_SMALL("invoice_too_small"),
    MIGRATION("migration"),
    UNAPPLIED_FROM_INVOICE("unapplied_from_invoice"),
    UNSPENT_RECEIVER_CREDIT("unspent_receiver_credit");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public CustomerBalanceTransaction amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The amount of the transaction. A negative value is a credit for the customer&#x27;s balance, and a positive value is a debit to the customer&#x27;s &#x60;balance&#x60;.
   * @return amount
  **/
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public CustomerBalanceTransaction created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Time at which the object was created. Measured in seconds since the Unix epoch.
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public CustomerBalanceTransaction creditNote(AnyOfcustomerBalanceTransactionCreditNote creditNote) {
    this.creditNote = creditNote;
    return this;
  }

   /**
   * The ID of the credit note (if any) related to the transaction.
   * @return creditNote
  **/
  public AnyOfcustomerBalanceTransactionCreditNote getCreditNote() {
    return creditNote;
  }

  public void setCreditNote(AnyOfcustomerBalanceTransactionCreditNote creditNote) {
    this.creditNote = creditNote;
  }

  public CustomerBalanceTransaction currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public CustomerBalanceTransaction customer(AnyOfcustomerBalanceTransactionCustomer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * The ID of the customer the transaction belongs to.
   * @return customer
  **/
  public AnyOfcustomerBalanceTransactionCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(AnyOfcustomerBalanceTransactionCustomer customer) {
    this.customer = customer;
  }

  public CustomerBalanceTransaction description(String description) {
    this.description = description;
    return this;
  }

   /**
   * An arbitrary string attached to the object. Often useful for displaying to users.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomerBalanceTransaction endingBalance(Integer endingBalance) {
    this.endingBalance = endingBalance;
    return this;
  }

   /**
   * The customer&#x27;s &#x60;balance&#x60; after the transaction was applied. A negative value decreases the amount due on the customer&#x27;s next invoice. A positive value increases the amount due on the customer&#x27;s next invoice.
   * @return endingBalance
  **/
  public Integer getEndingBalance() {
    return endingBalance;
  }

  public void setEndingBalance(Integer endingBalance) {
    this.endingBalance = endingBalance;
  }

  public CustomerBalanceTransaction id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the object.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerBalanceTransaction invoice(AnyOfcustomerBalanceTransactionInvoice invoice) {
    this.invoice = invoice;
    return this;
  }

   /**
   * The ID of the invoice (if any) related to the transaction.
   * @return invoice
  **/
  public AnyOfcustomerBalanceTransactionInvoice getInvoice() {
    return invoice;
  }

  public void setInvoice(AnyOfcustomerBalanceTransactionInvoice invoice) {
    this.invoice = invoice;
  }

  public CustomerBalanceTransaction livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Has the value &#x60;true&#x60; if the object exists in live mode or the value &#x60;false&#x60; if the object exists in test mode.
   * @return livemode
  **/
  public Boolean isLivemode() {
    return livemode;
  }

  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }

  public CustomerBalanceTransaction metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CustomerBalanceTransaction putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
   * @return metadata
  **/
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public CustomerBalanceTransaction object(ObjectEnum object) {
    this.object = object;
    return this;
  }

   /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   * @return object
  **/
  public ObjectEnum getObject() {
    return object;
  }

  public void setObject(ObjectEnum object) {
    this.object = object;
  }

  public CustomerBalanceTransaction type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Transaction type: &#x60;adjustment&#x60;, &#x60;applied_to_invoice&#x60;, &#x60;credit_note&#x60;, &#x60;initial&#x60;, &#x60;invoice_overpaid&#x60;, &#x60;invoice_too_large&#x60;, &#x60;invoice_too_small&#x60;, &#x60;unspent_receiver_credit&#x60;, or &#x60;unapplied_from_invoice&#x60;. See the [Customer Balance page](https://stripe.com/docs/billing/customer/balance#types) to learn more about transaction types.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBalanceTransaction customerBalanceTransaction = (CustomerBalanceTransaction) o;
    return Objects.equals(this.amount, customerBalanceTransaction.amount) &&
        Objects.equals(this.created, customerBalanceTransaction.created) &&
        Objects.equals(this.creditNote, customerBalanceTransaction.creditNote) &&
        Objects.equals(this.currency, customerBalanceTransaction.currency) &&
        Objects.equals(this.customer, customerBalanceTransaction.customer) &&
        Objects.equals(this.description, customerBalanceTransaction.description) &&
        Objects.equals(this.endingBalance, customerBalanceTransaction.endingBalance) &&
        Objects.equals(this.id, customerBalanceTransaction.id) &&
        Objects.equals(this.invoice, customerBalanceTransaction.invoice) &&
        Objects.equals(this.livemode, customerBalanceTransaction.livemode) &&
        Objects.equals(this.metadata, customerBalanceTransaction.metadata) &&
        Objects.equals(this.object, customerBalanceTransaction.object) &&
        Objects.equals(this.type, customerBalanceTransaction.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, created, creditNote, currency, customer, description, endingBalance, id, invoice, livemode, metadata, object, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBalanceTransaction {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    creditNote: ").append(toIndentedString(creditNote)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    endingBalance: ").append(toIndentedString(endingBalance)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoice: ").append(toIndentedString(invoice)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
