/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.EvidenceParam;

import java.util.ArrayList;
import java.util.List;
/**
 * DisputesDisputeBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class DisputesDisputeBody1 {
  @JsonProperty("amount")
  private Integer amount = null;

  @JsonProperty("evidence")
  private EvidenceParam evidence = null;

  @JsonProperty("expand")
  private List<String> expand = null;

  @JsonProperty("metadata")
  private AnyOfdisputesDisputeBody1Metadata metadata = null;

  public DisputesDisputeBody1 amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * The dispute amount in the card&#x27;s currency and in the [smallest currency unit](https://stripe.com/docs/currencies#zero-decimal).
   * @return amount
  **/
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public DisputesDisputeBody1 evidence(EvidenceParam evidence) {
    this.evidence = evidence;
    return this;
  }

   /**
   * Get evidence
   * @return evidence
  **/
  public EvidenceParam getEvidence() {
    return evidence;
  }

  public void setEvidence(EvidenceParam evidence) {
    this.evidence = evidence;
  }

  public DisputesDisputeBody1 expand(List<String> expand) {
    this.expand = expand;
    return this;
  }

  public DisputesDisputeBody1 addExpandItem(String expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

   /**
   * Specifies which fields in the response should be expanded.
   * @return expand
  **/
  public List<String> getExpand() {
    return expand;
  }

  public void setExpand(List<String> expand) {
    this.expand = expand;
  }

  public DisputesDisputeBody1 metadata(AnyOfdisputesDisputeBody1Metadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &#x60;metadata&#x60;.
   * @return metadata
  **/
  public AnyOfdisputesDisputeBody1Metadata getMetadata() {
    return metadata;
  }

  public void setMetadata(AnyOfdisputesDisputeBody1Metadata metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DisputesDisputeBody1 disputesDisputeBody1 = (DisputesDisputeBody1) o;
    return Objects.equals(this.amount, disputesDisputeBody1.amount) &&
        Objects.equals(this.evidence, disputesDisputeBody1.evidence) &&
        Objects.equals(this.expand, disputesDisputeBody1.expand) &&
        Objects.equals(this.metadata, disputesDisputeBody1.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, evidence, expand, metadata);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DisputesDisputeBody1 {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    evidence: ").append(toIndentedString(evidence)).append("\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
