/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.FinancialAccountFeaturesParam;

/**
 * FinancialAccountConfigParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class FinancialAccountConfigParam {
  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("features")
  private FinancialAccountFeaturesParam features = null;

  public FinancialAccountConfigParam enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public FinancialAccountConfigParam features(FinancialAccountFeaturesParam features) {
    this.features = features;
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  public FinancialAccountFeaturesParam getFeatures() {
    return features;
  }

  public void setFeatures(FinancialAccountFeaturesParam features) {
    this.features = features;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialAccountConfigParam financialAccountConfigParam = (FinancialAccountConfigParam) o;
    return Objects.equals(this.enabled, financialAccountConfigParam.enabled) &&
        Objects.equals(this.features, financialAccountConfigParam.features);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, features);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialAccountConfigParam {\n");
    
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
