/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.ForwardingSettings;

import java.util.ArrayList;
import java.util.List;
/**
 * FinancialAccountCloseBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class FinancialAccountCloseBody {
  @JsonProperty("expand")
  private List<String> expand = null;

  @JsonProperty("forwarding_settings")
  private ForwardingSettings forwardingSettings = null;

  public FinancialAccountCloseBody expand(List<String> expand) {
    this.expand = expand;
    return this;
  }

  public FinancialAccountCloseBody addExpandItem(String expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

   /**
   * Specifies which fields in the response should be expanded.
   * @return expand
  **/
  public List<String> getExpand() {
    return expand;
  }

  public void setExpand(List<String> expand) {
    this.expand = expand;
  }

  public FinancialAccountCloseBody forwardingSettings(ForwardingSettings forwardingSettings) {
    this.forwardingSettings = forwardingSettings;
    return this;
  }

   /**
   * Get forwardingSettings
   * @return forwardingSettings
  **/
  public ForwardingSettings getForwardingSettings() {
    return forwardingSettings;
  }

  public void setForwardingSettings(ForwardingSettings forwardingSettings) {
    this.forwardingSettings = forwardingSettings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FinancialAccountCloseBody financialAccountCloseBody = (FinancialAccountCloseBody) o;
    return Objects.equals(this.expand, financialAccountCloseBody.expand) &&
        Objects.equals(this.forwardingSettings, financialAccountCloseBody.forwardingSettings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expand, forwardingSettings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FinancialAccountCloseBody {\n");
    
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    forwardingSettings: ").append(toIndentedString(forwardingSettings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
