/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer;

/**
 * InvoicePaymentMethodOptionsCustomerBalanceBankTransfer
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class InvoicePaymentMethodOptionsCustomerBalanceBankTransfer {
  @JsonProperty("eu_bank_transfer")
  private InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer euBankTransfer = null;

  @JsonProperty("type")
  private String type = null;

  public InvoicePaymentMethodOptionsCustomerBalanceBankTransfer euBankTransfer(InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer euBankTransfer) {
    this.euBankTransfer = euBankTransfer;
    return this;
  }

   /**
   * Get euBankTransfer
   * @return euBankTransfer
  **/
  public InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer getEuBankTransfer() {
    return euBankTransfer;
  }

  public void setEuBankTransfer(InvoicePaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer euBankTransfer) {
    this.euBankTransfer = euBankTransfer;
  }

  public InvoicePaymentMethodOptionsCustomerBalanceBankTransfer type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The bank transfer type that can be used for funding. Permitted values include: &#x60;eu_bank_transfer&#x60;, &#x60;gb_bank_transfer&#x60;, &#x60;jp_bank_transfer&#x60;, &#x60;mx_bank_transfer&#x60;, or &#x60;us_bank_transfer&#x60;.
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePaymentMethodOptionsCustomerBalanceBankTransfer invoicePaymentMethodOptionsCustomerBalanceBankTransfer = (InvoicePaymentMethodOptionsCustomerBalanceBankTransfer) o;
    return Objects.equals(this.euBankTransfer, invoicePaymentMethodOptionsCustomerBalanceBankTransfer.euBankTransfer) &&
        Objects.equals(this.type, invoicePaymentMethodOptionsCustomerBalanceBankTransfer.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(euBankTransfer, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePaymentMethodOptionsCustomerBalanceBankTransfer {\n");
    
    sb.append("    euBankTransfer: ").append(toIndentedString(euBankTransfer)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
