/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.AdjustableQuantityParams;

/**
 * LineItemsUpdateParams
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class LineItemsUpdateParams {
  @JsonProperty("adjustable_quantity")
  private AdjustableQuantityParams adjustableQuantity = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("quantity")
  private Integer quantity = null;

  public LineItemsUpdateParams adjustableQuantity(AdjustableQuantityParams adjustableQuantity) {
    this.adjustableQuantity = adjustableQuantity;
    return this;
  }

   /**
   * Get adjustableQuantity
   * @return adjustableQuantity
  **/
  public AdjustableQuantityParams getAdjustableQuantity() {
    return adjustableQuantity;
  }

  public void setAdjustableQuantity(AdjustableQuantityParams adjustableQuantity) {
    this.adjustableQuantity = adjustableQuantity;
  }

  public LineItemsUpdateParams id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public LineItemsUpdateParams quantity(Integer quantity) {
    this.quantity = quantity;
    return this;
  }

   /**
   * Get quantity
   * @return quantity
  **/
  public Integer getQuantity() {
    return quantity;
  }

  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineItemsUpdateParams lineItemsUpdateParams = (LineItemsUpdateParams) o;
    return Objects.equals(this.adjustableQuantity, lineItemsUpdateParams.adjustableQuantity) &&
        Objects.equals(this.id, lineItemsUpdateParams.id) &&
        Objects.equals(this.quantity, lineItemsUpdateParams.quantity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adjustableQuantity, id, quantity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineItemsUpdateParams {\n");
    
    sb.append("    adjustableQuantity: ").append(toIndentedString(adjustableQuantity)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
