/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * MandateAcssDebit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class MandateAcssDebit {
  /**
   * Gets or Sets defaultFor
   */
  public enum DefaultForEnum {
    INVOICE("invoice"),
    SUBSCRIPTION("subscription");

    private String value;

    DefaultForEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DefaultForEnum fromValue(String input) {
      for (DefaultForEnum b : DefaultForEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("default_for")
  private List<DefaultForEnum> defaultFor = null;

  @JsonProperty("interval_description")
  private String intervalDescription = null;

  /**
   * Payment schedule for the mandate.
   */
  public enum PaymentScheduleEnum {
    COMBINED("combined"),
    INTERVAL("interval"),
    SPORADIC("sporadic");

    private String value;

    PaymentScheduleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PaymentScheduleEnum fromValue(String input) {
      for (PaymentScheduleEnum b : PaymentScheduleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("payment_schedule")
  private PaymentScheduleEnum paymentSchedule = null;

  /**
   * Transaction type of the mandate.
   */
  public enum TransactionTypeEnum {
    BUSINESS("business"),
    PERSONAL("personal");

    private String value;

    TransactionTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TransactionTypeEnum fromValue(String input) {
      for (TransactionTypeEnum b : TransactionTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("transaction_type")
  private TransactionTypeEnum transactionType = null;

  public MandateAcssDebit defaultFor(List<DefaultForEnum> defaultFor) {
    this.defaultFor = defaultFor;
    return this;
  }

  public MandateAcssDebit addDefaultForItem(DefaultForEnum defaultForItem) {
    if (this.defaultFor == null) {
      this.defaultFor = new ArrayList<>();
    }
    this.defaultFor.add(defaultForItem);
    return this;
  }

   /**
   * List of Stripe products where this mandate can be selected automatically.
   * @return defaultFor
  **/
  public List<DefaultForEnum> getDefaultFor() {
    return defaultFor;
  }

  public void setDefaultFor(List<DefaultForEnum> defaultFor) {
    this.defaultFor = defaultFor;
  }

  public MandateAcssDebit intervalDescription(String intervalDescription) {
    this.intervalDescription = intervalDescription;
    return this;
  }

   /**
   * Description of the interval. Only required if the &#x27;payment_schedule&#x27; parameter is &#x27;interval&#x27; or &#x27;combined&#x27;.
   * @return intervalDescription
  **/
  public String getIntervalDescription() {
    return intervalDescription;
  }

  public void setIntervalDescription(String intervalDescription) {
    this.intervalDescription = intervalDescription;
  }

  public MandateAcssDebit paymentSchedule(PaymentScheduleEnum paymentSchedule) {
    this.paymentSchedule = paymentSchedule;
    return this;
  }

   /**
   * Payment schedule for the mandate.
   * @return paymentSchedule
  **/
  public PaymentScheduleEnum getPaymentSchedule() {
    return paymentSchedule;
  }

  public void setPaymentSchedule(PaymentScheduleEnum paymentSchedule) {
    this.paymentSchedule = paymentSchedule;
  }

  public MandateAcssDebit transactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Transaction type of the mandate.
   * @return transactionType
  **/
  public TransactionTypeEnum getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MandateAcssDebit mandateAcssDebit = (MandateAcssDebit) o;
    return Objects.equals(this.defaultFor, mandateAcssDebit.defaultFor) &&
        Objects.equals(this.intervalDescription, mandateAcssDebit.intervalDescription) &&
        Objects.equals(this.paymentSchedule, mandateAcssDebit.paymentSchedule) &&
        Objects.equals(this.transactionType, mandateAcssDebit.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultFor, intervalDescription, paymentSchedule, transactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MandateAcssDebit {\n");
    
    sb.append("    defaultFor: ").append(toIndentedString(defaultFor)).append("\n");
    sb.append("    intervalDescription: ").append(toIndentedString(intervalDescription)).append("\n");
    sb.append("    paymentSchedule: ").append(toIndentedString(paymentSchedule)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
