/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethodDetailsCardInstallmentsPlan
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodDetailsCardInstallmentsPlan implements AnyOfpaymentMethodDetailsCardInstallmentsPlan, AnyOfpaymentMethodOptionsCardInstallmentsPlan {
  @JsonProperty("count")
  private Integer count = null;

  /**
   * For &#x60;fixed_count&#x60; installment plans, this is the interval between installment payments your customer will make to their credit card. One of &#x60;month&#x60;.
   */
  public enum IntervalEnum {
    MONTH("month");

    private String value;

    IntervalEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static IntervalEnum fromValue(String input) {
      for (IntervalEnum b : IntervalEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("interval")
  private IntervalEnum interval = null;

  /**
   * Type of installment plan, one of &#x60;fixed_count&#x60;.
   */
  public enum TypeEnum {
    FIXED_COUNT("fixed_count");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public PaymentMethodDetailsCardInstallmentsPlan count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * For &#x60;fixed_count&#x60; installment plans, this is the number of installment payments your customer will make to their credit card.
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public PaymentMethodDetailsCardInstallmentsPlan interval(IntervalEnum interval) {
    this.interval = interval;
    return this;
  }

   /**
   * For &#x60;fixed_count&#x60; installment plans, this is the interval between installment payments your customer will make to their credit card. One of &#x60;month&#x60;.
   * @return interval
  **/
  public IntervalEnum getInterval() {
    return interval;
  }

  public void setInterval(IntervalEnum interval) {
    this.interval = interval;
  }

  public PaymentMethodDetailsCardInstallmentsPlan type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Type of installment plan, one of &#x60;fixed_count&#x60;.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodDetailsCardInstallmentsPlan paymentMethodDetailsCardInstallmentsPlan = (PaymentMethodDetailsCardInstallmentsPlan) o;
    return Objects.equals(this.count, paymentMethodDetailsCardInstallmentsPlan.count) &&
        Objects.equals(this.interval, paymentMethodDetailsCardInstallmentsPlan.interval) &&
        Objects.equals(this.type, paymentMethodDetailsCardInstallmentsPlan.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, interval, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodDetailsCardInstallmentsPlan {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
