/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.PaymentIntentNextActionAlipayHandleRedirect;
import com.stripe.api.client.PaymentIntentNextActionBoleto;
import com.stripe.api.client.PaymentIntentNextActionCardAwaitNotification;
import com.stripe.api.client.PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionDisplayBankTransferInstructions;
import com.stripe.api.client.PaymentIntentNextActionDisplayMultibancoDetails;
import com.stripe.api.client.PaymentIntentNextActionDisplayOxxoDetails;
import com.stripe.api.client.PaymentIntentNextActionKonbini;
import com.stripe.api.client.PaymentIntentNextActionPaynowDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionPixDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionPromptpayDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionRedirectToUrl;
import com.stripe.api.client.PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionVerifyWithMicrodeposits;
import com.stripe.api.client.PaymentIntentNextActionWechatPayDisplayQrCode;
import com.stripe.api.client.PaymentIntentNextActionWechatPayRedirectToAndroidApp;
import com.stripe.api.client.PaymentIntentNextActionWechatPayRedirectToIosApp;

/**
 * PaymentIntentNextAction
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentIntentNextAction implements AnyOfpaymentIntentNextAction {
  @JsonProperty("alipay_handle_redirect")
  private PaymentIntentNextActionAlipayHandleRedirect alipayHandleRedirect = null;

  @JsonProperty("boleto_display_details")
  private PaymentIntentNextActionBoleto boletoDisplayDetails = null;

  @JsonProperty("card_await_notification")
  private PaymentIntentNextActionCardAwaitNotification cardAwaitNotification = null;

  @JsonProperty("cashapp_handle_redirect_or_display_qr_code")
  private PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode cashappHandleRedirectOrDisplayQrCode = null;

  @JsonProperty("display_bank_transfer_instructions")
  private PaymentIntentNextActionDisplayBankTransferInstructions displayBankTransferInstructions = null;

  @JsonProperty("konbini_display_details")
  private PaymentIntentNextActionKonbini konbiniDisplayDetails = null;

  @JsonProperty("multibanco_display_details")
  private PaymentIntentNextActionDisplayMultibancoDetails multibancoDisplayDetails = null;

  @JsonProperty("oxxo_display_details")
  private PaymentIntentNextActionDisplayOxxoDetails oxxoDisplayDetails = null;

  @JsonProperty("paynow_display_qr_code")
  private PaymentIntentNextActionPaynowDisplayQrCode paynowDisplayQrCode = null;

  @JsonProperty("pix_display_qr_code")
  private PaymentIntentNextActionPixDisplayQrCode pixDisplayQrCode = null;

  @JsonProperty("promptpay_display_qr_code")
  private PaymentIntentNextActionPromptpayDisplayQrCode promptpayDisplayQrCode = null;

  @JsonProperty("redirect_to_url")
  private PaymentIntentNextActionRedirectToUrl redirectToUrl = null;

  @JsonProperty("swish_handle_redirect_or_display_qr_code")
  private PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode swishHandleRedirectOrDisplayQrCode = null;

  @JsonProperty("type")
  private String type = null;

  @JsonProperty("use_stripe_sdk")
  private Object useStripeSdk = null;

  @JsonProperty("verify_with_microdeposits")
  private PaymentIntentNextActionVerifyWithMicrodeposits verifyWithMicrodeposits = null;

  @JsonProperty("wechat_pay_display_qr_code")
  private PaymentIntentNextActionWechatPayDisplayQrCode wechatPayDisplayQrCode = null;

  @JsonProperty("wechat_pay_redirect_to_android_app")
  private PaymentIntentNextActionWechatPayRedirectToAndroidApp wechatPayRedirectToAndroidApp = null;

  @JsonProperty("wechat_pay_redirect_to_ios_app")
  private PaymentIntentNextActionWechatPayRedirectToIosApp wechatPayRedirectToIosApp = null;

  public PaymentIntentNextAction alipayHandleRedirect(PaymentIntentNextActionAlipayHandleRedirect alipayHandleRedirect) {
    this.alipayHandleRedirect = alipayHandleRedirect;
    return this;
  }

   /**
   * Get alipayHandleRedirect
   * @return alipayHandleRedirect
  **/
  public PaymentIntentNextActionAlipayHandleRedirect getAlipayHandleRedirect() {
    return alipayHandleRedirect;
  }

  public void setAlipayHandleRedirect(PaymentIntentNextActionAlipayHandleRedirect alipayHandleRedirect) {
    this.alipayHandleRedirect = alipayHandleRedirect;
  }

  public PaymentIntentNextAction boletoDisplayDetails(PaymentIntentNextActionBoleto boletoDisplayDetails) {
    this.boletoDisplayDetails = boletoDisplayDetails;
    return this;
  }

   /**
   * Get boletoDisplayDetails
   * @return boletoDisplayDetails
  **/
  public PaymentIntentNextActionBoleto getBoletoDisplayDetails() {
    return boletoDisplayDetails;
  }

  public void setBoletoDisplayDetails(PaymentIntentNextActionBoleto boletoDisplayDetails) {
    this.boletoDisplayDetails = boletoDisplayDetails;
  }

  public PaymentIntentNextAction cardAwaitNotification(PaymentIntentNextActionCardAwaitNotification cardAwaitNotification) {
    this.cardAwaitNotification = cardAwaitNotification;
    return this;
  }

   /**
   * Get cardAwaitNotification
   * @return cardAwaitNotification
  **/
  public PaymentIntentNextActionCardAwaitNotification getCardAwaitNotification() {
    return cardAwaitNotification;
  }

  public void setCardAwaitNotification(PaymentIntentNextActionCardAwaitNotification cardAwaitNotification) {
    this.cardAwaitNotification = cardAwaitNotification;
  }

  public PaymentIntentNextAction cashappHandleRedirectOrDisplayQrCode(PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode cashappHandleRedirectOrDisplayQrCode) {
    this.cashappHandleRedirectOrDisplayQrCode = cashappHandleRedirectOrDisplayQrCode;
    return this;
  }

   /**
   * Get cashappHandleRedirectOrDisplayQrCode
   * @return cashappHandleRedirectOrDisplayQrCode
  **/
  public PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode getCashappHandleRedirectOrDisplayQrCode() {
    return cashappHandleRedirectOrDisplayQrCode;
  }

  public void setCashappHandleRedirectOrDisplayQrCode(PaymentIntentNextActionCashappHandleRedirectOrDisplayQrCode cashappHandleRedirectOrDisplayQrCode) {
    this.cashappHandleRedirectOrDisplayQrCode = cashappHandleRedirectOrDisplayQrCode;
  }

  public PaymentIntentNextAction displayBankTransferInstructions(PaymentIntentNextActionDisplayBankTransferInstructions displayBankTransferInstructions) {
    this.displayBankTransferInstructions = displayBankTransferInstructions;
    return this;
  }

   /**
   * Get displayBankTransferInstructions
   * @return displayBankTransferInstructions
  **/
  public PaymentIntentNextActionDisplayBankTransferInstructions getDisplayBankTransferInstructions() {
    return displayBankTransferInstructions;
  }

  public void setDisplayBankTransferInstructions(PaymentIntentNextActionDisplayBankTransferInstructions displayBankTransferInstructions) {
    this.displayBankTransferInstructions = displayBankTransferInstructions;
  }

  public PaymentIntentNextAction konbiniDisplayDetails(PaymentIntentNextActionKonbini konbiniDisplayDetails) {
    this.konbiniDisplayDetails = konbiniDisplayDetails;
    return this;
  }

   /**
   * Get konbiniDisplayDetails
   * @return konbiniDisplayDetails
  **/
  public PaymentIntentNextActionKonbini getKonbiniDisplayDetails() {
    return konbiniDisplayDetails;
  }

  public void setKonbiniDisplayDetails(PaymentIntentNextActionKonbini konbiniDisplayDetails) {
    this.konbiniDisplayDetails = konbiniDisplayDetails;
  }

  public PaymentIntentNextAction multibancoDisplayDetails(PaymentIntentNextActionDisplayMultibancoDetails multibancoDisplayDetails) {
    this.multibancoDisplayDetails = multibancoDisplayDetails;
    return this;
  }

   /**
   * Get multibancoDisplayDetails
   * @return multibancoDisplayDetails
  **/
  public PaymentIntentNextActionDisplayMultibancoDetails getMultibancoDisplayDetails() {
    return multibancoDisplayDetails;
  }

  public void setMultibancoDisplayDetails(PaymentIntentNextActionDisplayMultibancoDetails multibancoDisplayDetails) {
    this.multibancoDisplayDetails = multibancoDisplayDetails;
  }

  public PaymentIntentNextAction oxxoDisplayDetails(PaymentIntentNextActionDisplayOxxoDetails oxxoDisplayDetails) {
    this.oxxoDisplayDetails = oxxoDisplayDetails;
    return this;
  }

   /**
   * Get oxxoDisplayDetails
   * @return oxxoDisplayDetails
  **/
  public PaymentIntentNextActionDisplayOxxoDetails getOxxoDisplayDetails() {
    return oxxoDisplayDetails;
  }

  public void setOxxoDisplayDetails(PaymentIntentNextActionDisplayOxxoDetails oxxoDisplayDetails) {
    this.oxxoDisplayDetails = oxxoDisplayDetails;
  }

  public PaymentIntentNextAction paynowDisplayQrCode(PaymentIntentNextActionPaynowDisplayQrCode paynowDisplayQrCode) {
    this.paynowDisplayQrCode = paynowDisplayQrCode;
    return this;
  }

   /**
   * Get paynowDisplayQrCode
   * @return paynowDisplayQrCode
  **/
  public PaymentIntentNextActionPaynowDisplayQrCode getPaynowDisplayQrCode() {
    return paynowDisplayQrCode;
  }

  public void setPaynowDisplayQrCode(PaymentIntentNextActionPaynowDisplayQrCode paynowDisplayQrCode) {
    this.paynowDisplayQrCode = paynowDisplayQrCode;
  }

  public PaymentIntentNextAction pixDisplayQrCode(PaymentIntentNextActionPixDisplayQrCode pixDisplayQrCode) {
    this.pixDisplayQrCode = pixDisplayQrCode;
    return this;
  }

   /**
   * Get pixDisplayQrCode
   * @return pixDisplayQrCode
  **/
  public PaymentIntentNextActionPixDisplayQrCode getPixDisplayQrCode() {
    return pixDisplayQrCode;
  }

  public void setPixDisplayQrCode(PaymentIntentNextActionPixDisplayQrCode pixDisplayQrCode) {
    this.pixDisplayQrCode = pixDisplayQrCode;
  }

  public PaymentIntentNextAction promptpayDisplayQrCode(PaymentIntentNextActionPromptpayDisplayQrCode promptpayDisplayQrCode) {
    this.promptpayDisplayQrCode = promptpayDisplayQrCode;
    return this;
  }

   /**
   * Get promptpayDisplayQrCode
   * @return promptpayDisplayQrCode
  **/
  public PaymentIntentNextActionPromptpayDisplayQrCode getPromptpayDisplayQrCode() {
    return promptpayDisplayQrCode;
  }

  public void setPromptpayDisplayQrCode(PaymentIntentNextActionPromptpayDisplayQrCode promptpayDisplayQrCode) {
    this.promptpayDisplayQrCode = promptpayDisplayQrCode;
  }

  public PaymentIntentNextAction redirectToUrl(PaymentIntentNextActionRedirectToUrl redirectToUrl) {
    this.redirectToUrl = redirectToUrl;
    return this;
  }

   /**
   * Get redirectToUrl
   * @return redirectToUrl
  **/
  public PaymentIntentNextActionRedirectToUrl getRedirectToUrl() {
    return redirectToUrl;
  }

  public void setRedirectToUrl(PaymentIntentNextActionRedirectToUrl redirectToUrl) {
    this.redirectToUrl = redirectToUrl;
  }

  public PaymentIntentNextAction swishHandleRedirectOrDisplayQrCode(PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode swishHandleRedirectOrDisplayQrCode) {
    this.swishHandleRedirectOrDisplayQrCode = swishHandleRedirectOrDisplayQrCode;
    return this;
  }

   /**
   * Get swishHandleRedirectOrDisplayQrCode
   * @return swishHandleRedirectOrDisplayQrCode
  **/
  public PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode getSwishHandleRedirectOrDisplayQrCode() {
    return swishHandleRedirectOrDisplayQrCode;
  }

  public void setSwishHandleRedirectOrDisplayQrCode(PaymentIntentNextActionSwishHandleRedirectOrDisplayQrCode swishHandleRedirectOrDisplayQrCode) {
    this.swishHandleRedirectOrDisplayQrCode = swishHandleRedirectOrDisplayQrCode;
  }

  public PaymentIntentNextAction type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of the next action to perform, one of &#x60;redirect_to_url&#x60;, &#x60;use_stripe_sdk&#x60;, &#x60;alipay_handle_redirect&#x60;, &#x60;oxxo_display_details&#x60;, or &#x60;verify_with_microdeposits&#x60;.
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PaymentIntentNextAction useStripeSdk(Object useStripeSdk) {
    this.useStripeSdk = useStripeSdk;
    return this;
  }

   /**
   * When confirming a PaymentIntent with Stripe.js, Stripe.js depends on the contents of this dictionary to invoke authentication flows. The shape of the contents is subject to change and is only intended to be used by Stripe.js.
   * @return useStripeSdk
  **/
  public Object getUseStripeSdk() {
    return useStripeSdk;
  }

  public void setUseStripeSdk(Object useStripeSdk) {
    this.useStripeSdk = useStripeSdk;
  }

  public PaymentIntentNextAction verifyWithMicrodeposits(PaymentIntentNextActionVerifyWithMicrodeposits verifyWithMicrodeposits) {
    this.verifyWithMicrodeposits = verifyWithMicrodeposits;
    return this;
  }

   /**
   * Get verifyWithMicrodeposits
   * @return verifyWithMicrodeposits
  **/
  public PaymentIntentNextActionVerifyWithMicrodeposits getVerifyWithMicrodeposits() {
    return verifyWithMicrodeposits;
  }

  public void setVerifyWithMicrodeposits(PaymentIntentNextActionVerifyWithMicrodeposits verifyWithMicrodeposits) {
    this.verifyWithMicrodeposits = verifyWithMicrodeposits;
  }

  public PaymentIntentNextAction wechatPayDisplayQrCode(PaymentIntentNextActionWechatPayDisplayQrCode wechatPayDisplayQrCode) {
    this.wechatPayDisplayQrCode = wechatPayDisplayQrCode;
    return this;
  }

   /**
   * Get wechatPayDisplayQrCode
   * @return wechatPayDisplayQrCode
  **/
  public PaymentIntentNextActionWechatPayDisplayQrCode getWechatPayDisplayQrCode() {
    return wechatPayDisplayQrCode;
  }

  public void setWechatPayDisplayQrCode(PaymentIntentNextActionWechatPayDisplayQrCode wechatPayDisplayQrCode) {
    this.wechatPayDisplayQrCode = wechatPayDisplayQrCode;
  }

  public PaymentIntentNextAction wechatPayRedirectToAndroidApp(PaymentIntentNextActionWechatPayRedirectToAndroidApp wechatPayRedirectToAndroidApp) {
    this.wechatPayRedirectToAndroidApp = wechatPayRedirectToAndroidApp;
    return this;
  }

   /**
   * Get wechatPayRedirectToAndroidApp
   * @return wechatPayRedirectToAndroidApp
  **/
  public PaymentIntentNextActionWechatPayRedirectToAndroidApp getWechatPayRedirectToAndroidApp() {
    return wechatPayRedirectToAndroidApp;
  }

  public void setWechatPayRedirectToAndroidApp(PaymentIntentNextActionWechatPayRedirectToAndroidApp wechatPayRedirectToAndroidApp) {
    this.wechatPayRedirectToAndroidApp = wechatPayRedirectToAndroidApp;
  }

  public PaymentIntentNextAction wechatPayRedirectToIosApp(PaymentIntentNextActionWechatPayRedirectToIosApp wechatPayRedirectToIosApp) {
    this.wechatPayRedirectToIosApp = wechatPayRedirectToIosApp;
    return this;
  }

   /**
   * Get wechatPayRedirectToIosApp
   * @return wechatPayRedirectToIosApp
  **/
  public PaymentIntentNextActionWechatPayRedirectToIosApp getWechatPayRedirectToIosApp() {
    return wechatPayRedirectToIosApp;
  }

  public void setWechatPayRedirectToIosApp(PaymentIntentNextActionWechatPayRedirectToIosApp wechatPayRedirectToIosApp) {
    this.wechatPayRedirectToIosApp = wechatPayRedirectToIosApp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentIntentNextAction paymentIntentNextAction = (PaymentIntentNextAction) o;
    return Objects.equals(this.alipayHandleRedirect, paymentIntentNextAction.alipayHandleRedirect) &&
        Objects.equals(this.boletoDisplayDetails, paymentIntentNextAction.boletoDisplayDetails) &&
        Objects.equals(this.cardAwaitNotification, paymentIntentNextAction.cardAwaitNotification) &&
        Objects.equals(this.cashappHandleRedirectOrDisplayQrCode, paymentIntentNextAction.cashappHandleRedirectOrDisplayQrCode) &&
        Objects.equals(this.displayBankTransferInstructions, paymentIntentNextAction.displayBankTransferInstructions) &&
        Objects.equals(this.konbiniDisplayDetails, paymentIntentNextAction.konbiniDisplayDetails) &&
        Objects.equals(this.multibancoDisplayDetails, paymentIntentNextAction.multibancoDisplayDetails) &&
        Objects.equals(this.oxxoDisplayDetails, paymentIntentNextAction.oxxoDisplayDetails) &&
        Objects.equals(this.paynowDisplayQrCode, paymentIntentNextAction.paynowDisplayQrCode) &&
        Objects.equals(this.pixDisplayQrCode, paymentIntentNextAction.pixDisplayQrCode) &&
        Objects.equals(this.promptpayDisplayQrCode, paymentIntentNextAction.promptpayDisplayQrCode) &&
        Objects.equals(this.redirectToUrl, paymentIntentNextAction.redirectToUrl) &&
        Objects.equals(this.swishHandleRedirectOrDisplayQrCode, paymentIntentNextAction.swishHandleRedirectOrDisplayQrCode) &&
        Objects.equals(this.type, paymentIntentNextAction.type) &&
        Objects.equals(this.useStripeSdk, paymentIntentNextAction.useStripeSdk) &&
        Objects.equals(this.verifyWithMicrodeposits, paymentIntentNextAction.verifyWithMicrodeposits) &&
        Objects.equals(this.wechatPayDisplayQrCode, paymentIntentNextAction.wechatPayDisplayQrCode) &&
        Objects.equals(this.wechatPayRedirectToAndroidApp, paymentIntentNextAction.wechatPayRedirectToAndroidApp) &&
        Objects.equals(this.wechatPayRedirectToIosApp, paymentIntentNextAction.wechatPayRedirectToIosApp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alipayHandleRedirect, boletoDisplayDetails, cardAwaitNotification, cashappHandleRedirectOrDisplayQrCode, displayBankTransferInstructions, konbiniDisplayDetails, multibancoDisplayDetails, oxxoDisplayDetails, paynowDisplayQrCode, pixDisplayQrCode, promptpayDisplayQrCode, redirectToUrl, swishHandleRedirectOrDisplayQrCode, type, useStripeSdk, verifyWithMicrodeposits, wechatPayDisplayQrCode, wechatPayRedirectToAndroidApp, wechatPayRedirectToIosApp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentIntentNextAction {\n");
    
    sb.append("    alipayHandleRedirect: ").append(toIndentedString(alipayHandleRedirect)).append("\n");
    sb.append("    boletoDisplayDetails: ").append(toIndentedString(boletoDisplayDetails)).append("\n");
    sb.append("    cardAwaitNotification: ").append(toIndentedString(cardAwaitNotification)).append("\n");
    sb.append("    cashappHandleRedirectOrDisplayQrCode: ").append(toIndentedString(cashappHandleRedirectOrDisplayQrCode)).append("\n");
    sb.append("    displayBankTransferInstructions: ").append(toIndentedString(displayBankTransferInstructions)).append("\n");
    sb.append("    konbiniDisplayDetails: ").append(toIndentedString(konbiniDisplayDetails)).append("\n");
    sb.append("    multibancoDisplayDetails: ").append(toIndentedString(multibancoDisplayDetails)).append("\n");
    sb.append("    oxxoDisplayDetails: ").append(toIndentedString(oxxoDisplayDetails)).append("\n");
    sb.append("    paynowDisplayQrCode: ").append(toIndentedString(paynowDisplayQrCode)).append("\n");
    sb.append("    pixDisplayQrCode: ").append(toIndentedString(pixDisplayQrCode)).append("\n");
    sb.append("    promptpayDisplayQrCode: ").append(toIndentedString(promptpayDisplayQrCode)).append("\n");
    sb.append("    redirectToUrl: ").append(toIndentedString(redirectToUrl)).append("\n");
    sb.append("    swishHandleRedirectOrDisplayQrCode: ").append(toIndentedString(swishHandleRedirectOrDisplayQrCode)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    useStripeSdk: ").append(toIndentedString(useStripeSdk)).append("\n");
    sb.append("    verifyWithMicrodeposits: ").append(toIndentedString(verifyWithMicrodeposits)).append("\n");
    sb.append("    wechatPayDisplayQrCode: ").append(toIndentedString(wechatPayDisplayQrCode)).append("\n");
    sb.append("    wechatPayRedirectToAndroidApp: ").append(toIndentedString(wechatPayRedirectToAndroidApp)).append("\n");
    sb.append("    wechatPayRedirectToIosApp: ").append(toIndentedString(wechatPayRedirectToIosApp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
