/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet;

import java.util.ArrayList;
import java.util.List;
/**
 * PaymentMethodDetailsCardPresent
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodDetailsCardPresent {
  @JsonProperty("amount_authorized")
  private Integer amountAuthorized = null;

  @JsonProperty("brand")
  private String brand = null;

  @JsonProperty("brand_product")
  private String brandProduct = null;

  @JsonProperty("capture_before")
  private Integer captureBefore = null;

  @JsonProperty("cardholder_name")
  private String cardholderName = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("emv_auth_data")
  private String emvAuthData = null;

  @JsonProperty("exp_month")
  private Integer expMonth = null;

  @JsonProperty("exp_year")
  private Integer expYear = null;

  @JsonProperty("fingerprint")
  private String fingerprint = null;

  @JsonProperty("funding")
  private String funding = null;

  @JsonProperty("generated_card")
  private String generatedCard = null;

  @JsonProperty("incremental_authorization_supported")
  private Boolean incrementalAuthorizationSupported = null;

  @JsonProperty("issuer")
  private String issuer = null;

  @JsonProperty("last4")
  private String last4 = null;

  @JsonProperty("network")
  private String network = null;

  @JsonProperty("network_transaction_id")
  private String networkTransactionId = null;

  @JsonProperty("offline")
  private AnyOfpaymentMethodDetailsCardPresentOffline offline = null;

  @JsonProperty("overcapture_supported")
  private Boolean overcaptureSupported = null;

  @JsonProperty("preferred_locales")
  private List<String> preferredLocales = null;

  /**
   * How card details were read in this transaction.
   */
  public enum ReadMethodEnum {
    CONTACT_EMV("contact_emv"),
    CONTACTLESS_EMV("contactless_emv"),
    CONTACTLESS_MAGSTRIPE_MODE("contactless_magstripe_mode"),
    MAGNETIC_STRIPE_FALLBACK("magnetic_stripe_fallback"),
    MAGNETIC_STRIPE_TRACK2("magnetic_stripe_track2");

    private String value;

    ReadMethodEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReadMethodEnum fromValue(String input) {
      for (ReadMethodEnum b : ReadMethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("read_method")
  private ReadMethodEnum readMethod = null;

  @JsonProperty("receipt")
  private AnyOfpaymentMethodDetailsCardPresentReceipt receipt = null;

  @JsonProperty("wallet")
  private PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet wallet = null;

  public PaymentMethodDetailsCardPresent amountAuthorized(Integer amountAuthorized) {
    this.amountAuthorized = amountAuthorized;
    return this;
  }

   /**
   * The authorized amount
   * @return amountAuthorized
  **/
  public Integer getAmountAuthorized() {
    return amountAuthorized;
  }

  public void setAmountAuthorized(Integer amountAuthorized) {
    this.amountAuthorized = amountAuthorized;
  }

  public PaymentMethodDetailsCardPresent brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Card brand. Can be &#x60;amex&#x60;, &#x60;diners&#x60;, &#x60;discover&#x60;, &#x60;eftpos_au&#x60;, &#x60;jcb&#x60;, &#x60;link&#x60;, &#x60;mastercard&#x60;, &#x60;unionpay&#x60;, &#x60;visa&#x60;, or &#x60;unknown&#x60;.
   * @return brand
  **/
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public PaymentMethodDetailsCardPresent brandProduct(String brandProduct) {
    this.brandProduct = brandProduct;
    return this;
  }

   /**
   * The [product code](https://stripe.com/docs/card-product-codes) that identifies the specific program or product associated with a card.
   * @return brandProduct
  **/
  public String getBrandProduct() {
    return brandProduct;
  }

  public void setBrandProduct(String brandProduct) {
    this.brandProduct = brandProduct;
  }

  public PaymentMethodDetailsCardPresent captureBefore(Integer captureBefore) {
    this.captureBefore = captureBefore;
    return this;
  }

   /**
   * When using manual capture, a future timestamp after which the charge will be automatically refunded if uncaptured.
   * @return captureBefore
  **/
  public Integer getCaptureBefore() {
    return captureBefore;
  }

  public void setCaptureBefore(Integer captureBefore) {
    this.captureBefore = captureBefore;
  }

  public PaymentMethodDetailsCardPresent cardholderName(String cardholderName) {
    this.cardholderName = cardholderName;
    return this;
  }

   /**
   * The cardholder name as read from the card, in [ISO 7813](https://en.wikipedia.org/wiki/ISO/IEC_7813) format. May include alphanumeric characters, special characters and first/last name separator (&#x60;/&#x60;). In some cases, the cardholder name may not be available depending on how the issuer has configured the card. Cardholder name is typically not available on swipe or contactless payments, such as those made with Apple Pay and Google Pay.
   * @return cardholderName
  **/
  public String getCardholderName() {
    return cardholderName;
  }

  public void setCardholderName(String cardholderName) {
    this.cardholderName = cardholderName;
  }

  public PaymentMethodDetailsCardPresent country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you&#x27;ve collected.
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public PaymentMethodDetailsCardPresent description(String description) {
    this.description = description;
    return this;
  }

   /**
   * A high-level description of the type of cards issued in this range.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public PaymentMethodDetailsCardPresent emvAuthData(String emvAuthData) {
    this.emvAuthData = emvAuthData;
    return this;
  }

   /**
   * Authorization response cryptogram.
   * @return emvAuthData
  **/
  public String getEmvAuthData() {
    return emvAuthData;
  }

  public void setEmvAuthData(String emvAuthData) {
    this.emvAuthData = emvAuthData;
  }

  public PaymentMethodDetailsCardPresent expMonth(Integer expMonth) {
    this.expMonth = expMonth;
    return this;
  }

   /**
   * Two-digit number representing the card&#x27;s expiration month.
   * @return expMonth
  **/
  public Integer getExpMonth() {
    return expMonth;
  }

  public void setExpMonth(Integer expMonth) {
    this.expMonth = expMonth;
  }

  public PaymentMethodDetailsCardPresent expYear(Integer expYear) {
    this.expYear = expYear;
    return this;
  }

   /**
   * Four-digit number representing the card&#x27;s expiration year.
   * @return expYear
  **/
  public Integer getExpYear() {
    return expYear;
  }

  public void setExpYear(Integer expYear) {
    this.expYear = expYear;
  }

  public PaymentMethodDetailsCardPresent fingerprint(String fingerprint) {
    this.fingerprint = fingerprint;
    return this;
  }

   /**
   * Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card number.  *As of May 1, 2021, card fingerprint in India for Connect changed to allow two fingerprints for the same card---one for India and one for the rest of the world.*
   * @return fingerprint
  **/
  public String getFingerprint() {
    return fingerprint;
  }

  public void setFingerprint(String fingerprint) {
    this.fingerprint = fingerprint;
  }

  public PaymentMethodDetailsCardPresent funding(String funding) {
    this.funding = funding;
    return this;
  }

   /**
   * Card funding type. Can be &#x60;credit&#x60;, &#x60;debit&#x60;, &#x60;prepaid&#x60;, or &#x60;unknown&#x60;.
   * @return funding
  **/
  public String getFunding() {
    return funding;
  }

  public void setFunding(String funding) {
    this.funding = funding;
  }

  public PaymentMethodDetailsCardPresent generatedCard(String generatedCard) {
    this.generatedCard = generatedCard;
    return this;
  }

   /**
   * ID of a card PaymentMethod generated from the card_present PaymentMethod that may be attached to a Customer for future transactions. Only present if it was possible to generate a card PaymentMethod.
   * @return generatedCard
  **/
  public String getGeneratedCard() {
    return generatedCard;
  }

  public void setGeneratedCard(String generatedCard) {
    this.generatedCard = generatedCard;
  }

  public PaymentMethodDetailsCardPresent incrementalAuthorizationSupported(Boolean incrementalAuthorizationSupported) {
    this.incrementalAuthorizationSupported = incrementalAuthorizationSupported;
    return this;
  }

   /**
   * Whether this [PaymentIntent](https://stripe.com/docs/api/payment_intents) is eligible for incremental authorizations. Request support using [request_incremental_authorization_support](https://stripe.com/docs/api/payment_intents/create#create_payment_intent-payment_method_options-card_present-request_incremental_authorization_support).
   * @return incrementalAuthorizationSupported
  **/
  public Boolean isIncrementalAuthorizationSupported() {
    return incrementalAuthorizationSupported;
  }

  public void setIncrementalAuthorizationSupported(Boolean incrementalAuthorizationSupported) {
    this.incrementalAuthorizationSupported = incrementalAuthorizationSupported;
  }

  public PaymentMethodDetailsCardPresent issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

   /**
   * The name of the card&#x27;s issuing bank.
   * @return issuer
  **/
  public String getIssuer() {
    return issuer;
  }

  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }

  public PaymentMethodDetailsCardPresent last4(String last4) {
    this.last4 = last4;
    return this;
  }

   /**
   * The last four digits of the card.
   * @return last4
  **/
  public String getLast4() {
    return last4;
  }

  public void setLast4(String last4) {
    this.last4 = last4;
  }

  public PaymentMethodDetailsCardPresent network(String network) {
    this.network = network;
    return this;
  }

   /**
   * Identifies which network this charge was processed on. Can be &#x60;amex&#x60;, &#x60;cartes_bancaires&#x60;, &#x60;diners&#x60;, &#x60;discover&#x60;, &#x60;eftpos_au&#x60;, &#x60;interac&#x60;, &#x60;jcb&#x60;, &#x60;link&#x60;, &#x60;mastercard&#x60;, &#x60;unionpay&#x60;, &#x60;visa&#x60;, or &#x60;unknown&#x60;.
   * @return network
  **/
  public String getNetwork() {
    return network;
  }

  public void setNetwork(String network) {
    this.network = network;
  }

  public PaymentMethodDetailsCardPresent networkTransactionId(String networkTransactionId) {
    this.networkTransactionId = networkTransactionId;
    return this;
  }

   /**
   * This is used by the financial networks to identify a transaction. Visa calls this the Transaction ID, Mastercard calls this the Trace ID, and American Express calls this the Acquirer Reference Data. The first three digits of the Trace ID is the Financial Network Code, the next 6 digits is the Banknet Reference Number, and the last 4 digits represent the date (MM/DD). This field will be available for successful Visa, Mastercard, or American Express transactions and always null for other card brands.
   * @return networkTransactionId
  **/
  public String getNetworkTransactionId() {
    return networkTransactionId;
  }

  public void setNetworkTransactionId(String networkTransactionId) {
    this.networkTransactionId = networkTransactionId;
  }

  public PaymentMethodDetailsCardPresent offline(AnyOfpaymentMethodDetailsCardPresentOffline offline) {
    this.offline = offline;
    return this;
  }

   /**
   * Details about payments collected offline.
   * @return offline
  **/
  public AnyOfpaymentMethodDetailsCardPresentOffline getOffline() {
    return offline;
  }

  public void setOffline(AnyOfpaymentMethodDetailsCardPresentOffline offline) {
    this.offline = offline;
  }

  public PaymentMethodDetailsCardPresent overcaptureSupported(Boolean overcaptureSupported) {
    this.overcaptureSupported = overcaptureSupported;
    return this;
  }

   /**
   * Defines whether the authorized amount can be over-captured or not
   * @return overcaptureSupported
  **/
  public Boolean isOvercaptureSupported() {
    return overcaptureSupported;
  }

  public void setOvercaptureSupported(Boolean overcaptureSupported) {
    this.overcaptureSupported = overcaptureSupported;
  }

  public PaymentMethodDetailsCardPresent preferredLocales(List<String> preferredLocales) {
    this.preferredLocales = preferredLocales;
    return this;
  }

  public PaymentMethodDetailsCardPresent addPreferredLocalesItem(String preferredLocalesItem) {
    if (this.preferredLocales == null) {
      this.preferredLocales = new ArrayList<>();
    }
    this.preferredLocales.add(preferredLocalesItem);
    return this;
  }

   /**
   * EMV tag 5F2D. Preferred languages specified by the integrated circuit chip.
   * @return preferredLocales
  **/
  public List<String> getPreferredLocales() {
    return preferredLocales;
  }

  public void setPreferredLocales(List<String> preferredLocales) {
    this.preferredLocales = preferredLocales;
  }

  public PaymentMethodDetailsCardPresent readMethod(ReadMethodEnum readMethod) {
    this.readMethod = readMethod;
    return this;
  }

   /**
   * How card details were read in this transaction.
   * @return readMethod
  **/
  public ReadMethodEnum getReadMethod() {
    return readMethod;
  }

  public void setReadMethod(ReadMethodEnum readMethod) {
    this.readMethod = readMethod;
  }

  public PaymentMethodDetailsCardPresent receipt(AnyOfpaymentMethodDetailsCardPresentReceipt receipt) {
    this.receipt = receipt;
    return this;
  }

   /**
   * A collection of fields required to be displayed on receipts. Only required for EMV transactions.
   * @return receipt
  **/
  public AnyOfpaymentMethodDetailsCardPresentReceipt getReceipt() {
    return receipt;
  }

  public void setReceipt(AnyOfpaymentMethodDetailsCardPresentReceipt receipt) {
    this.receipt = receipt;
  }

  public PaymentMethodDetailsCardPresent wallet(PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet wallet) {
    this.wallet = wallet;
    return this;
  }

   /**
   * Get wallet
   * @return wallet
  **/
  public PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet getWallet() {
    return wallet;
  }

  public void setWallet(PaymentFlowsPrivatePaymentMethodsCardPresentCommonWallet wallet) {
    this.wallet = wallet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodDetailsCardPresent paymentMethodDetailsCardPresent = (PaymentMethodDetailsCardPresent) o;
    return Objects.equals(this.amountAuthorized, paymentMethodDetailsCardPresent.amountAuthorized) &&
        Objects.equals(this.brand, paymentMethodDetailsCardPresent.brand) &&
        Objects.equals(this.brandProduct, paymentMethodDetailsCardPresent.brandProduct) &&
        Objects.equals(this.captureBefore, paymentMethodDetailsCardPresent.captureBefore) &&
        Objects.equals(this.cardholderName, paymentMethodDetailsCardPresent.cardholderName) &&
        Objects.equals(this.country, paymentMethodDetailsCardPresent.country) &&
        Objects.equals(this.description, paymentMethodDetailsCardPresent.description) &&
        Objects.equals(this.emvAuthData, paymentMethodDetailsCardPresent.emvAuthData) &&
        Objects.equals(this.expMonth, paymentMethodDetailsCardPresent.expMonth) &&
        Objects.equals(this.expYear, paymentMethodDetailsCardPresent.expYear) &&
        Objects.equals(this.fingerprint, paymentMethodDetailsCardPresent.fingerprint) &&
        Objects.equals(this.funding, paymentMethodDetailsCardPresent.funding) &&
        Objects.equals(this.generatedCard, paymentMethodDetailsCardPresent.generatedCard) &&
        Objects.equals(this.incrementalAuthorizationSupported, paymentMethodDetailsCardPresent.incrementalAuthorizationSupported) &&
        Objects.equals(this.issuer, paymentMethodDetailsCardPresent.issuer) &&
        Objects.equals(this.last4, paymentMethodDetailsCardPresent.last4) &&
        Objects.equals(this.network, paymentMethodDetailsCardPresent.network) &&
        Objects.equals(this.networkTransactionId, paymentMethodDetailsCardPresent.networkTransactionId) &&
        Objects.equals(this.offline, paymentMethodDetailsCardPresent.offline) &&
        Objects.equals(this.overcaptureSupported, paymentMethodDetailsCardPresent.overcaptureSupported) &&
        Objects.equals(this.preferredLocales, paymentMethodDetailsCardPresent.preferredLocales) &&
        Objects.equals(this.readMethod, paymentMethodDetailsCardPresent.readMethod) &&
        Objects.equals(this.receipt, paymentMethodDetailsCardPresent.receipt) &&
        Objects.equals(this.wallet, paymentMethodDetailsCardPresent.wallet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountAuthorized, brand, brandProduct, captureBefore, cardholderName, country, description, emvAuthData, expMonth, expYear, fingerprint, funding, generatedCard, incrementalAuthorizationSupported, issuer, last4, network, networkTransactionId, offline, overcaptureSupported, preferredLocales, readMethod, receipt, wallet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodDetailsCardPresent {\n");
    
    sb.append("    amountAuthorized: ").append(toIndentedString(amountAuthorized)).append("\n");
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    brandProduct: ").append(toIndentedString(brandProduct)).append("\n");
    sb.append("    captureBefore: ").append(toIndentedString(captureBefore)).append("\n");
    sb.append("    cardholderName: ").append(toIndentedString(cardholderName)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    emvAuthData: ").append(toIndentedString(emvAuthData)).append("\n");
    sb.append("    expMonth: ").append(toIndentedString(expMonth)).append("\n");
    sb.append("    expYear: ").append(toIndentedString(expYear)).append("\n");
    sb.append("    fingerprint: ").append(toIndentedString(fingerprint)).append("\n");
    sb.append("    funding: ").append(toIndentedString(funding)).append("\n");
    sb.append("    generatedCard: ").append(toIndentedString(generatedCard)).append("\n");
    sb.append("    incrementalAuthorizationSupported: ").append(toIndentedString(incrementalAuthorizationSupported)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("    last4: ").append(toIndentedString(last4)).append("\n");
    sb.append("    network: ").append(toIndentedString(network)).append("\n");
    sb.append("    networkTransactionId: ").append(toIndentedString(networkTransactionId)).append("\n");
    sb.append("    offline: ").append(toIndentedString(offline)).append("\n");
    sb.append("    overcaptureSupported: ").append(toIndentedString(overcaptureSupported)).append("\n");
    sb.append("    preferredLocales: ").append(toIndentedString(preferredLocales)).append("\n");
    sb.append("    readMethod: ").append(toIndentedString(readMethod)).append("\n");
    sb.append("    receipt: ").append(toIndentedString(receipt)).append("\n");
    sb.append("    wallet: ").append(toIndentedString(wallet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
