/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethodP24
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodP24 {
  /**
   * The customer&#x27;s bank, if provided.
   */
  public enum BankEnum {
    ALIOR_BANK("alior_bank"),
    BANK_MILLENNIUM("bank_millennium"),
    BANK_NOWY_BFG_SA("bank_nowy_bfg_sa"),
    BANK_PEKAO_SA("bank_pekao_sa"),
    BANKI_SPBDZIELCZE("banki_spbdzielcze"),
    BLIK("blik"),
    BNP_PARIBAS("bnp_paribas"),
    BOZ("boz"),
    CITI_HANDLOWY("citi_handlowy"),
    CREDIT_AGRICOLE("credit_agricole"),
    ENVELOBANK("envelobank"),
    ETRANSFER_POCZTOWY24("etransfer_pocztowy24"),
    GETIN_BANK("getin_bank"),
    IDEABANK("ideabank"),
    ING("ing"),
    INTELIGO("inteligo"),
    MBANK_MTRANSFER("mbank_mtransfer"),
    NEST_PRZELEW("nest_przelew"),
    NOBLE_PAY("noble_pay"),
    PBAC_Z_IPKO("pbac_z_ipko"),
    PLUS_BANK("plus_bank"),
    SANTANDER_PRZELEW24("santander_przelew24"),
    TMOBILE_USBUGI_BANKOWE("tmobile_usbugi_bankowe"),
    TOYOTA_BANK("toyota_bank"),
    VELOBANK("velobank"),
    VOLKSWAGEN_BANK("volkswagen_bank");

    private String value;

    BankEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static BankEnum fromValue(String input) {
      for (BankEnum b : BankEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("bank")
  private BankEnum bank = null;

  public PaymentMethodP24 bank(BankEnum bank) {
    this.bank = bank;
    return this;
  }

   /**
   * The customer&#x27;s bank, if provided.
   * @return bank
  **/
  public BankEnum getBank() {
    return bank;
  }

  public void setBank(BankEnum bank) {
    this.bank = bank;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodP24 paymentMethodP24 = (PaymentMethodP24) o;
    return Objects.equals(this.bank, paymentMethodP24.bank);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bank);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodP24 {\n");
    
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
