/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentPagesCheckoutSessionCurrencyConversion
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentPagesCheckoutSessionCurrencyConversion implements AnyOfcheckoutSessionCurrencyConversion {
  @JsonProperty("amount_subtotal")
  private Integer amountSubtotal = null;

  @JsonProperty("amount_total")
  private Integer amountTotal = null;

  @JsonProperty("fx_rate")
  private String fxRate = null;

  @JsonProperty("source_currency")
  private String sourceCurrency = null;

  public PaymentPagesCheckoutSessionCurrencyConversion amountSubtotal(Integer amountSubtotal) {
    this.amountSubtotal = amountSubtotal;
    return this;
  }

   /**
   * Total of all items in source currency before discounts or taxes are applied.
   * @return amountSubtotal
  **/
  public Integer getAmountSubtotal() {
    return amountSubtotal;
  }

  public void setAmountSubtotal(Integer amountSubtotal) {
    this.amountSubtotal = amountSubtotal;
  }

  public PaymentPagesCheckoutSessionCurrencyConversion amountTotal(Integer amountTotal) {
    this.amountTotal = amountTotal;
    return this;
  }

   /**
   * Total of all items in source currency after discounts and taxes are applied.
   * @return amountTotal
  **/
  public Integer getAmountTotal() {
    return amountTotal;
  }

  public void setAmountTotal(Integer amountTotal) {
    this.amountTotal = amountTotal;
  }

  public PaymentPagesCheckoutSessionCurrencyConversion fxRate(String fxRate) {
    this.fxRate = fxRate;
    return this;
  }

   /**
   * Exchange rate used to convert source currency amounts to customer currency amounts
   * @return fxRate
  **/
  public String getFxRate() {
    return fxRate;
  }

  public void setFxRate(String fxRate) {
    this.fxRate = fxRate;
  }

  public PaymentPagesCheckoutSessionCurrencyConversion sourceCurrency(String sourceCurrency) {
    this.sourceCurrency = sourceCurrency;
    return this;
  }

   /**
   * Creation currency of the CheckoutSession before localization
   * @return sourceCurrency
  **/
  public String getSourceCurrency() {
    return sourceCurrency;
  }

  public void setSourceCurrency(String sourceCurrency) {
    this.sourceCurrency = sourceCurrency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPagesCheckoutSessionCurrencyConversion paymentPagesCheckoutSessionCurrencyConversion = (PaymentPagesCheckoutSessionCurrencyConversion) o;
    return Objects.equals(this.amountSubtotal, paymentPagesCheckoutSessionCurrencyConversion.amountSubtotal) &&
        Objects.equals(this.amountTotal, paymentPagesCheckoutSessionCurrencyConversion.amountTotal) &&
        Objects.equals(this.fxRate, paymentPagesCheckoutSessionCurrencyConversion.fxRate) &&
        Objects.equals(this.sourceCurrency, paymentPagesCheckoutSessionCurrencyConversion.sourceCurrency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountSubtotal, amountTotal, fxRate, sourceCurrency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPagesCheckoutSessionCurrencyConversion {\n");
    
    sb.append("    amountSubtotal: ").append(toIndentedString(amountSubtotal)).append("\n");
    sb.append("    amountTotal: ").append(toIndentedString(amountTotal)).append("\n");
    sb.append("    fxRate: ").append(toIndentedString(fxRate)).append("\n");
    sb.append("    sourceCurrency: ").append(toIndentedString(sourceCurrency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
