/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethodOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodOptions {
  @JsonProperty("acss_debit")
  private AnyOfpaymentMethodOptionsAcssDebit acssDebit = null;

  @JsonProperty("bancontact")
  private AnyOfpaymentMethodOptionsBancontact bancontact = null;

  @JsonProperty("card")
  private AnyOfpaymentMethodOptionsCard card = null;

  @JsonProperty("customer_balance")
  private AnyOfpaymentMethodOptionsCustomerBalance customerBalance = null;

  @JsonProperty("konbini")
  private AnyOfpaymentMethodOptionsKonbini konbini = null;

  @JsonProperty("sepa_debit")
  private AnyOfpaymentMethodOptionsSepaDebit sepaDebit = null;

  @JsonProperty("us_bank_account")
  private AnyOfpaymentMethodOptionsUsBankAccount usBankAccount = null;

  public PaymentMethodOptions acssDebit(AnyOfpaymentMethodOptionsAcssDebit acssDebit) {
    this.acssDebit = acssDebit;
    return this;
  }

   /**
   * Get acssDebit
   * @return acssDebit
  **/
  public AnyOfpaymentMethodOptionsAcssDebit getAcssDebit() {
    return acssDebit;
  }

  public void setAcssDebit(AnyOfpaymentMethodOptionsAcssDebit acssDebit) {
    this.acssDebit = acssDebit;
  }

  public PaymentMethodOptions bancontact(AnyOfpaymentMethodOptionsBancontact bancontact) {
    this.bancontact = bancontact;
    return this;
  }

   /**
   * Get bancontact
   * @return bancontact
  **/
  public AnyOfpaymentMethodOptionsBancontact getBancontact() {
    return bancontact;
  }

  public void setBancontact(AnyOfpaymentMethodOptionsBancontact bancontact) {
    this.bancontact = bancontact;
  }

  public PaymentMethodOptions card(AnyOfpaymentMethodOptionsCard card) {
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  public AnyOfpaymentMethodOptionsCard getCard() {
    return card;
  }

  public void setCard(AnyOfpaymentMethodOptionsCard card) {
    this.card = card;
  }

  public PaymentMethodOptions customerBalance(AnyOfpaymentMethodOptionsCustomerBalance customerBalance) {
    this.customerBalance = customerBalance;
    return this;
  }

   /**
   * Get customerBalance
   * @return customerBalance
  **/
  public AnyOfpaymentMethodOptionsCustomerBalance getCustomerBalance() {
    return customerBalance;
  }

  public void setCustomerBalance(AnyOfpaymentMethodOptionsCustomerBalance customerBalance) {
    this.customerBalance = customerBalance;
  }

  public PaymentMethodOptions konbini(AnyOfpaymentMethodOptionsKonbini konbini) {
    this.konbini = konbini;
    return this;
  }

   /**
   * Get konbini
   * @return konbini
  **/
  public AnyOfpaymentMethodOptionsKonbini getKonbini() {
    return konbini;
  }

  public void setKonbini(AnyOfpaymentMethodOptionsKonbini konbini) {
    this.konbini = konbini;
  }

  public PaymentMethodOptions sepaDebit(AnyOfpaymentMethodOptionsSepaDebit sepaDebit) {
    this.sepaDebit = sepaDebit;
    return this;
  }

   /**
   * Get sepaDebit
   * @return sepaDebit
  **/
  public AnyOfpaymentMethodOptionsSepaDebit getSepaDebit() {
    return sepaDebit;
  }

  public void setSepaDebit(AnyOfpaymentMethodOptionsSepaDebit sepaDebit) {
    this.sepaDebit = sepaDebit;
  }

  public PaymentMethodOptions usBankAccount(AnyOfpaymentMethodOptionsUsBankAccount usBankAccount) {
    this.usBankAccount = usBankAccount;
    return this;
  }

   /**
   * Get usBankAccount
   * @return usBankAccount
  **/
  public AnyOfpaymentMethodOptionsUsBankAccount getUsBankAccount() {
    return usBankAccount;
  }

  public void setUsBankAccount(AnyOfpaymentMethodOptionsUsBankAccount usBankAccount) {
    this.usBankAccount = usBankAccount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodOptions paymentMethodOptions = (PaymentMethodOptions) o;
    return Objects.equals(this.acssDebit, paymentMethodOptions.acssDebit) &&
        Objects.equals(this.bancontact, paymentMethodOptions.bancontact) &&
        Objects.equals(this.card, paymentMethodOptions.card) &&
        Objects.equals(this.customerBalance, paymentMethodOptions.customerBalance) &&
        Objects.equals(this.konbini, paymentMethodOptions.konbini) &&
        Objects.equals(this.sepaDebit, paymentMethodOptions.sepaDebit) &&
        Objects.equals(this.usBankAccount, paymentMethodOptions.usBankAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acssDebit, bancontact, card, customerBalance, konbini, sepaDebit, usBankAccount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodOptions {\n");
    
    sb.append("    acssDebit: ").append(toIndentedString(acssDebit)).append("\n");
    sb.append("    bancontact: ").append(toIndentedString(bancontact)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    customerBalance: ").append(toIndentedString(customerBalance)).append("\n");
    sb.append("    konbini: ").append(toIndentedString(konbini)).append("\n");
    sb.append("    sepaDebit: ").append(toIndentedString(sepaDebit)).append("\n");
    sb.append("    usBankAccount: ").append(toIndentedString(usBankAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
