/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.PaymentMethodOptions1;

/**
 * Configuration settings for the PaymentIntent that is generated when the invoice is finalized.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentSettings1 {
  @JsonProperty("default_mandate")
  private AnyOfpaymentSettings1DefaultMandate defaultMandate = null;

  @JsonProperty("payment_method_options")
  private PaymentMethodOptions1 paymentMethodOptions = null;

  @JsonProperty("payment_method_types")
  private AnyOfpaymentSettings1PaymentMethodTypes paymentMethodTypes = null;

  public PaymentSettings1 defaultMandate(AnyOfpaymentSettings1DefaultMandate defaultMandate) {
    this.defaultMandate = defaultMandate;
    return this;
  }

   /**
   * Get defaultMandate
   * @return defaultMandate
  **/
  public AnyOfpaymentSettings1DefaultMandate getDefaultMandate() {
    return defaultMandate;
  }

  public void setDefaultMandate(AnyOfpaymentSettings1DefaultMandate defaultMandate) {
    this.defaultMandate = defaultMandate;
  }

  public PaymentSettings1 paymentMethodOptions(PaymentMethodOptions1 paymentMethodOptions) {
    this.paymentMethodOptions = paymentMethodOptions;
    return this;
  }

   /**
   * Get paymentMethodOptions
   * @return paymentMethodOptions
  **/
  public PaymentMethodOptions1 getPaymentMethodOptions() {
    return paymentMethodOptions;
  }

  public void setPaymentMethodOptions(PaymentMethodOptions1 paymentMethodOptions) {
    this.paymentMethodOptions = paymentMethodOptions;
  }

  public PaymentSettings1 paymentMethodTypes(AnyOfpaymentSettings1PaymentMethodTypes paymentMethodTypes) {
    this.paymentMethodTypes = paymentMethodTypes;
    return this;
  }

   /**
   * Get paymentMethodTypes
   * @return paymentMethodTypes
  **/
  public AnyOfpaymentSettings1PaymentMethodTypes getPaymentMethodTypes() {
    return paymentMethodTypes;
  }

  public void setPaymentMethodTypes(AnyOfpaymentSettings1PaymentMethodTypes paymentMethodTypes) {
    this.paymentMethodTypes = paymentMethodTypes;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentSettings1 paymentSettings1 = (PaymentSettings1) o;
    return Objects.equals(this.defaultMandate, paymentSettings1.defaultMandate) &&
        Objects.equals(this.paymentMethodOptions, paymentSettings1.paymentMethodOptions) &&
        Objects.equals(this.paymentMethodTypes, paymentSettings1.paymentMethodTypes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(defaultMandate, paymentMethodOptions, paymentMethodTypes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentSettings1 {\n");
    
    sb.append("    defaultMandate: ").append(toIndentedString(defaultMandate)).append("\n");
    sb.append("    paymentMethodOptions: ").append(toIndentedString(paymentMethodOptions)).append("\n");
    sb.append("    paymentMethodTypes: ").append(toIndentedString(paymentMethodTypes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
