/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.DisplayPreferenceParam;

/**
 * Revolut Pay, developed by Revolut, a global finance app, is a digital wallet payment method. Revolut Pay uses the customer’s stored balance or cards to fund the payment, and offers the option for non-Revolut customers to save their details after their first purchase.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodParam37 {
  @JsonProperty("display_preference")
  private DisplayPreferenceParam displayPreference = null;

  public PaymentMethodParam37 displayPreference(DisplayPreferenceParam displayPreference) {
    this.displayPreference = displayPreference;
    return this;
  }

   /**
   * Get displayPreference
   * @return displayPreference
  **/
  public DisplayPreferenceParam getDisplayPreference() {
    return displayPreference;
  }

  public void setDisplayPreference(DisplayPreferenceParam displayPreference) {
    this.displayPreference = displayPreference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodParam37 paymentMethodParam37 = (PaymentMethodParam37) o;
    return Objects.equals(this.displayPreference, paymentMethodParam37.displayPreference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayPreference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodParam37 {\n");
    
    sb.append("    displayPreference: ").append(toIndentedString(displayPreference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
