/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.PaymentLinksResourceCompletionBehaviorConfirmationPage;
import com.stripe.api.client.PaymentLinksResourceCompletionBehaviorRedirect;

/**
 * PaymentLinksResourceAfterCompletion
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentLinksResourceAfterCompletion {
  @JsonProperty("hosted_confirmation")
  private PaymentLinksResourceCompletionBehaviorConfirmationPage hostedConfirmation = null;

  @JsonProperty("redirect")
  private PaymentLinksResourceCompletionBehaviorRedirect redirect = null;

  /**
   * The specified behavior after the purchase is complete.
   */
  public enum TypeEnum {
    HOSTED_CONFIRMATION("hosted_confirmation"),
    REDIRECT("redirect");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public PaymentLinksResourceAfterCompletion hostedConfirmation(PaymentLinksResourceCompletionBehaviorConfirmationPage hostedConfirmation) {
    this.hostedConfirmation = hostedConfirmation;
    return this;
  }

   /**
   * Get hostedConfirmation
   * @return hostedConfirmation
  **/
  public PaymentLinksResourceCompletionBehaviorConfirmationPage getHostedConfirmation() {
    return hostedConfirmation;
  }

  public void setHostedConfirmation(PaymentLinksResourceCompletionBehaviorConfirmationPage hostedConfirmation) {
    this.hostedConfirmation = hostedConfirmation;
  }

  public PaymentLinksResourceAfterCompletion redirect(PaymentLinksResourceCompletionBehaviorRedirect redirect) {
    this.redirect = redirect;
    return this;
  }

   /**
   * Get redirect
   * @return redirect
  **/
  public PaymentLinksResourceCompletionBehaviorRedirect getRedirect() {
    return redirect;
  }

  public void setRedirect(PaymentLinksResourceCompletionBehaviorRedirect redirect) {
    this.redirect = redirect;
  }

  public PaymentLinksResourceAfterCompletion type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The specified behavior after the purchase is complete.
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentLinksResourceAfterCompletion paymentLinksResourceAfterCompletion = (PaymentLinksResourceAfterCompletion) o;
    return Objects.equals(this.hostedConfirmation, paymentLinksResourceAfterCompletion.hostedConfirmation) &&
        Objects.equals(this.redirect, paymentLinksResourceAfterCompletion.redirect) &&
        Objects.equals(this.type, paymentLinksResourceAfterCompletion.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostedConfirmation, redirect, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentLinksResourceAfterCompletion {\n");
    
    sb.append("    hostedConfirmation: ").append(toIndentedString(hostedConfirmation)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
