/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentMethodOptionsParam12
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodOptionsParam12 {
  /**
   * Gets or Sets captureMethod
   */
  public enum CaptureMethodEnum {
    EMPTY(""),
    MANUAL("manual");

    private String value;

    CaptureMethodEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CaptureMethodEnum fromValue(String input) {
      for (CaptureMethodEnum b : CaptureMethodEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("capture_method")
  private CaptureMethodEnum captureMethod = null;

  /**
   * Gets or Sets preferredLocale
   */
  public enum PreferredLocaleEnum {
    CS_CZ("cs-CZ"),
    DA_DK("da-DK"),
    DE_AT("de-AT"),
    DE_DE("de-DE"),
    DE_LU("de-LU"),
    EL_GR("el-GR"),
    EN_GB("en-GB"),
    EN_US("en-US"),
    ES_ES("es-ES"),
    FI_FI("fi-FI"),
    FR_BE("fr-BE"),
    FR_FR("fr-FR"),
    FR_LU("fr-LU"),
    HU_HU("hu-HU"),
    IT_IT("it-IT"),
    NL_BE("nl-BE"),
    NL_NL("nl-NL"),
    PL_PL("pl-PL"),
    PT_PT("pt-PT"),
    SK_SK("sk-SK"),
    SV_SE("sv-SE");

    private String value;

    PreferredLocaleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PreferredLocaleEnum fromValue(String input) {
      for (PreferredLocaleEnum b : PreferredLocaleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("preferred_locale")
  private PreferredLocaleEnum preferredLocale = null;

  @JsonProperty("reference")
  private String reference = null;

  @JsonProperty("risk_correlation_id")
  private String riskCorrelationId = null;

  /**
   * Gets or Sets setupFutureUsage
   */
  public enum SetupFutureUsageEnum {
    EMPTY(""),
    NONE("none"),
    OFF_SESSION("off_session");

    private String value;

    SetupFutureUsageEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static SetupFutureUsageEnum fromValue(String input) {
      for (SetupFutureUsageEnum b : SetupFutureUsageEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("setup_future_usage")
  private SetupFutureUsageEnum setupFutureUsage = null;

  public PaymentMethodOptionsParam12 captureMethod(CaptureMethodEnum captureMethod) {
    this.captureMethod = captureMethod;
    return this;
  }

   /**
   * Get captureMethod
   * @return captureMethod
  **/
  public CaptureMethodEnum getCaptureMethod() {
    return captureMethod;
  }

  public void setCaptureMethod(CaptureMethodEnum captureMethod) {
    this.captureMethod = captureMethod;
  }

  public PaymentMethodOptionsParam12 preferredLocale(PreferredLocaleEnum preferredLocale) {
    this.preferredLocale = preferredLocale;
    return this;
  }

   /**
   * Get preferredLocale
   * @return preferredLocale
  **/
  public PreferredLocaleEnum getPreferredLocale() {
    return preferredLocale;
  }

  public void setPreferredLocale(PreferredLocaleEnum preferredLocale) {
    this.preferredLocale = preferredLocale;
  }

  public PaymentMethodOptionsParam12 reference(String reference) {
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  public String getReference() {
    return reference;
  }

  public void setReference(String reference) {
    this.reference = reference;
  }

  public PaymentMethodOptionsParam12 riskCorrelationId(String riskCorrelationId) {
    this.riskCorrelationId = riskCorrelationId;
    return this;
  }

   /**
   * Get riskCorrelationId
   * @return riskCorrelationId
  **/
  public String getRiskCorrelationId() {
    return riskCorrelationId;
  }

  public void setRiskCorrelationId(String riskCorrelationId) {
    this.riskCorrelationId = riskCorrelationId;
  }

  public PaymentMethodOptionsParam12 setupFutureUsage(SetupFutureUsageEnum setupFutureUsage) {
    this.setupFutureUsage = setupFutureUsage;
    return this;
  }

   /**
   * Get setupFutureUsage
   * @return setupFutureUsage
  **/
  public SetupFutureUsageEnum getSetupFutureUsage() {
    return setupFutureUsage;
  }

  public void setSetupFutureUsage(SetupFutureUsageEnum setupFutureUsage) {
    this.setupFutureUsage = setupFutureUsage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodOptionsParam12 paymentMethodOptionsParam12 = (PaymentMethodOptionsParam12) o;
    return Objects.equals(this.captureMethod, paymentMethodOptionsParam12.captureMethod) &&
        Objects.equals(this.preferredLocale, paymentMethodOptionsParam12.preferredLocale) &&
        Objects.equals(this.reference, paymentMethodOptionsParam12.reference) &&
        Objects.equals(this.riskCorrelationId, paymentMethodOptionsParam12.riskCorrelationId) &&
        Objects.equals(this.setupFutureUsage, paymentMethodOptionsParam12.setupFutureUsage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(captureMethod, preferredLocale, reference, riskCorrelationId, setupFutureUsage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodOptionsParam12 {\n");
    
    sb.append("    captureMethod: ").append(toIndentedString(captureMethod)).append("\n");
    sb.append("    preferredLocale: ").append(toIndentedString(preferredLocale)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    riskCorrelationId: ").append(toIndentedString(riskCorrelationId)).append("\n");
    sb.append("    setupFutureUsage: ").append(toIndentedString(setupFutureUsage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
