/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit {
  @JsonProperty("custom_mandate_url")
  private String customMandateUrl = null;

  @JsonProperty("interval_description")
  private String intervalDescription = null;

  /**
   * Payment schedule for the mandate.
   */
  public enum PaymentScheduleEnum {
    COMBINED("combined"),
    INTERVAL("interval"),
    SPORADIC("sporadic");

    private String value;

    PaymentScheduleEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PaymentScheduleEnum fromValue(String input) {
      for (PaymentScheduleEnum b : PaymentScheduleEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("payment_schedule")
  private PaymentScheduleEnum paymentSchedule = null;

  /**
   * Transaction type of the mandate.
   */
  public enum TransactionTypeEnum {
    BUSINESS("business"),
    PERSONAL("personal");

    private String value;

    TransactionTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TransactionTypeEnum fromValue(String input) {
      for (TransactionTypeEnum b : TransactionTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("transaction_type")
  private TransactionTypeEnum transactionType = null;

  public PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit customMandateUrl(String customMandateUrl) {
    this.customMandateUrl = customMandateUrl;
    return this;
  }

   /**
   * A URL for custom mandate text
   * @return customMandateUrl
  **/
  public String getCustomMandateUrl() {
    return customMandateUrl;
  }

  public void setCustomMandateUrl(String customMandateUrl) {
    this.customMandateUrl = customMandateUrl;
  }

  public PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit intervalDescription(String intervalDescription) {
    this.intervalDescription = intervalDescription;
    return this;
  }

   /**
   * Description of the interval. Only required if the &#x27;payment_schedule&#x27; parameter is &#x27;interval&#x27; or &#x27;combined&#x27;.
   * @return intervalDescription
  **/
  public String getIntervalDescription() {
    return intervalDescription;
  }

  public void setIntervalDescription(String intervalDescription) {
    this.intervalDescription = intervalDescription;
  }

  public PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit paymentSchedule(PaymentScheduleEnum paymentSchedule) {
    this.paymentSchedule = paymentSchedule;
    return this;
  }

   /**
   * Payment schedule for the mandate.
   * @return paymentSchedule
  **/
  public PaymentScheduleEnum getPaymentSchedule() {
    return paymentSchedule;
  }

  public void setPaymentSchedule(PaymentScheduleEnum paymentSchedule) {
    this.paymentSchedule = paymentSchedule;
  }

  public PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit transactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Transaction type of the mandate.
   * @return transactionType
  **/
  public TransactionTypeEnum getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(TransactionTypeEnum transactionType) {
    this.transactionType = transactionType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit paymentIntentPaymentMethodOptionsMandateOptionsAcssDebit = (PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit) o;
    return Objects.equals(this.customMandateUrl, paymentIntentPaymentMethodOptionsMandateOptionsAcssDebit.customMandateUrl) &&
        Objects.equals(this.intervalDescription, paymentIntentPaymentMethodOptionsMandateOptionsAcssDebit.intervalDescription) &&
        Objects.equals(this.paymentSchedule, paymentIntentPaymentMethodOptionsMandateOptionsAcssDebit.paymentSchedule) &&
        Objects.equals(this.transactionType, paymentIntentPaymentMethodOptionsMandateOptionsAcssDebit.transactionType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(customMandateUrl, intervalDescription, paymentSchedule, transactionType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentIntentPaymentMethodOptionsMandateOptionsAcssDebit {\n");
    
    sb.append("    customMandateUrl: ").append(toIndentedString(customMandateUrl)).append("\n");
    sb.append("    intervalDescription: ").append(toIndentedString(intervalDescription)).append("\n");
    sb.append("    paymentSchedule: ").append(toIndentedString(paymentSchedule)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
