/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentIntentPaymentMethodOptions
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentIntentPaymentMethodOptions implements AnyOfpaymentIntentPaymentMethodOptions {
  @JsonProperty("acss_debit")
  private AnyOfpaymentIntentPaymentMethodOptionsAcssDebit acssDebit = null;

  @JsonProperty("affirm")
  private AnyOfpaymentIntentPaymentMethodOptionsAffirm affirm = null;

  @JsonProperty("afterpay_clearpay")
  private AnyOfpaymentIntentPaymentMethodOptionsAfterpayClearpay afterpayClearpay = null;

  @JsonProperty("alipay")
  private AnyOfpaymentIntentPaymentMethodOptionsAlipay alipay = null;

  @JsonProperty("alma")
  private AnyOfpaymentIntentPaymentMethodOptionsAlma alma = null;

  @JsonProperty("amazon_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsAmazonPay amazonPay = null;

  @JsonProperty("au_becs_debit")
  private AnyOfpaymentIntentPaymentMethodOptionsAuBecsDebit auBecsDebit = null;

  @JsonProperty("bacs_debit")
  private AnyOfpaymentIntentPaymentMethodOptionsBacsDebit bacsDebit = null;

  @JsonProperty("bancontact")
  private AnyOfpaymentIntentPaymentMethodOptionsBancontact bancontact = null;

  @JsonProperty("blik")
  private AnyOfpaymentIntentPaymentMethodOptionsBlik blik = null;

  @JsonProperty("boleto")
  private AnyOfpaymentIntentPaymentMethodOptionsBoleto boleto = null;

  @JsonProperty("card")
  private AnyOfpaymentIntentPaymentMethodOptionsCard card = null;

  @JsonProperty("card_present")
  private AnyOfpaymentIntentPaymentMethodOptionsCardPresent cardPresent = null;

  @JsonProperty("cashapp")
  private AnyOfpaymentIntentPaymentMethodOptionsCashapp cashapp = null;

  @JsonProperty("customer_balance")
  private AnyOfpaymentIntentPaymentMethodOptionsCustomerBalance customerBalance = null;

  @JsonProperty("eps")
  private AnyOfpaymentIntentPaymentMethodOptionsEps eps = null;

  @JsonProperty("fpx")
  private AnyOfpaymentIntentPaymentMethodOptionsFpx fpx = null;

  @JsonProperty("giropay")
  private AnyOfpaymentIntentPaymentMethodOptionsGiropay giropay = null;

  @JsonProperty("grabpay")
  private AnyOfpaymentIntentPaymentMethodOptionsGrabpay grabpay = null;

  @JsonProperty("ideal")
  private AnyOfpaymentIntentPaymentMethodOptionsIdeal ideal = null;

  @JsonProperty("interac_present")
  private AnyOfpaymentIntentPaymentMethodOptionsInteracPresent interacPresent = null;

  @JsonProperty("kakao_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsKakaoPay kakaoPay = null;

  @JsonProperty("klarna")
  private AnyOfpaymentIntentPaymentMethodOptionsKlarna klarna = null;

  @JsonProperty("konbini")
  private AnyOfpaymentIntentPaymentMethodOptionsKonbini konbini = null;

  @JsonProperty("kr_card")
  private AnyOfpaymentIntentPaymentMethodOptionsKrCard krCard = null;

  @JsonProperty("link")
  private AnyOfpaymentIntentPaymentMethodOptionsLink link = null;

  @JsonProperty("mobilepay")
  private AnyOfpaymentIntentPaymentMethodOptionsMobilepay mobilepay = null;

  @JsonProperty("multibanco")
  private AnyOfpaymentIntentPaymentMethodOptionsMultibanco multibanco = null;

  @JsonProperty("naver_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsNaverPay naverPay = null;

  @JsonProperty("oxxo")
  private AnyOfpaymentIntentPaymentMethodOptionsOxxo oxxo = null;

  @JsonProperty("p24")
  private AnyOfpaymentIntentPaymentMethodOptionsP24 p24 = null;

  @JsonProperty("pay_by_bank")
  private AnyOfpaymentIntentPaymentMethodOptionsPayByBank payByBank = null;

  @JsonProperty("payco")
  private AnyOfpaymentIntentPaymentMethodOptionsPayco payco = null;

  @JsonProperty("paynow")
  private AnyOfpaymentIntentPaymentMethodOptionsPaynow paynow = null;

  @JsonProperty("paypal")
  private AnyOfpaymentIntentPaymentMethodOptionsPaypal paypal = null;

  @JsonProperty("pix")
  private AnyOfpaymentIntentPaymentMethodOptionsPix pix = null;

  @JsonProperty("promptpay")
  private AnyOfpaymentIntentPaymentMethodOptionsPromptpay promptpay = null;

  @JsonProperty("revolut_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsRevolutPay revolutPay = null;

  @JsonProperty("samsung_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsSamsungPay samsungPay = null;

  @JsonProperty("sepa_debit")
  private AnyOfpaymentIntentPaymentMethodOptionsSepaDebit sepaDebit = null;

  @JsonProperty("sofort")
  private AnyOfpaymentIntentPaymentMethodOptionsSofort sofort = null;

  @JsonProperty("swish")
  private AnyOfpaymentIntentPaymentMethodOptionsSwish swish = null;

  @JsonProperty("twint")
  private AnyOfpaymentIntentPaymentMethodOptionsTwint twint = null;

  @JsonProperty("us_bank_account")
  private AnyOfpaymentIntentPaymentMethodOptionsUsBankAccount usBankAccount = null;

  @JsonProperty("wechat_pay")
  private AnyOfpaymentIntentPaymentMethodOptionsWechatPay wechatPay = null;

  @JsonProperty("zip")
  private AnyOfpaymentIntentPaymentMethodOptionsZip zip = null;

  public PaymentIntentPaymentMethodOptions acssDebit(AnyOfpaymentIntentPaymentMethodOptionsAcssDebit acssDebit) {
    this.acssDebit = acssDebit;
    return this;
  }

   /**
   * Get acssDebit
   * @return acssDebit
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAcssDebit getAcssDebit() {
    return acssDebit;
  }

  public void setAcssDebit(AnyOfpaymentIntentPaymentMethodOptionsAcssDebit acssDebit) {
    this.acssDebit = acssDebit;
  }

  public PaymentIntentPaymentMethodOptions affirm(AnyOfpaymentIntentPaymentMethodOptionsAffirm affirm) {
    this.affirm = affirm;
    return this;
  }

   /**
   * Get affirm
   * @return affirm
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAffirm getAffirm() {
    return affirm;
  }

  public void setAffirm(AnyOfpaymentIntentPaymentMethodOptionsAffirm affirm) {
    this.affirm = affirm;
  }

  public PaymentIntentPaymentMethodOptions afterpayClearpay(AnyOfpaymentIntentPaymentMethodOptionsAfterpayClearpay afterpayClearpay) {
    this.afterpayClearpay = afterpayClearpay;
    return this;
  }

   /**
   * Get afterpayClearpay
   * @return afterpayClearpay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAfterpayClearpay getAfterpayClearpay() {
    return afterpayClearpay;
  }

  public void setAfterpayClearpay(AnyOfpaymentIntentPaymentMethodOptionsAfterpayClearpay afterpayClearpay) {
    this.afterpayClearpay = afterpayClearpay;
  }

  public PaymentIntentPaymentMethodOptions alipay(AnyOfpaymentIntentPaymentMethodOptionsAlipay alipay) {
    this.alipay = alipay;
    return this;
  }

   /**
   * Get alipay
   * @return alipay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAlipay getAlipay() {
    return alipay;
  }

  public void setAlipay(AnyOfpaymentIntentPaymentMethodOptionsAlipay alipay) {
    this.alipay = alipay;
  }

  public PaymentIntentPaymentMethodOptions alma(AnyOfpaymentIntentPaymentMethodOptionsAlma alma) {
    this.alma = alma;
    return this;
  }

   /**
   * Get alma
   * @return alma
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAlma getAlma() {
    return alma;
  }

  public void setAlma(AnyOfpaymentIntentPaymentMethodOptionsAlma alma) {
    this.alma = alma;
  }

  public PaymentIntentPaymentMethodOptions amazonPay(AnyOfpaymentIntentPaymentMethodOptionsAmazonPay amazonPay) {
    this.amazonPay = amazonPay;
    return this;
  }

   /**
   * Get amazonPay
   * @return amazonPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAmazonPay getAmazonPay() {
    return amazonPay;
  }

  public void setAmazonPay(AnyOfpaymentIntentPaymentMethodOptionsAmazonPay amazonPay) {
    this.amazonPay = amazonPay;
  }

  public PaymentIntentPaymentMethodOptions auBecsDebit(AnyOfpaymentIntentPaymentMethodOptionsAuBecsDebit auBecsDebit) {
    this.auBecsDebit = auBecsDebit;
    return this;
  }

   /**
   * Get auBecsDebit
   * @return auBecsDebit
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsAuBecsDebit getAuBecsDebit() {
    return auBecsDebit;
  }

  public void setAuBecsDebit(AnyOfpaymentIntentPaymentMethodOptionsAuBecsDebit auBecsDebit) {
    this.auBecsDebit = auBecsDebit;
  }

  public PaymentIntentPaymentMethodOptions bacsDebit(AnyOfpaymentIntentPaymentMethodOptionsBacsDebit bacsDebit) {
    this.bacsDebit = bacsDebit;
    return this;
  }

   /**
   * Get bacsDebit
   * @return bacsDebit
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsBacsDebit getBacsDebit() {
    return bacsDebit;
  }

  public void setBacsDebit(AnyOfpaymentIntentPaymentMethodOptionsBacsDebit bacsDebit) {
    this.bacsDebit = bacsDebit;
  }

  public PaymentIntentPaymentMethodOptions bancontact(AnyOfpaymentIntentPaymentMethodOptionsBancontact bancontact) {
    this.bancontact = bancontact;
    return this;
  }

   /**
   * Get bancontact
   * @return bancontact
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsBancontact getBancontact() {
    return bancontact;
  }

  public void setBancontact(AnyOfpaymentIntentPaymentMethodOptionsBancontact bancontact) {
    this.bancontact = bancontact;
  }

  public PaymentIntentPaymentMethodOptions blik(AnyOfpaymentIntentPaymentMethodOptionsBlik blik) {
    this.blik = blik;
    return this;
  }

   /**
   * Get blik
   * @return blik
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsBlik getBlik() {
    return blik;
  }

  public void setBlik(AnyOfpaymentIntentPaymentMethodOptionsBlik blik) {
    this.blik = blik;
  }

  public PaymentIntentPaymentMethodOptions boleto(AnyOfpaymentIntentPaymentMethodOptionsBoleto boleto) {
    this.boleto = boleto;
    return this;
  }

   /**
   * Get boleto
   * @return boleto
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsBoleto getBoleto() {
    return boleto;
  }

  public void setBoleto(AnyOfpaymentIntentPaymentMethodOptionsBoleto boleto) {
    this.boleto = boleto;
  }

  public PaymentIntentPaymentMethodOptions card(AnyOfpaymentIntentPaymentMethodOptionsCard card) {
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsCard getCard() {
    return card;
  }

  public void setCard(AnyOfpaymentIntentPaymentMethodOptionsCard card) {
    this.card = card;
  }

  public PaymentIntentPaymentMethodOptions cardPresent(AnyOfpaymentIntentPaymentMethodOptionsCardPresent cardPresent) {
    this.cardPresent = cardPresent;
    return this;
  }

   /**
   * Get cardPresent
   * @return cardPresent
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsCardPresent getCardPresent() {
    return cardPresent;
  }

  public void setCardPresent(AnyOfpaymentIntentPaymentMethodOptionsCardPresent cardPresent) {
    this.cardPresent = cardPresent;
  }

  public PaymentIntentPaymentMethodOptions cashapp(AnyOfpaymentIntentPaymentMethodOptionsCashapp cashapp) {
    this.cashapp = cashapp;
    return this;
  }

   /**
   * Get cashapp
   * @return cashapp
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsCashapp getCashapp() {
    return cashapp;
  }

  public void setCashapp(AnyOfpaymentIntentPaymentMethodOptionsCashapp cashapp) {
    this.cashapp = cashapp;
  }

  public PaymentIntentPaymentMethodOptions customerBalance(AnyOfpaymentIntentPaymentMethodOptionsCustomerBalance customerBalance) {
    this.customerBalance = customerBalance;
    return this;
  }

   /**
   * Get customerBalance
   * @return customerBalance
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsCustomerBalance getCustomerBalance() {
    return customerBalance;
  }

  public void setCustomerBalance(AnyOfpaymentIntentPaymentMethodOptionsCustomerBalance customerBalance) {
    this.customerBalance = customerBalance;
  }

  public PaymentIntentPaymentMethodOptions eps(AnyOfpaymentIntentPaymentMethodOptionsEps eps) {
    this.eps = eps;
    return this;
  }

   /**
   * Get eps
   * @return eps
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsEps getEps() {
    return eps;
  }

  public void setEps(AnyOfpaymentIntentPaymentMethodOptionsEps eps) {
    this.eps = eps;
  }

  public PaymentIntentPaymentMethodOptions fpx(AnyOfpaymentIntentPaymentMethodOptionsFpx fpx) {
    this.fpx = fpx;
    return this;
  }

   /**
   * Get fpx
   * @return fpx
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsFpx getFpx() {
    return fpx;
  }

  public void setFpx(AnyOfpaymentIntentPaymentMethodOptionsFpx fpx) {
    this.fpx = fpx;
  }

  public PaymentIntentPaymentMethodOptions giropay(AnyOfpaymentIntentPaymentMethodOptionsGiropay giropay) {
    this.giropay = giropay;
    return this;
  }

   /**
   * Get giropay
   * @return giropay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsGiropay getGiropay() {
    return giropay;
  }

  public void setGiropay(AnyOfpaymentIntentPaymentMethodOptionsGiropay giropay) {
    this.giropay = giropay;
  }

  public PaymentIntentPaymentMethodOptions grabpay(AnyOfpaymentIntentPaymentMethodOptionsGrabpay grabpay) {
    this.grabpay = grabpay;
    return this;
  }

   /**
   * Get grabpay
   * @return grabpay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsGrabpay getGrabpay() {
    return grabpay;
  }

  public void setGrabpay(AnyOfpaymentIntentPaymentMethodOptionsGrabpay grabpay) {
    this.grabpay = grabpay;
  }

  public PaymentIntentPaymentMethodOptions ideal(AnyOfpaymentIntentPaymentMethodOptionsIdeal ideal) {
    this.ideal = ideal;
    return this;
  }

   /**
   * Get ideal
   * @return ideal
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsIdeal getIdeal() {
    return ideal;
  }

  public void setIdeal(AnyOfpaymentIntentPaymentMethodOptionsIdeal ideal) {
    this.ideal = ideal;
  }

  public PaymentIntentPaymentMethodOptions interacPresent(AnyOfpaymentIntentPaymentMethodOptionsInteracPresent interacPresent) {
    this.interacPresent = interacPresent;
    return this;
  }

   /**
   * Get interacPresent
   * @return interacPresent
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsInteracPresent getInteracPresent() {
    return interacPresent;
  }

  public void setInteracPresent(AnyOfpaymentIntentPaymentMethodOptionsInteracPresent interacPresent) {
    this.interacPresent = interacPresent;
  }

  public PaymentIntentPaymentMethodOptions kakaoPay(AnyOfpaymentIntentPaymentMethodOptionsKakaoPay kakaoPay) {
    this.kakaoPay = kakaoPay;
    return this;
  }

   /**
   * Get kakaoPay
   * @return kakaoPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsKakaoPay getKakaoPay() {
    return kakaoPay;
  }

  public void setKakaoPay(AnyOfpaymentIntentPaymentMethodOptionsKakaoPay kakaoPay) {
    this.kakaoPay = kakaoPay;
  }

  public PaymentIntentPaymentMethodOptions klarna(AnyOfpaymentIntentPaymentMethodOptionsKlarna klarna) {
    this.klarna = klarna;
    return this;
  }

   /**
   * Get klarna
   * @return klarna
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsKlarna getKlarna() {
    return klarna;
  }

  public void setKlarna(AnyOfpaymentIntentPaymentMethodOptionsKlarna klarna) {
    this.klarna = klarna;
  }

  public PaymentIntentPaymentMethodOptions konbini(AnyOfpaymentIntentPaymentMethodOptionsKonbini konbini) {
    this.konbini = konbini;
    return this;
  }

   /**
   * Get konbini
   * @return konbini
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsKonbini getKonbini() {
    return konbini;
  }

  public void setKonbini(AnyOfpaymentIntentPaymentMethodOptionsKonbini konbini) {
    this.konbini = konbini;
  }

  public PaymentIntentPaymentMethodOptions krCard(AnyOfpaymentIntentPaymentMethodOptionsKrCard krCard) {
    this.krCard = krCard;
    return this;
  }

   /**
   * Get krCard
   * @return krCard
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsKrCard getKrCard() {
    return krCard;
  }

  public void setKrCard(AnyOfpaymentIntentPaymentMethodOptionsKrCard krCard) {
    this.krCard = krCard;
  }

  public PaymentIntentPaymentMethodOptions link(AnyOfpaymentIntentPaymentMethodOptionsLink link) {
    this.link = link;
    return this;
  }

   /**
   * Get link
   * @return link
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsLink getLink() {
    return link;
  }

  public void setLink(AnyOfpaymentIntentPaymentMethodOptionsLink link) {
    this.link = link;
  }

  public PaymentIntentPaymentMethodOptions mobilepay(AnyOfpaymentIntentPaymentMethodOptionsMobilepay mobilepay) {
    this.mobilepay = mobilepay;
    return this;
  }

   /**
   * Get mobilepay
   * @return mobilepay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsMobilepay getMobilepay() {
    return mobilepay;
  }

  public void setMobilepay(AnyOfpaymentIntentPaymentMethodOptionsMobilepay mobilepay) {
    this.mobilepay = mobilepay;
  }

  public PaymentIntentPaymentMethodOptions multibanco(AnyOfpaymentIntentPaymentMethodOptionsMultibanco multibanco) {
    this.multibanco = multibanco;
    return this;
  }

   /**
   * Get multibanco
   * @return multibanco
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsMultibanco getMultibanco() {
    return multibanco;
  }

  public void setMultibanco(AnyOfpaymentIntentPaymentMethodOptionsMultibanco multibanco) {
    this.multibanco = multibanco;
  }

  public PaymentIntentPaymentMethodOptions naverPay(AnyOfpaymentIntentPaymentMethodOptionsNaverPay naverPay) {
    this.naverPay = naverPay;
    return this;
  }

   /**
   * Get naverPay
   * @return naverPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsNaverPay getNaverPay() {
    return naverPay;
  }

  public void setNaverPay(AnyOfpaymentIntentPaymentMethodOptionsNaverPay naverPay) {
    this.naverPay = naverPay;
  }

  public PaymentIntentPaymentMethodOptions oxxo(AnyOfpaymentIntentPaymentMethodOptionsOxxo oxxo) {
    this.oxxo = oxxo;
    return this;
  }

   /**
   * Get oxxo
   * @return oxxo
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsOxxo getOxxo() {
    return oxxo;
  }

  public void setOxxo(AnyOfpaymentIntentPaymentMethodOptionsOxxo oxxo) {
    this.oxxo = oxxo;
  }

  public PaymentIntentPaymentMethodOptions p24(AnyOfpaymentIntentPaymentMethodOptionsP24 p24) {
    this.p24 = p24;
    return this;
  }

   /**
   * Get p24
   * @return p24
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsP24 getP24() {
    return p24;
  }

  public void setP24(AnyOfpaymentIntentPaymentMethodOptionsP24 p24) {
    this.p24 = p24;
  }

  public PaymentIntentPaymentMethodOptions payByBank(AnyOfpaymentIntentPaymentMethodOptionsPayByBank payByBank) {
    this.payByBank = payByBank;
    return this;
  }

   /**
   * Get payByBank
   * @return payByBank
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPayByBank getPayByBank() {
    return payByBank;
  }

  public void setPayByBank(AnyOfpaymentIntentPaymentMethodOptionsPayByBank payByBank) {
    this.payByBank = payByBank;
  }

  public PaymentIntentPaymentMethodOptions payco(AnyOfpaymentIntentPaymentMethodOptionsPayco payco) {
    this.payco = payco;
    return this;
  }

   /**
   * Get payco
   * @return payco
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPayco getPayco() {
    return payco;
  }

  public void setPayco(AnyOfpaymentIntentPaymentMethodOptionsPayco payco) {
    this.payco = payco;
  }

  public PaymentIntentPaymentMethodOptions paynow(AnyOfpaymentIntentPaymentMethodOptionsPaynow paynow) {
    this.paynow = paynow;
    return this;
  }

   /**
   * Get paynow
   * @return paynow
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPaynow getPaynow() {
    return paynow;
  }

  public void setPaynow(AnyOfpaymentIntentPaymentMethodOptionsPaynow paynow) {
    this.paynow = paynow;
  }

  public PaymentIntentPaymentMethodOptions paypal(AnyOfpaymentIntentPaymentMethodOptionsPaypal paypal) {
    this.paypal = paypal;
    return this;
  }

   /**
   * Get paypal
   * @return paypal
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPaypal getPaypal() {
    return paypal;
  }

  public void setPaypal(AnyOfpaymentIntentPaymentMethodOptionsPaypal paypal) {
    this.paypal = paypal;
  }

  public PaymentIntentPaymentMethodOptions pix(AnyOfpaymentIntentPaymentMethodOptionsPix pix) {
    this.pix = pix;
    return this;
  }

   /**
   * Get pix
   * @return pix
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPix getPix() {
    return pix;
  }

  public void setPix(AnyOfpaymentIntentPaymentMethodOptionsPix pix) {
    this.pix = pix;
  }

  public PaymentIntentPaymentMethodOptions promptpay(AnyOfpaymentIntentPaymentMethodOptionsPromptpay promptpay) {
    this.promptpay = promptpay;
    return this;
  }

   /**
   * Get promptpay
   * @return promptpay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsPromptpay getPromptpay() {
    return promptpay;
  }

  public void setPromptpay(AnyOfpaymentIntentPaymentMethodOptionsPromptpay promptpay) {
    this.promptpay = promptpay;
  }

  public PaymentIntentPaymentMethodOptions revolutPay(AnyOfpaymentIntentPaymentMethodOptionsRevolutPay revolutPay) {
    this.revolutPay = revolutPay;
    return this;
  }

   /**
   * Get revolutPay
   * @return revolutPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsRevolutPay getRevolutPay() {
    return revolutPay;
  }

  public void setRevolutPay(AnyOfpaymentIntentPaymentMethodOptionsRevolutPay revolutPay) {
    this.revolutPay = revolutPay;
  }

  public PaymentIntentPaymentMethodOptions samsungPay(AnyOfpaymentIntentPaymentMethodOptionsSamsungPay samsungPay) {
    this.samsungPay = samsungPay;
    return this;
  }

   /**
   * Get samsungPay
   * @return samsungPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsSamsungPay getSamsungPay() {
    return samsungPay;
  }

  public void setSamsungPay(AnyOfpaymentIntentPaymentMethodOptionsSamsungPay samsungPay) {
    this.samsungPay = samsungPay;
  }

  public PaymentIntentPaymentMethodOptions sepaDebit(AnyOfpaymentIntentPaymentMethodOptionsSepaDebit sepaDebit) {
    this.sepaDebit = sepaDebit;
    return this;
  }

   /**
   * Get sepaDebit
   * @return sepaDebit
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsSepaDebit getSepaDebit() {
    return sepaDebit;
  }

  public void setSepaDebit(AnyOfpaymentIntentPaymentMethodOptionsSepaDebit sepaDebit) {
    this.sepaDebit = sepaDebit;
  }

  public PaymentIntentPaymentMethodOptions sofort(AnyOfpaymentIntentPaymentMethodOptionsSofort sofort) {
    this.sofort = sofort;
    return this;
  }

   /**
   * Get sofort
   * @return sofort
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsSofort getSofort() {
    return sofort;
  }

  public void setSofort(AnyOfpaymentIntentPaymentMethodOptionsSofort sofort) {
    this.sofort = sofort;
  }

  public PaymentIntentPaymentMethodOptions swish(AnyOfpaymentIntentPaymentMethodOptionsSwish swish) {
    this.swish = swish;
    return this;
  }

   /**
   * Get swish
   * @return swish
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsSwish getSwish() {
    return swish;
  }

  public void setSwish(AnyOfpaymentIntentPaymentMethodOptionsSwish swish) {
    this.swish = swish;
  }

  public PaymentIntentPaymentMethodOptions twint(AnyOfpaymentIntentPaymentMethodOptionsTwint twint) {
    this.twint = twint;
    return this;
  }

   /**
   * Get twint
   * @return twint
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsTwint getTwint() {
    return twint;
  }

  public void setTwint(AnyOfpaymentIntentPaymentMethodOptionsTwint twint) {
    this.twint = twint;
  }

  public PaymentIntentPaymentMethodOptions usBankAccount(AnyOfpaymentIntentPaymentMethodOptionsUsBankAccount usBankAccount) {
    this.usBankAccount = usBankAccount;
    return this;
  }

   /**
   * Get usBankAccount
   * @return usBankAccount
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsUsBankAccount getUsBankAccount() {
    return usBankAccount;
  }

  public void setUsBankAccount(AnyOfpaymentIntentPaymentMethodOptionsUsBankAccount usBankAccount) {
    this.usBankAccount = usBankAccount;
  }

  public PaymentIntentPaymentMethodOptions wechatPay(AnyOfpaymentIntentPaymentMethodOptionsWechatPay wechatPay) {
    this.wechatPay = wechatPay;
    return this;
  }

   /**
   * Get wechatPay
   * @return wechatPay
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsWechatPay getWechatPay() {
    return wechatPay;
  }

  public void setWechatPay(AnyOfpaymentIntentPaymentMethodOptionsWechatPay wechatPay) {
    this.wechatPay = wechatPay;
  }

  public PaymentIntentPaymentMethodOptions zip(AnyOfpaymentIntentPaymentMethodOptionsZip zip) {
    this.zip = zip;
    return this;
  }

   /**
   * Get zip
   * @return zip
  **/
  public AnyOfpaymentIntentPaymentMethodOptionsZip getZip() {
    return zip;
  }

  public void setZip(AnyOfpaymentIntentPaymentMethodOptionsZip zip) {
    this.zip = zip;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentIntentPaymentMethodOptions paymentIntentPaymentMethodOptions = (PaymentIntentPaymentMethodOptions) o;
    return Objects.equals(this.acssDebit, paymentIntentPaymentMethodOptions.acssDebit) &&
        Objects.equals(this.affirm, paymentIntentPaymentMethodOptions.affirm) &&
        Objects.equals(this.afterpayClearpay, paymentIntentPaymentMethodOptions.afterpayClearpay) &&
        Objects.equals(this.alipay, paymentIntentPaymentMethodOptions.alipay) &&
        Objects.equals(this.alma, paymentIntentPaymentMethodOptions.alma) &&
        Objects.equals(this.amazonPay, paymentIntentPaymentMethodOptions.amazonPay) &&
        Objects.equals(this.auBecsDebit, paymentIntentPaymentMethodOptions.auBecsDebit) &&
        Objects.equals(this.bacsDebit, paymentIntentPaymentMethodOptions.bacsDebit) &&
        Objects.equals(this.bancontact, paymentIntentPaymentMethodOptions.bancontact) &&
        Objects.equals(this.blik, paymentIntentPaymentMethodOptions.blik) &&
        Objects.equals(this.boleto, paymentIntentPaymentMethodOptions.boleto) &&
        Objects.equals(this.card, paymentIntentPaymentMethodOptions.card) &&
        Objects.equals(this.cardPresent, paymentIntentPaymentMethodOptions.cardPresent) &&
        Objects.equals(this.cashapp, paymentIntentPaymentMethodOptions.cashapp) &&
        Objects.equals(this.customerBalance, paymentIntentPaymentMethodOptions.customerBalance) &&
        Objects.equals(this.eps, paymentIntentPaymentMethodOptions.eps) &&
        Objects.equals(this.fpx, paymentIntentPaymentMethodOptions.fpx) &&
        Objects.equals(this.giropay, paymentIntentPaymentMethodOptions.giropay) &&
        Objects.equals(this.grabpay, paymentIntentPaymentMethodOptions.grabpay) &&
        Objects.equals(this.ideal, paymentIntentPaymentMethodOptions.ideal) &&
        Objects.equals(this.interacPresent, paymentIntentPaymentMethodOptions.interacPresent) &&
        Objects.equals(this.kakaoPay, paymentIntentPaymentMethodOptions.kakaoPay) &&
        Objects.equals(this.klarna, paymentIntentPaymentMethodOptions.klarna) &&
        Objects.equals(this.konbini, paymentIntentPaymentMethodOptions.konbini) &&
        Objects.equals(this.krCard, paymentIntentPaymentMethodOptions.krCard) &&
        Objects.equals(this.link, paymentIntentPaymentMethodOptions.link) &&
        Objects.equals(this.mobilepay, paymentIntentPaymentMethodOptions.mobilepay) &&
        Objects.equals(this.multibanco, paymentIntentPaymentMethodOptions.multibanco) &&
        Objects.equals(this.naverPay, paymentIntentPaymentMethodOptions.naverPay) &&
        Objects.equals(this.oxxo, paymentIntentPaymentMethodOptions.oxxo) &&
        Objects.equals(this.p24, paymentIntentPaymentMethodOptions.p24) &&
        Objects.equals(this.payByBank, paymentIntentPaymentMethodOptions.payByBank) &&
        Objects.equals(this.payco, paymentIntentPaymentMethodOptions.payco) &&
        Objects.equals(this.paynow, paymentIntentPaymentMethodOptions.paynow) &&
        Objects.equals(this.paypal, paymentIntentPaymentMethodOptions.paypal) &&
        Objects.equals(this.pix, paymentIntentPaymentMethodOptions.pix) &&
        Objects.equals(this.promptpay, paymentIntentPaymentMethodOptions.promptpay) &&
        Objects.equals(this.revolutPay, paymentIntentPaymentMethodOptions.revolutPay) &&
        Objects.equals(this.samsungPay, paymentIntentPaymentMethodOptions.samsungPay) &&
        Objects.equals(this.sepaDebit, paymentIntentPaymentMethodOptions.sepaDebit) &&
        Objects.equals(this.sofort, paymentIntentPaymentMethodOptions.sofort) &&
        Objects.equals(this.swish, paymentIntentPaymentMethodOptions.swish) &&
        Objects.equals(this.twint, paymentIntentPaymentMethodOptions.twint) &&
        Objects.equals(this.usBankAccount, paymentIntentPaymentMethodOptions.usBankAccount) &&
        Objects.equals(this.wechatPay, paymentIntentPaymentMethodOptions.wechatPay) &&
        Objects.equals(this.zip, paymentIntentPaymentMethodOptions.zip);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acssDebit, affirm, afterpayClearpay, alipay, alma, amazonPay, auBecsDebit, bacsDebit, bancontact, blik, boleto, card, cardPresent, cashapp, customerBalance, eps, fpx, giropay, grabpay, ideal, interacPresent, kakaoPay, klarna, konbini, krCard, link, mobilepay, multibanco, naverPay, oxxo, p24, payByBank, payco, paynow, paypal, pix, promptpay, revolutPay, samsungPay, sepaDebit, sofort, swish, twint, usBankAccount, wechatPay, zip);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentIntentPaymentMethodOptions {\n");
    
    sb.append("    acssDebit: ").append(toIndentedString(acssDebit)).append("\n");
    sb.append("    affirm: ").append(toIndentedString(affirm)).append("\n");
    sb.append("    afterpayClearpay: ").append(toIndentedString(afterpayClearpay)).append("\n");
    sb.append("    alipay: ").append(toIndentedString(alipay)).append("\n");
    sb.append("    alma: ").append(toIndentedString(alma)).append("\n");
    sb.append("    amazonPay: ").append(toIndentedString(amazonPay)).append("\n");
    sb.append("    auBecsDebit: ").append(toIndentedString(auBecsDebit)).append("\n");
    sb.append("    bacsDebit: ").append(toIndentedString(bacsDebit)).append("\n");
    sb.append("    bancontact: ").append(toIndentedString(bancontact)).append("\n");
    sb.append("    blik: ").append(toIndentedString(blik)).append("\n");
    sb.append("    boleto: ").append(toIndentedString(boleto)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("    cardPresent: ").append(toIndentedString(cardPresent)).append("\n");
    sb.append("    cashapp: ").append(toIndentedString(cashapp)).append("\n");
    sb.append("    customerBalance: ").append(toIndentedString(customerBalance)).append("\n");
    sb.append("    eps: ").append(toIndentedString(eps)).append("\n");
    sb.append("    fpx: ").append(toIndentedString(fpx)).append("\n");
    sb.append("    giropay: ").append(toIndentedString(giropay)).append("\n");
    sb.append("    grabpay: ").append(toIndentedString(grabpay)).append("\n");
    sb.append("    ideal: ").append(toIndentedString(ideal)).append("\n");
    sb.append("    interacPresent: ").append(toIndentedString(interacPresent)).append("\n");
    sb.append("    kakaoPay: ").append(toIndentedString(kakaoPay)).append("\n");
    sb.append("    klarna: ").append(toIndentedString(klarna)).append("\n");
    sb.append("    konbini: ").append(toIndentedString(konbini)).append("\n");
    sb.append("    krCard: ").append(toIndentedString(krCard)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    mobilepay: ").append(toIndentedString(mobilepay)).append("\n");
    sb.append("    multibanco: ").append(toIndentedString(multibanco)).append("\n");
    sb.append("    naverPay: ").append(toIndentedString(naverPay)).append("\n");
    sb.append("    oxxo: ").append(toIndentedString(oxxo)).append("\n");
    sb.append("    p24: ").append(toIndentedString(p24)).append("\n");
    sb.append("    payByBank: ").append(toIndentedString(payByBank)).append("\n");
    sb.append("    payco: ").append(toIndentedString(payco)).append("\n");
    sb.append("    paynow: ").append(toIndentedString(paynow)).append("\n");
    sb.append("    paypal: ").append(toIndentedString(paypal)).append("\n");
    sb.append("    pix: ").append(toIndentedString(pix)).append("\n");
    sb.append("    promptpay: ").append(toIndentedString(promptpay)).append("\n");
    sb.append("    revolutPay: ").append(toIndentedString(revolutPay)).append("\n");
    sb.append("    samsungPay: ").append(toIndentedString(samsungPay)).append("\n");
    sb.append("    sepaDebit: ").append(toIndentedString(sepaDebit)).append("\n");
    sb.append("    sofort: ").append(toIndentedString(sofort)).append("\n");
    sb.append("    swish: ").append(toIndentedString(swish)).append("\n");
    sb.append("    twint: ").append(toIndentedString(twint)).append("\n");
    sb.append("    usBankAccount: ").append(toIndentedString(usBankAccount)).append("\n");
    sb.append("    wechatPay: ").append(toIndentedString(wechatPay)).append("\n");
    sb.append("    zip: ").append(toIndentedString(zip)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
