/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.PaymentMethodDetailsCardInstallmentsPlan;

import java.util.ArrayList;
import java.util.List;
/**
 * PaymentMethodOptionsCardInstallments
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodOptionsCardInstallments implements AnyOfpaymentIntentPaymentMethodOptionsCardInstallments {
  @JsonProperty("available_plans")
  private List<PaymentMethodDetailsCardInstallmentsPlan> availablePlans = null;

  @JsonProperty("enabled")
  private Boolean enabled = null;

  @JsonProperty("plan")
  private AnyOfpaymentMethodOptionsCardInstallmentsPlan plan = null;

  public PaymentMethodOptionsCardInstallments availablePlans(List<PaymentMethodDetailsCardInstallmentsPlan> availablePlans) {
    this.availablePlans = availablePlans;
    return this;
  }

  public PaymentMethodOptionsCardInstallments addAvailablePlansItem(PaymentMethodDetailsCardInstallmentsPlan availablePlansItem) {
    if (this.availablePlans == null) {
      this.availablePlans = new ArrayList<>();
    }
    this.availablePlans.add(availablePlansItem);
    return this;
  }

   /**
   * Installment plans that may be selected for this PaymentIntent.
   * @return availablePlans
  **/
  public List<PaymentMethodDetailsCardInstallmentsPlan> getAvailablePlans() {
    return availablePlans;
  }

  public void setAvailablePlans(List<PaymentMethodDetailsCardInstallmentsPlan> availablePlans) {
    this.availablePlans = availablePlans;
  }

  public PaymentMethodOptionsCardInstallments enabled(Boolean enabled) {
    this.enabled = enabled;
    return this;
  }

   /**
   * Whether Installments are enabled for this PaymentIntent.
   * @return enabled
  **/
  public Boolean isEnabled() {
    return enabled;
  }

  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }

  public PaymentMethodOptionsCardInstallments plan(AnyOfpaymentMethodOptionsCardInstallmentsPlan plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Installment plan selected for this PaymentIntent.
   * @return plan
  **/
  public AnyOfpaymentMethodOptionsCardInstallmentsPlan getPlan() {
    return plan;
  }

  public void setPlan(AnyOfpaymentMethodOptionsCardInstallmentsPlan plan) {
    this.plan = plan;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodOptionsCardInstallments paymentMethodOptionsCardInstallments = (PaymentMethodOptionsCardInstallments) o;
    return Objects.equals(this.availablePlans, paymentMethodOptionsCardInstallments.availablePlans) &&
        Objects.equals(this.enabled, paymentMethodOptionsCardInstallments.enabled) &&
        Objects.equals(this.plan, paymentMethodOptionsCardInstallments.plan);
  }

  @Override
  public int hashCode() {
    return Objects.hash(availablePlans, enabled, plan);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodOptionsCardInstallments {\n");
    
    sb.append("    availablePlans: ").append(toIndentedString(availablePlans)).append("\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
