/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.DisplayPreferenceParam;

/**
 * [Link](https://stripe.com/docs/payments/link) is a payment method network. With Link, users save their payment details once, then reuse that information to pay with one click for any business on the network.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PaymentMethodParam28 {
  @JsonProperty("display_preference")
  private DisplayPreferenceParam displayPreference = null;

  public PaymentMethodParam28 displayPreference(DisplayPreferenceParam displayPreference) {
    this.displayPreference = displayPreference;
    return this;
  }

   /**
   * Get displayPreference
   * @return displayPreference
  **/
  public DisplayPreferenceParam getDisplayPreference() {
    return displayPreference;
  }

  public void setDisplayPreference(DisplayPreferenceParam displayPreference) {
    this.displayPreference = displayPreference;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodParam28 paymentMethodParam28 = (PaymentMethodParam28) o;
    return Objects.equals(this.displayPreference, paymentMethodParam28.displayPreference);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayPreference);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodParam28 {\n");
    
    sb.append("    displayPreference: ").append(toIndentedString(displayPreference)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
