/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.DocumentsParam1;

/**
 * PersonDocumentsSpecs1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PersonDocumentsSpecs1 {
  @JsonProperty("company_authorization")
  private DocumentsParam1 companyAuthorization = null;

  @JsonProperty("passport")
  private DocumentsParam1 passport = null;

  @JsonProperty("visa")
  private DocumentsParam1 visa = null;

  public PersonDocumentsSpecs1 companyAuthorization(DocumentsParam1 companyAuthorization) {
    this.companyAuthorization = companyAuthorization;
    return this;
  }

   /**
   * Get companyAuthorization
   * @return companyAuthorization
  **/
  public DocumentsParam1 getCompanyAuthorization() {
    return companyAuthorization;
  }

  public void setCompanyAuthorization(DocumentsParam1 companyAuthorization) {
    this.companyAuthorization = companyAuthorization;
  }

  public PersonDocumentsSpecs1 passport(DocumentsParam1 passport) {
    this.passport = passport;
    return this;
  }

   /**
   * Get passport
   * @return passport
  **/
  public DocumentsParam1 getPassport() {
    return passport;
  }

  public void setPassport(DocumentsParam1 passport) {
    this.passport = passport;
  }

  public PersonDocumentsSpecs1 visa(DocumentsParam1 visa) {
    this.visa = visa;
    return this;
  }

   /**
   * Get visa
   * @return visa
  **/
  public DocumentsParam1 getVisa() {
    return visa;
  }

  public void setVisa(DocumentsParam1 visa) {
    this.visa = visa;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonDocumentsSpecs1 personDocumentsSpecs1 = (PersonDocumentsSpecs1) o;
    return Objects.equals(this.companyAuthorization, personDocumentsSpecs1.companyAuthorization) &&
        Objects.equals(this.passport, personDocumentsSpecs1.passport) &&
        Objects.equals(this.visa, personDocumentsSpecs1.visa);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyAuthorization, passport, visa);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonDocumentsSpecs1 {\n");
    
    sb.append("    companyAuthorization: ").append(toIndentedString(companyAuthorization)).append("\n");
    sb.append("    passport: ").append(toIndentedString(passport)).append("\n");
    sb.append("    visa: ").append(toIndentedString(visa)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
