/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The set of functionalities that the platform can restrict on the FinancialAccount.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class PlatformRestrictions {
  /**
   * Gets or Sets inboundFlows
   */
  public enum InboundFlowsEnum {
    RESTRICTED("restricted"),
    UNRESTRICTED("unrestricted");

    private String value;

    InboundFlowsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static InboundFlowsEnum fromValue(String input) {
      for (InboundFlowsEnum b : InboundFlowsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("inbound_flows")
  private InboundFlowsEnum inboundFlows = null;

  /**
   * Gets or Sets outboundFlows
   */
  public enum OutboundFlowsEnum {
    RESTRICTED("restricted"),
    UNRESTRICTED("unrestricted");

    private String value;

    OutboundFlowsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static OutboundFlowsEnum fromValue(String input) {
      for (OutboundFlowsEnum b : OutboundFlowsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("outbound_flows")
  private OutboundFlowsEnum outboundFlows = null;

  public PlatformRestrictions inboundFlows(InboundFlowsEnum inboundFlows) {
    this.inboundFlows = inboundFlows;
    return this;
  }

   /**
   * Get inboundFlows
   * @return inboundFlows
  **/
  public InboundFlowsEnum getInboundFlows() {
    return inboundFlows;
  }

  public void setInboundFlows(InboundFlowsEnum inboundFlows) {
    this.inboundFlows = inboundFlows;
  }

  public PlatformRestrictions outboundFlows(OutboundFlowsEnum outboundFlows) {
    this.outboundFlows = outboundFlows;
    return this;
  }

   /**
   * Get outboundFlows
   * @return outboundFlows
  **/
  public OutboundFlowsEnum getOutboundFlows() {
    return outboundFlows;
  }

  public void setOutboundFlows(OutboundFlowsEnum outboundFlows) {
    this.outboundFlows = outboundFlows;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PlatformRestrictions platformRestrictions = (PlatformRestrictions) o;
    return Objects.equals(this.inboundFlows, platformRestrictions.inboundFlows) &&
        Objects.equals(this.outboundFlows, platformRestrictions.outboundFlows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inboundFlows, outboundFlows);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PlatformRestrictions {\n");
    
    sb.append("    inboundFlows: ").append(toIndentedString(inboundFlows)).append("\n");
    sb.append("    outboundFlows: ").append(toIndentedString(outboundFlows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
