/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.OptionalFieldsAddress;

/**
 * Shipping details for the invoice. The Invoice PDF will use the &#x60;shipping_details&#x60; value if it is set, otherwise the PDF will render the shipping address from the customer.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class RecipientShippingWithOptionalFieldsAddress {
  @JsonProperty("address")
  private OptionalFieldsAddress address = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("phone")
  private AnyOfrecipientShippingWithOptionalFieldsAddressPhone phone = null;

  public RecipientShippingWithOptionalFieldsAddress address(OptionalFieldsAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public OptionalFieldsAddress getAddress() {
    return address;
  }

  public void setAddress(OptionalFieldsAddress address) {
    this.address = address;
  }

  public RecipientShippingWithOptionalFieldsAddress name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RecipientShippingWithOptionalFieldsAddress phone(AnyOfrecipientShippingWithOptionalFieldsAddressPhone phone) {
    this.phone = phone;
    return this;
  }

   /**
   * Get phone
   * @return phone
  **/
  public AnyOfrecipientShippingWithOptionalFieldsAddressPhone getPhone() {
    return phone;
  }

  public void setPhone(AnyOfrecipientShippingWithOptionalFieldsAddressPhone phone) {
    this.phone = phone;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RecipientShippingWithOptionalFieldsAddress recipientShippingWithOptionalFieldsAddress = (RecipientShippingWithOptionalFieldsAddress) o;
    return Objects.equals(this.address, recipientShippingWithOptionalFieldsAddress.address) &&
        Objects.equals(this.name, recipientShippingWithOptionalFieldsAddress.name) &&
        Objects.equals(this.phone, recipientShippingWithOptionalFieldsAddress.phone);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, name, phone);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RecipientShippingWithOptionalFieldsAddress {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phone: ").append(toIndentedString(phone)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
