/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.BacsDebitPaymentsSpecs;
import com.stripe.api.client.BrandingSettingsSpecs;
import com.stripe.api.client.CardIssuingSettingsSpecs;
import com.stripe.api.client.CardPaymentsSettingsSpecs;
import com.stripe.api.client.PaymentsSettingsSpecs;
import com.stripe.api.client.PayoutSettingsSpecs;
import com.stripe.api.client.TreasurySettingsSpecs;

/**
 * Options for customizing how the account functions within Stripe.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SettingsSpecs {
  @JsonProperty("bacs_debit_payments")
  private BacsDebitPaymentsSpecs bacsDebitPayments = null;

  @JsonProperty("branding")
  private BrandingSettingsSpecs branding = null;

  @JsonProperty("card_issuing")
  private CardIssuingSettingsSpecs cardIssuing = null;

  @JsonProperty("card_payments")
  private CardPaymentsSettingsSpecs cardPayments = null;

  @JsonProperty("payments")
  private PaymentsSettingsSpecs payments = null;

  @JsonProperty("payouts")
  private PayoutSettingsSpecs payouts = null;

  @JsonProperty("treasury")
  private TreasurySettingsSpecs treasury = null;

  public SettingsSpecs bacsDebitPayments(BacsDebitPaymentsSpecs bacsDebitPayments) {
    this.bacsDebitPayments = bacsDebitPayments;
    return this;
  }

   /**
   * Get bacsDebitPayments
   * @return bacsDebitPayments
  **/
  public BacsDebitPaymentsSpecs getBacsDebitPayments() {
    return bacsDebitPayments;
  }

  public void setBacsDebitPayments(BacsDebitPaymentsSpecs bacsDebitPayments) {
    this.bacsDebitPayments = bacsDebitPayments;
  }

  public SettingsSpecs branding(BrandingSettingsSpecs branding) {
    this.branding = branding;
    return this;
  }

   /**
   * Get branding
   * @return branding
  **/
  public BrandingSettingsSpecs getBranding() {
    return branding;
  }

  public void setBranding(BrandingSettingsSpecs branding) {
    this.branding = branding;
  }

  public SettingsSpecs cardIssuing(CardIssuingSettingsSpecs cardIssuing) {
    this.cardIssuing = cardIssuing;
    return this;
  }

   /**
   * Get cardIssuing
   * @return cardIssuing
  **/
  public CardIssuingSettingsSpecs getCardIssuing() {
    return cardIssuing;
  }

  public void setCardIssuing(CardIssuingSettingsSpecs cardIssuing) {
    this.cardIssuing = cardIssuing;
  }

  public SettingsSpecs cardPayments(CardPaymentsSettingsSpecs cardPayments) {
    this.cardPayments = cardPayments;
    return this;
  }

   /**
   * Get cardPayments
   * @return cardPayments
  **/
  public CardPaymentsSettingsSpecs getCardPayments() {
    return cardPayments;
  }

  public void setCardPayments(CardPaymentsSettingsSpecs cardPayments) {
    this.cardPayments = cardPayments;
  }

  public SettingsSpecs payments(PaymentsSettingsSpecs payments) {
    this.payments = payments;
    return this;
  }

   /**
   * Get payments
   * @return payments
  **/
  public PaymentsSettingsSpecs getPayments() {
    return payments;
  }

  public void setPayments(PaymentsSettingsSpecs payments) {
    this.payments = payments;
  }

  public SettingsSpecs payouts(PayoutSettingsSpecs payouts) {
    this.payouts = payouts;
    return this;
  }

   /**
   * Get payouts
   * @return payouts
  **/
  public PayoutSettingsSpecs getPayouts() {
    return payouts;
  }

  public void setPayouts(PayoutSettingsSpecs payouts) {
    this.payouts = payouts;
  }

  public SettingsSpecs treasury(TreasurySettingsSpecs treasury) {
    this.treasury = treasury;
    return this;
  }

   /**
   * Get treasury
   * @return treasury
  **/
  public TreasurySettingsSpecs getTreasury() {
    return treasury;
  }

  public void setTreasury(TreasurySettingsSpecs treasury) {
    this.treasury = treasury;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettingsSpecs settingsSpecs = (SettingsSpecs) o;
    return Objects.equals(this.bacsDebitPayments, settingsSpecs.bacsDebitPayments) &&
        Objects.equals(this.branding, settingsSpecs.branding) &&
        Objects.equals(this.cardIssuing, settingsSpecs.cardIssuing) &&
        Objects.equals(this.cardPayments, settingsSpecs.cardPayments) &&
        Objects.equals(this.payments, settingsSpecs.payments) &&
        Objects.equals(this.payouts, settingsSpecs.payouts) &&
        Objects.equals(this.treasury, settingsSpecs.treasury);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bacsDebitPayments, branding, cardIssuing, cardPayments, payments, payouts, treasury);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettingsSpecs {\n");
    
    sb.append("    bacsDebitPayments: ").append(toIndentedString(bacsDebitPayments)).append("\n");
    sb.append("    branding: ").append(toIndentedString(branding)).append("\n");
    sb.append("    cardIssuing: ").append(toIndentedString(cardIssuing)).append("\n");
    sb.append("    cardPayments: ").append(toIndentedString(cardPayments)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    payouts: ").append(toIndentedString(payouts)).append("\n");
    sb.append("    treasury: ").append(toIndentedString(treasury)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
