/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * A SetupIntent guides you through the process of setting up and saving a customer&#x27;s payment credentials for future payments. For example, you can use a SetupIntent to set up and save your customer&#x27;s card without immediately collecting a payment. Later, you can use [PaymentIntents](https://stripe.com/docs/api#payment_intents) to drive the payment flow.  Create a SetupIntent when you&#x27;re ready to collect your customer&#x27;s payment credentials. Don&#x27;t maintain long-lived, unconfirmed SetupIntents because they might not be valid. The SetupIntent transitions through multiple [statuses](https://docs.stripe.com/payments/intents#intent-statuses) as it guides you through the setup process.  Successful SetupIntents result in payment credentials that are optimized for future payments. For example, cardholders in [certain regions](https://stripe.com/guides/strong-customer-authentication) might need to be run through [Strong Customer Authentication](https://docs.stripe.com/strong-customer-authentication) during payment method collection to streamline later [off-session payments](https://docs.stripe.com/payments/setup-intents). If you use the SetupIntent with a [Customer](https://stripe.com/docs/api#setup_intent_object-customer), it automatically attaches the resulting payment method to that Customer after successful setup. We recommend using SetupIntents or [setup_future_usage](https://stripe.com/docs/api#payment_intent_object-setup_future_usage) on PaymentIntents to save payment methods to prevent saving invalid or unoptimized payment methods.  By using SetupIntents, you can reduce friction for your customers, even as regulations change over time.  Related guide: [Setup Intents API](https://docs.stripe.com/payments/setup-intents)
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SetupIntent implements AnyOfcheckoutSessionSetupIntent, AnyOfsetupAttemptSetupIntent, AnyOfsubscriptionPendingSetupIntent, AnyOfterminalReaderReaderResourceProcessSetupIntentActionSetupIntent {
  @JsonProperty("application")
  private AnyOfsetupIntentApplication application = null;

  @JsonProperty("attach_to_self")
  private Boolean attachToSelf = null;

  @JsonProperty("automatic_payment_methods")
  private AnyOfsetupIntentAutomaticPaymentMethods automaticPaymentMethods = null;

  /**
   * Reason for cancellation of this SetupIntent, one of &#x60;abandoned&#x60;, &#x60;requested_by_customer&#x60;, or &#x60;duplicate&#x60;.
   */
  public enum CancellationReasonEnum {
    ABANDONED("abandoned"),
    DUPLICATE("duplicate"),
    REQUESTED_BY_CUSTOMER("requested_by_customer");

    private String value;

    CancellationReasonEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static CancellationReasonEnum fromValue(String input) {
      for (CancellationReasonEnum b : CancellationReasonEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("cancellation_reason")
  private CancellationReasonEnum cancellationReason = null;

  @JsonProperty("client_secret")
  private String clientSecret = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("customer")
  private AnyOfsetupIntentCustomer customer = null;

  @JsonProperty("description")
  private String description = null;

  /**
   * Gets or Sets flowDirections
   */
  public enum FlowDirectionsEnum {
    INBOUND("inbound"),
    OUTBOUND("outbound");

    private String value;

    FlowDirectionsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static FlowDirectionsEnum fromValue(String input) {
      for (FlowDirectionsEnum b : FlowDirectionsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("flow_directions")
  private List<FlowDirectionsEnum> flowDirections = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("last_setup_error")
  private AnyOfsetupIntentLastSetupError lastSetupError = null;

  @JsonProperty("latest_attempt")
  private AnyOfsetupIntentLatestAttempt latestAttempt = null;

  @JsonProperty("livemode")
  private Boolean livemode = null;

  @JsonProperty("mandate")
  private AnyOfsetupIntentMandate mandate = null;

  @JsonProperty("metadata")
  private Map<String, String> metadata = null;

  @JsonProperty("next_action")
  private AnyOfsetupIntentNextAction nextAction = null;

  /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   */
  public enum ObjectEnum {
    SETUP_INTENT("setup_intent");

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ObjectEnum fromValue(String input) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("object")
  private ObjectEnum object = null;

  @JsonProperty("on_behalf_of")
  private AnyOfsetupIntentOnBehalfOf onBehalfOf = null;

  @JsonProperty("payment_method")
  private AnyOfsetupIntentPaymentMethod paymentMethod = null;

  @JsonProperty("payment_method_configuration_details")
  private AnyOfsetupIntentPaymentMethodConfigurationDetails paymentMethodConfigurationDetails = null;

  @JsonProperty("payment_method_options")
  private AnyOfsetupIntentPaymentMethodOptions paymentMethodOptions = null;

  @JsonProperty("payment_method_types")
  private List<String> paymentMethodTypes = new ArrayList<>();

  @JsonProperty("single_use_mandate")
  private AnyOfsetupIntentSingleUseMandate singleUseMandate = null;

  /**
   * [Status](https://stripe.com/docs/payments/intents#intent-statuses) of this SetupIntent, one of &#x60;requires_payment_method&#x60;, &#x60;requires_confirmation&#x60;, &#x60;requires_action&#x60;, &#x60;processing&#x60;, &#x60;canceled&#x60;, or &#x60;succeeded&#x60;.
   */
  public enum StatusEnum {
    CANCELED("canceled"),
    PROCESSING("processing"),
    REQUIRES_ACTION("requires_action"),
    REQUIRES_CONFIRMATION("requires_confirmation"),
    REQUIRES_PAYMENT_METHOD("requires_payment_method"),
    SUCCEEDED("succeeded");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("usage")
  private String usage = null;

  public SetupIntent application(AnyOfsetupIntentApplication application) {
    this.application = application;
    return this;
  }

   /**
   * ID of the Connect application that created the SetupIntent.
   * @return application
  **/
  public AnyOfsetupIntentApplication getApplication() {
    return application;
  }

  public void setApplication(AnyOfsetupIntentApplication application) {
    this.application = application;
  }

  public SetupIntent attachToSelf(Boolean attachToSelf) {
    this.attachToSelf = attachToSelf;
    return this;
  }

   /**
   * If present, the SetupIntent&#x27;s payment method will be attached to the in-context Stripe Account.  It can only be used for this Stripe Account’s own money movement flows like InboundTransfer and OutboundTransfers. It cannot be set to true when setting up a PaymentMethod for a Customer, and defaults to false when attaching a PaymentMethod to a Customer.
   * @return attachToSelf
  **/
  public Boolean isAttachToSelf() {
    return attachToSelf;
  }

  public void setAttachToSelf(Boolean attachToSelf) {
    this.attachToSelf = attachToSelf;
  }

  public SetupIntent automaticPaymentMethods(AnyOfsetupIntentAutomaticPaymentMethods automaticPaymentMethods) {
    this.automaticPaymentMethods = automaticPaymentMethods;
    return this;
  }

   /**
   * Settings for dynamic payment methods compatible with this Setup Intent
   * @return automaticPaymentMethods
  **/
  public AnyOfsetupIntentAutomaticPaymentMethods getAutomaticPaymentMethods() {
    return automaticPaymentMethods;
  }

  public void setAutomaticPaymentMethods(AnyOfsetupIntentAutomaticPaymentMethods automaticPaymentMethods) {
    this.automaticPaymentMethods = automaticPaymentMethods;
  }

  public SetupIntent cancellationReason(CancellationReasonEnum cancellationReason) {
    this.cancellationReason = cancellationReason;
    return this;
  }

   /**
   * Reason for cancellation of this SetupIntent, one of &#x60;abandoned&#x60;, &#x60;requested_by_customer&#x60;, or &#x60;duplicate&#x60;.
   * @return cancellationReason
  **/
  public CancellationReasonEnum getCancellationReason() {
    return cancellationReason;
  }

  public void setCancellationReason(CancellationReasonEnum cancellationReason) {
    this.cancellationReason = cancellationReason;
  }

  public SetupIntent clientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
    return this;
  }

   /**
   * The client secret of this SetupIntent. Used for client-side retrieval using a publishable key.  The client secret can be used to complete payment setup from your frontend. It should not be stored, logged, or exposed to anyone other than the customer. Make sure that you have TLS enabled on any page that includes the client secret.
   * @return clientSecret
  **/
  public String getClientSecret() {
    return clientSecret;
  }

  public void setClientSecret(String clientSecret) {
    this.clientSecret = clientSecret;
  }

  public SetupIntent created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Time at which the object was created. Measured in seconds since the Unix epoch.
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public SetupIntent customer(AnyOfsetupIntentCustomer customer) {
    this.customer = customer;
    return this;
  }

   /**
   * ID of the Customer this SetupIntent belongs to, if one exists.  If present, the SetupIntent&#x27;s payment method will be attached to the Customer on successful setup. Payment methods attached to other Customers cannot be used with this SetupIntent.
   * @return customer
  **/
  public AnyOfsetupIntentCustomer getCustomer() {
    return customer;
  }

  public void setCustomer(AnyOfsetupIntentCustomer customer) {
    this.customer = customer;
  }

  public SetupIntent description(String description) {
    this.description = description;
    return this;
  }

   /**
   * An arbitrary string attached to the object. Often useful for displaying to users.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public SetupIntent flowDirections(List<FlowDirectionsEnum> flowDirections) {
    this.flowDirections = flowDirections;
    return this;
  }

  public SetupIntent addFlowDirectionsItem(FlowDirectionsEnum flowDirectionsItem) {
    if (this.flowDirections == null) {
      this.flowDirections = new ArrayList<>();
    }
    this.flowDirections.add(flowDirectionsItem);
    return this;
  }

   /**
   * Indicates the directions of money movement for which this payment method is intended to be used.  Include &#x60;inbound&#x60; if you intend to use the payment method as the origin to pull funds from. Include &#x60;outbound&#x60; if you intend to use the payment method as the destination to send funds to. You can include both if you intend to use the payment method for both purposes.
   * @return flowDirections
  **/
  public List<FlowDirectionsEnum> getFlowDirections() {
    return flowDirections;
  }

  public void setFlowDirections(List<FlowDirectionsEnum> flowDirections) {
    this.flowDirections = flowDirections;
  }

  public SetupIntent id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the object.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SetupIntent lastSetupError(AnyOfsetupIntentLastSetupError lastSetupError) {
    this.lastSetupError = lastSetupError;
    return this;
  }

   /**
   * The error encountered in the previous SetupIntent confirmation.
   * @return lastSetupError
  **/
  public AnyOfsetupIntentLastSetupError getLastSetupError() {
    return lastSetupError;
  }

  public void setLastSetupError(AnyOfsetupIntentLastSetupError lastSetupError) {
    this.lastSetupError = lastSetupError;
  }

  public SetupIntent latestAttempt(AnyOfsetupIntentLatestAttempt latestAttempt) {
    this.latestAttempt = latestAttempt;
    return this;
  }

   /**
   * The most recent SetupAttempt for this SetupIntent.
   * @return latestAttempt
  **/
  public AnyOfsetupIntentLatestAttempt getLatestAttempt() {
    return latestAttempt;
  }

  public void setLatestAttempt(AnyOfsetupIntentLatestAttempt latestAttempt) {
    this.latestAttempt = latestAttempt;
  }

  public SetupIntent livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Has the value &#x60;true&#x60; if the object exists in live mode or the value &#x60;false&#x60; if the object exists in test mode.
   * @return livemode
  **/
  public Boolean isLivemode() {
    return livemode;
  }

  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }

  public SetupIntent mandate(AnyOfsetupIntentMandate mandate) {
    this.mandate = mandate;
    return this;
  }

   /**
   * ID of the multi use Mandate generated by the SetupIntent.
   * @return mandate
  **/
  public AnyOfsetupIntentMandate getMandate() {
    return mandate;
  }

  public void setMandate(AnyOfsetupIntentMandate mandate) {
    this.mandate = mandate;
  }

  public SetupIntent metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public SetupIntent putMetadataItem(String key, String metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
   * @return metadata
  **/
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public SetupIntent nextAction(AnyOfsetupIntentNextAction nextAction) {
    this.nextAction = nextAction;
    return this;
  }

   /**
   * If present, this property tells you what actions you need to take in order for your customer to continue payment setup.
   * @return nextAction
  **/
  public AnyOfsetupIntentNextAction getNextAction() {
    return nextAction;
  }

  public void setNextAction(AnyOfsetupIntentNextAction nextAction) {
    this.nextAction = nextAction;
  }

  public SetupIntent object(ObjectEnum object) {
    this.object = object;
    return this;
  }

   /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   * @return object
  **/
  public ObjectEnum getObject() {
    return object;
  }

  public void setObject(ObjectEnum object) {
    this.object = object;
  }

  public SetupIntent onBehalfOf(AnyOfsetupIntentOnBehalfOf onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
    return this;
  }

   /**
   * The account (if any) for which the setup is intended.
   * @return onBehalfOf
  **/
  public AnyOfsetupIntentOnBehalfOf getOnBehalfOf() {
    return onBehalfOf;
  }

  public void setOnBehalfOf(AnyOfsetupIntentOnBehalfOf onBehalfOf) {
    this.onBehalfOf = onBehalfOf;
  }

  public SetupIntent paymentMethod(AnyOfsetupIntentPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * ID of the payment method used with this SetupIntent. If the payment method is &#x60;card_present&#x60; and isn&#x27;t a digital wallet, then the [generated_card](https://docs.stripe.com/api/setup_attempts/object#setup_attempt_object-payment_method_details-card_present-generated_card) associated with the &#x60;latest_attempt&#x60; is attached to the Customer instead.
   * @return paymentMethod
  **/
  public AnyOfsetupIntentPaymentMethod getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(AnyOfsetupIntentPaymentMethod paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public SetupIntent paymentMethodConfigurationDetails(AnyOfsetupIntentPaymentMethodConfigurationDetails paymentMethodConfigurationDetails) {
    this.paymentMethodConfigurationDetails = paymentMethodConfigurationDetails;
    return this;
  }

   /**
   * Information about the [payment method configuration](https://stripe.com/docs/api/payment_method_configurations) used for this Setup Intent.
   * @return paymentMethodConfigurationDetails
  **/
  public AnyOfsetupIntentPaymentMethodConfigurationDetails getPaymentMethodConfigurationDetails() {
    return paymentMethodConfigurationDetails;
  }

  public void setPaymentMethodConfigurationDetails(AnyOfsetupIntentPaymentMethodConfigurationDetails paymentMethodConfigurationDetails) {
    this.paymentMethodConfigurationDetails = paymentMethodConfigurationDetails;
  }

  public SetupIntent paymentMethodOptions(AnyOfsetupIntentPaymentMethodOptions paymentMethodOptions) {
    this.paymentMethodOptions = paymentMethodOptions;
    return this;
  }

   /**
   * Payment method-specific configuration for this SetupIntent.
   * @return paymentMethodOptions
  **/
  public AnyOfsetupIntentPaymentMethodOptions getPaymentMethodOptions() {
    return paymentMethodOptions;
  }

  public void setPaymentMethodOptions(AnyOfsetupIntentPaymentMethodOptions paymentMethodOptions) {
    this.paymentMethodOptions = paymentMethodOptions;
  }

  public SetupIntent paymentMethodTypes(List<String> paymentMethodTypes) {
    this.paymentMethodTypes = paymentMethodTypes;
    return this;
  }

  public SetupIntent addPaymentMethodTypesItem(String paymentMethodTypesItem) {
    this.paymentMethodTypes.add(paymentMethodTypesItem);
    return this;
  }

   /**
   * The list of payment method types (e.g. card) that this SetupIntent is allowed to set up.
   * @return paymentMethodTypes
  **/
  public List<String> getPaymentMethodTypes() {
    return paymentMethodTypes;
  }

  public void setPaymentMethodTypes(List<String> paymentMethodTypes) {
    this.paymentMethodTypes = paymentMethodTypes;
  }

  public SetupIntent singleUseMandate(AnyOfsetupIntentSingleUseMandate singleUseMandate) {
    this.singleUseMandate = singleUseMandate;
    return this;
  }

   /**
   * ID of the single_use Mandate generated by the SetupIntent.
   * @return singleUseMandate
  **/
  public AnyOfsetupIntentSingleUseMandate getSingleUseMandate() {
    return singleUseMandate;
  }

  public void setSingleUseMandate(AnyOfsetupIntentSingleUseMandate singleUseMandate) {
    this.singleUseMandate = singleUseMandate;
  }

  public SetupIntent status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * [Status](https://stripe.com/docs/payments/intents#intent-statuses) of this SetupIntent, one of &#x60;requires_payment_method&#x60;, &#x60;requires_confirmation&#x60;, &#x60;requires_action&#x60;, &#x60;processing&#x60;, &#x60;canceled&#x60;, or &#x60;succeeded&#x60;.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public SetupIntent usage(String usage) {
    this.usage = usage;
    return this;
  }

   /**
   * Indicates how the payment method is intended to be used in the future.  Use &#x60;on_session&#x60; if you intend to only reuse the payment method when the customer is in your checkout flow. Use &#x60;off_session&#x60; if your customer may or may not be in your checkout flow. If not provided, this value defaults to &#x60;off_session&#x60;.
   * @return usage
  **/
  public String getUsage() {
    return usage;
  }

  public void setUsage(String usage) {
    this.usage = usage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetupIntent setupIntent = (SetupIntent) o;
    return Objects.equals(this.application, setupIntent.application) &&
        Objects.equals(this.attachToSelf, setupIntent.attachToSelf) &&
        Objects.equals(this.automaticPaymentMethods, setupIntent.automaticPaymentMethods) &&
        Objects.equals(this.cancellationReason, setupIntent.cancellationReason) &&
        Objects.equals(this.clientSecret, setupIntent.clientSecret) &&
        Objects.equals(this.created, setupIntent.created) &&
        Objects.equals(this.customer, setupIntent.customer) &&
        Objects.equals(this.description, setupIntent.description) &&
        Objects.equals(this.flowDirections, setupIntent.flowDirections) &&
        Objects.equals(this.id, setupIntent.id) &&
        Objects.equals(this.lastSetupError, setupIntent.lastSetupError) &&
        Objects.equals(this.latestAttempt, setupIntent.latestAttempt) &&
        Objects.equals(this.livemode, setupIntent.livemode) &&
        Objects.equals(this.mandate, setupIntent.mandate) &&
        Objects.equals(this.metadata, setupIntent.metadata) &&
        Objects.equals(this.nextAction, setupIntent.nextAction) &&
        Objects.equals(this.object, setupIntent.object) &&
        Objects.equals(this.onBehalfOf, setupIntent.onBehalfOf) &&
        Objects.equals(this.paymentMethod, setupIntent.paymentMethod) &&
        Objects.equals(this.paymentMethodConfigurationDetails, setupIntent.paymentMethodConfigurationDetails) &&
        Objects.equals(this.paymentMethodOptions, setupIntent.paymentMethodOptions) &&
        Objects.equals(this.paymentMethodTypes, setupIntent.paymentMethodTypes) &&
        Objects.equals(this.singleUseMandate, setupIntent.singleUseMandate) &&
        Objects.equals(this.status, setupIntent.status) &&
        Objects.equals(this.usage, setupIntent.usage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(application, attachToSelf, automaticPaymentMethods, cancellationReason, clientSecret, created, customer, description, flowDirections, id, lastSetupError, latestAttempt, livemode, mandate, metadata, nextAction, object, onBehalfOf, paymentMethod, paymentMethodConfigurationDetails, paymentMethodOptions, paymentMethodTypes, singleUseMandate, status, usage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetupIntent {\n");
    
    sb.append("    application: ").append(toIndentedString(application)).append("\n");
    sb.append("    attachToSelf: ").append(toIndentedString(attachToSelf)).append("\n");
    sb.append("    automaticPaymentMethods: ").append(toIndentedString(automaticPaymentMethods)).append("\n");
    sb.append("    cancellationReason: ").append(toIndentedString(cancellationReason)).append("\n");
    sb.append("    clientSecret: ").append(toIndentedString(clientSecret)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    customer: ").append(toIndentedString(customer)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    flowDirections: ").append(toIndentedString(flowDirections)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastSetupError: ").append(toIndentedString(lastSetupError)).append("\n");
    sb.append("    latestAttempt: ").append(toIndentedString(latestAttempt)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    mandate: ").append(toIndentedString(mandate)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    nextAction: ").append(toIndentedString(nextAction)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    onBehalfOf: ").append(toIndentedString(onBehalfOf)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentMethodConfigurationDetails: ").append(toIndentedString(paymentMethodConfigurationDetails)).append("\n");
    sb.append("    paymentMethodOptions: ").append(toIndentedString(paymentMethodOptions)).append("\n");
    sb.append("    paymentMethodTypes: ").append(toIndentedString(paymentMethodTypes)).append("\n");
    sb.append("    singleUseMandate: ").append(toIndentedString(singleUseMandate)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    usage: ").append(toIndentedString(usage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
