/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.AddressValidationParam;
import com.stripe.api.client.CustomsParam;
import com.stripe.api.client.RequiredAddress;

/**
 * Updated shipping information for the card.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class ShippingSpecs1 {
  @JsonProperty("address")
  private RequiredAddress address = null;

  @JsonProperty("address_validation")
  private AddressValidationParam addressValidation = null;

  @JsonProperty("customs")
  private CustomsParam customs = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("phone_number")
  private String phoneNumber = null;

  @JsonProperty("require_signature")
  private Boolean requireSignature = null;

  /**
   * Gets or Sets service
   */
  public enum ServiceEnum {
    EXPRESS("express"),
    PRIORITY("priority"),
    STANDARD("standard");

    private String value;

    ServiceEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ServiceEnum fromValue(String input) {
      for (ServiceEnum b : ServiceEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("service")
  private ServiceEnum service = null;

  /**
   * Gets or Sets type
   */
  public enum TypeEnum {
    BULK("bulk"),
    INDIVIDUAL("individual");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static TypeEnum fromValue(String input) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("type")
  private TypeEnum type = null;

  public ShippingSpecs1 address(RequiredAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  public RequiredAddress getAddress() {
    return address;
  }

  public void setAddress(RequiredAddress address) {
    this.address = address;
  }

  public ShippingSpecs1 addressValidation(AddressValidationParam addressValidation) {
    this.addressValidation = addressValidation;
    return this;
  }

   /**
   * Get addressValidation
   * @return addressValidation
  **/
  public AddressValidationParam getAddressValidation() {
    return addressValidation;
  }

  public void setAddressValidation(AddressValidationParam addressValidation) {
    this.addressValidation = addressValidation;
  }

  public ShippingSpecs1 customs(CustomsParam customs) {
    this.customs = customs;
    return this;
  }

   /**
   * Get customs
   * @return customs
  **/
  public CustomsParam getCustoms() {
    return customs;
  }

  public void setCustoms(CustomsParam customs) {
    this.customs = customs;
  }

  public ShippingSpecs1 name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ShippingSpecs1 phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * Get phoneNumber
   * @return phoneNumber
  **/
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public ShippingSpecs1 requireSignature(Boolean requireSignature) {
    this.requireSignature = requireSignature;
    return this;
  }

   /**
   * Get requireSignature
   * @return requireSignature
  **/
  public Boolean isRequireSignature() {
    return requireSignature;
  }

  public void setRequireSignature(Boolean requireSignature) {
    this.requireSignature = requireSignature;
  }

  public ShippingSpecs1 service(ServiceEnum service) {
    this.service = service;
    return this;
  }

   /**
   * Get service
   * @return service
  **/
  public ServiceEnum getService() {
    return service;
  }

  public void setService(ServiceEnum service) {
    this.service = service;
  }

  public ShippingSpecs1 type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingSpecs1 shippingSpecs1 = (ShippingSpecs1) o;
    return Objects.equals(this.address, shippingSpecs1.address) &&
        Objects.equals(this.addressValidation, shippingSpecs1.addressValidation) &&
        Objects.equals(this.customs, shippingSpecs1.customs) &&
        Objects.equals(this.name, shippingSpecs1.name) &&
        Objects.equals(this.phoneNumber, shippingSpecs1.phoneNumber) &&
        Objects.equals(this.requireSignature, shippingSpecs1.requireSignature) &&
        Objects.equals(this.service, shippingSpecs1.service) &&
        Objects.equals(this.type, shippingSpecs1.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(address, addressValidation, customs, name, phoneNumber, requireSignature, service, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingSpecs1 {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    addressValidation: ").append(toIndentedString(addressValidation)).append("\n");
    sb.append("    customs: ").append(toIndentedString(customs)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    requireSignature: ").append(toIndentedString(requireSignature)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
