/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ShippingRateDeliveryEstimate
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class ShippingRateDeliveryEstimate implements AnyOfshippingRateDeliveryEstimate {
  @JsonProperty("maximum")
  private AnyOfshippingRateDeliveryEstimateMaximum maximum = null;

  @JsonProperty("minimum")
  private AnyOfshippingRateDeliveryEstimateMinimum minimum = null;

  public ShippingRateDeliveryEstimate maximum(AnyOfshippingRateDeliveryEstimateMaximum maximum) {
    this.maximum = maximum;
    return this;
  }

   /**
   * The upper bound of the estimated range. If empty, represents no upper bound i.e., infinite.
   * @return maximum
  **/
  public AnyOfshippingRateDeliveryEstimateMaximum getMaximum() {
    return maximum;
  }

  public void setMaximum(AnyOfshippingRateDeliveryEstimateMaximum maximum) {
    this.maximum = maximum;
  }

  public ShippingRateDeliveryEstimate minimum(AnyOfshippingRateDeliveryEstimateMinimum minimum) {
    this.minimum = minimum;
    return this;
  }

   /**
   * The lower bound of the estimated range. If empty, represents no lower bound.
   * @return minimum
  **/
  public AnyOfshippingRateDeliveryEstimateMinimum getMinimum() {
    return minimum;
  }

  public void setMinimum(AnyOfshippingRateDeliveryEstimateMinimum minimum) {
    this.minimum = minimum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ShippingRateDeliveryEstimate shippingRateDeliveryEstimate = (ShippingRateDeliveryEstimate) o;
    return Objects.equals(this.maximum, shippingRateDeliveryEstimate.maximum) &&
        Objects.equals(this.minimum, shippingRateDeliveryEstimate.minimum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maximum, minimum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ShippingRateDeliveryEstimate {\n");
    
    sb.append("    maximum: ").append(toIndentedString(maximum)).append("\n");
    sb.append("    minimum: ").append(toIndentedString(minimum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
