/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SourceTypeSofort
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SourceTypeSofort {
  @JsonProperty("bank_code")
  private String bankCode = null;

  @JsonProperty("bank_name")
  private String bankName = null;

  @JsonProperty("bic")
  private String bic = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("iban_last4")
  private String ibanLast4 = null;

  @JsonProperty("preferred_language")
  private String preferredLanguage = null;

  @JsonProperty("statement_descriptor")
  private String statementDescriptor = null;

  public SourceTypeSofort bankCode(String bankCode) {
    this.bankCode = bankCode;
    return this;
  }

   /**
   * Get bankCode
   * @return bankCode
  **/
  public String getBankCode() {
    return bankCode;
  }

  public void setBankCode(String bankCode) {
    this.bankCode = bankCode;
  }

  public SourceTypeSofort bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

   /**
   * Get bankName
   * @return bankName
  **/
  public String getBankName() {
    return bankName;
  }

  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public SourceTypeSofort bic(String bic) {
    this.bic = bic;
    return this;
  }

   /**
   * Get bic
   * @return bic
  **/
  public String getBic() {
    return bic;
  }

  public void setBic(String bic) {
    this.bic = bic;
  }

  public SourceTypeSofort country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public SourceTypeSofort ibanLast4(String ibanLast4) {
    this.ibanLast4 = ibanLast4;
    return this;
  }

   /**
   * Get ibanLast4
   * @return ibanLast4
  **/
  public String getIbanLast4() {
    return ibanLast4;
  }

  public void setIbanLast4(String ibanLast4) {
    this.ibanLast4 = ibanLast4;
  }

  public SourceTypeSofort preferredLanguage(String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
    return this;
  }

   /**
   * Get preferredLanguage
   * @return preferredLanguage
  **/
  public String getPreferredLanguage() {
    return preferredLanguage;
  }

  public void setPreferredLanguage(String preferredLanguage) {
    this.preferredLanguage = preferredLanguage;
  }

  public SourceTypeSofort statementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
    return this;
  }

   /**
   * Get statementDescriptor
   * @return statementDescriptor
  **/
  public String getStatementDescriptor() {
    return statementDescriptor;
  }

  public void setStatementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SourceTypeSofort sourceTypeSofort = (SourceTypeSofort) o;
    return Objects.equals(this.bankCode, sourceTypeSofort.bankCode) &&
        Objects.equals(this.bankName, sourceTypeSofort.bankName) &&
        Objects.equals(this.bic, sourceTypeSofort.bic) &&
        Objects.equals(this.country, sourceTypeSofort.country) &&
        Objects.equals(this.ibanLast4, sourceTypeSofort.ibanLast4) &&
        Objects.equals(this.preferredLanguage, sourceTypeSofort.preferredLanguage) &&
        Objects.equals(this.statementDescriptor, sourceTypeSofort.statementDescriptor);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bankCode, bankName, bic, country, ibanLast4, preferredLanguage, statementDescriptor);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SourceTypeSofort {\n");
    
    sb.append("    bankCode: ").append(toIndentedString(bankCode)).append("\n");
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    ibanLast4: ").append(toIndentedString(ibanLast4)).append("\n");
    sb.append("    preferredLanguage: ").append(toIndentedString(preferredLanguage)).append("\n");
    sb.append("    statementDescriptor: ").append(toIndentedString(statementDescriptor)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
