/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubscriptionScheduleCurrentPhase
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SubscriptionScheduleCurrentPhase implements AnyOfsubscriptionScheduleCurrentPhase {
  @JsonProperty("end_date")
  private Integer endDate = null;

  @JsonProperty("start_date")
  private Integer startDate = null;

  public SubscriptionScheduleCurrentPhase endDate(Integer endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * The end of this phase of the subscription schedule.
   * @return endDate
  **/
  public Integer getEndDate() {
    return endDate;
  }

  public void setEndDate(Integer endDate) {
    this.endDate = endDate;
  }

  public SubscriptionScheduleCurrentPhase startDate(Integer startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * The start of this phase of the subscription schedule.
   * @return startDate
  **/
  public Integer getStartDate() {
    return startDate;
  }

  public void setStartDate(Integer startDate) {
    this.startDate = startDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionScheduleCurrentPhase subscriptionScheduleCurrentPhase = (SubscriptionScheduleCurrentPhase) o;
    return Objects.equals(this.endDate, subscriptionScheduleCurrentPhase.endDate) &&
        Objects.equals(this.startDate, subscriptionScheduleCurrentPhase.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(endDate, startDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionScheduleCurrentPhase {\n");
    
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
