/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubscriptionItemsItemBody1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SubscriptionItemsItemBody1 {
  @JsonProperty("clear_usage")
  private Boolean clearUsage = null;

  /**
   * Determines how to handle [prorations](https://stripe.com/docs/billing/subscriptions/prorations) when the billing cycle changes (e.g., when switching plans, resetting &#x60;billing_cycle_anchor&#x3D;now&#x60;, or starting a trial), or if an item&#x27;s &#x60;quantity&#x60; changes. The default value is &#x60;create_prorations&#x60;.
   */
  public enum ProrationBehaviorEnum {
    ALWAYS_INVOICE("always_invoice"),
    CREATE_PRORATIONS("create_prorations"),
    NONE("none");

    private String value;

    ProrationBehaviorEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ProrationBehaviorEnum fromValue(String input) {
      for (ProrationBehaviorEnum b : ProrationBehaviorEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("proration_behavior")
  private ProrationBehaviorEnum prorationBehavior = null;

  @JsonProperty("proration_date")
  private Integer prorationDate = null;

  public SubscriptionItemsItemBody1 clearUsage(Boolean clearUsage) {
    this.clearUsage = clearUsage;
    return this;
  }

   /**
   * Delete all usage for the given subscription item. Allowed only when the current plan&#x27;s &#x60;usage_type&#x60; is &#x60;metered&#x60;.
   * @return clearUsage
  **/
  public Boolean isClearUsage() {
    return clearUsage;
  }

  public void setClearUsage(Boolean clearUsage) {
    this.clearUsage = clearUsage;
  }

  public SubscriptionItemsItemBody1 prorationBehavior(ProrationBehaviorEnum prorationBehavior) {
    this.prorationBehavior = prorationBehavior;
    return this;
  }

   /**
   * Determines how to handle [prorations](https://stripe.com/docs/billing/subscriptions/prorations) when the billing cycle changes (e.g., when switching plans, resetting &#x60;billing_cycle_anchor&#x3D;now&#x60;, or starting a trial), or if an item&#x27;s &#x60;quantity&#x60; changes. The default value is &#x60;create_prorations&#x60;.
   * @return prorationBehavior
  **/
  public ProrationBehaviorEnum getProrationBehavior() {
    return prorationBehavior;
  }

  public void setProrationBehavior(ProrationBehaviorEnum prorationBehavior) {
    this.prorationBehavior = prorationBehavior;
  }

  public SubscriptionItemsItemBody1 prorationDate(Integer prorationDate) {
    this.prorationDate = prorationDate;
    return this;
  }

   /**
   * If set, the proration will be calculated as though the subscription was updated at the given time. This can be used to apply the same proration that was previewed with the [upcoming invoice](https://stripe.com/docs/api#retrieve_customer_invoice) endpoint.
   * @return prorationDate
  **/
  public Integer getProrationDate() {
    return prorationDate;
  }

  public void setProrationDate(Integer prorationDate) {
    this.prorationDate = prorationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionItemsItemBody1 subscriptionItemsItemBody1 = (SubscriptionItemsItemBody1) o;
    return Objects.equals(this.clearUsage, subscriptionItemsItemBody1.clearUsage) &&
        Objects.equals(this.prorationBehavior, subscriptionItemsItemBody1.prorationBehavior) &&
        Objects.equals(this.prorationDate, subscriptionItemsItemBody1.prorationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clearUsage, prorationBehavior, prorationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionItemsItemBody1 {\n");
    
    sb.append("    clearUsage: ").append(toIndentedString(clearUsage)).append("\n");
    sb.append("    prorationBehavior: ").append(toIndentedString(prorationBehavior)).append("\n");
    sb.append("    prorationDate: ").append(toIndentedString(prorationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
