/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * SubscriptionsResourceBillingCycleAnchorConfig
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SubscriptionsResourceBillingCycleAnchorConfig implements AnyOfsubscriptionBillingCycleAnchorConfig {
  @JsonProperty("day_of_month")
  private Integer dayOfMonth = null;

  @JsonProperty("hour")
  private Integer hour = null;

  @JsonProperty("minute")
  private Integer minute = null;

  @JsonProperty("month")
  private Integer month = null;

  @JsonProperty("second")
  private Integer second = null;

  public SubscriptionsResourceBillingCycleAnchorConfig dayOfMonth(Integer dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
    return this;
  }

   /**
   * The day of the month of the billing_cycle_anchor.
   * @return dayOfMonth
  **/
  public Integer getDayOfMonth() {
    return dayOfMonth;
  }

  public void setDayOfMonth(Integer dayOfMonth) {
    this.dayOfMonth = dayOfMonth;
  }

  public SubscriptionsResourceBillingCycleAnchorConfig hour(Integer hour) {
    this.hour = hour;
    return this;
  }

   /**
   * The hour of the day of the billing_cycle_anchor.
   * @return hour
  **/
  public Integer getHour() {
    return hour;
  }

  public void setHour(Integer hour) {
    this.hour = hour;
  }

  public SubscriptionsResourceBillingCycleAnchorConfig minute(Integer minute) {
    this.minute = minute;
    return this;
  }

   /**
   * The minute of the hour of the billing_cycle_anchor.
   * @return minute
  **/
  public Integer getMinute() {
    return minute;
  }

  public void setMinute(Integer minute) {
    this.minute = minute;
  }

  public SubscriptionsResourceBillingCycleAnchorConfig month(Integer month) {
    this.month = month;
    return this;
  }

   /**
   * The month to start full cycle billing periods.
   * @return month
  **/
  public Integer getMonth() {
    return month;
  }

  public void setMonth(Integer month) {
    this.month = month;
  }

  public SubscriptionsResourceBillingCycleAnchorConfig second(Integer second) {
    this.second = second;
    return this;
  }

   /**
   * The second of the minute of the billing_cycle_anchor.
   * @return second
  **/
  public Integer getSecond() {
    return second;
  }

  public void setSecond(Integer second) {
    this.second = second;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionsResourceBillingCycleAnchorConfig subscriptionsResourceBillingCycleAnchorConfig = (SubscriptionsResourceBillingCycleAnchorConfig) o;
    return Objects.equals(this.dayOfMonth, subscriptionsResourceBillingCycleAnchorConfig.dayOfMonth) &&
        Objects.equals(this.hour, subscriptionsResourceBillingCycleAnchorConfig.hour) &&
        Objects.equals(this.minute, subscriptionsResourceBillingCycleAnchorConfig.minute) &&
        Objects.equals(this.month, subscriptionsResourceBillingCycleAnchorConfig.month) &&
        Objects.equals(this.second, subscriptionsResourceBillingCycleAnchorConfig.second);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dayOfMonth, hour, minute, month, second);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionsResourceBillingCycleAnchorConfig {\n");
    
    sb.append("    dayOfMonth: ").append(toIndentedString(dayOfMonth)).append("\n");
    sb.append("    hour: ").append(toIndentedString(hour)).append("\n");
    sb.append("    minute: ").append(toIndentedString(minute)).append("\n");
    sb.append("    month: ").append(toIndentedString(month)).append("\n");
    sb.append("    second: ").append(toIndentedString(second)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
