/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.Param3;

/**
 * SubscriptionScheduleDefaultSettingsParam
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SubscriptionScheduleDefaultSettingsParam {
  @JsonProperty("account_tax_ids")
  private AnyOfsubscriptionScheduleDefaultSettingsParamAccountTaxIds accountTaxIds = null;

  @JsonProperty("days_until_due")
  private Integer daysUntilDue = null;

  @JsonProperty("issuer")
  private Param3 issuer = null;

  public SubscriptionScheduleDefaultSettingsParam accountTaxIds(AnyOfsubscriptionScheduleDefaultSettingsParamAccountTaxIds accountTaxIds) {
    this.accountTaxIds = accountTaxIds;
    return this;
  }

   /**
   * Get accountTaxIds
   * @return accountTaxIds
  **/
  public AnyOfsubscriptionScheduleDefaultSettingsParamAccountTaxIds getAccountTaxIds() {
    return accountTaxIds;
  }

  public void setAccountTaxIds(AnyOfsubscriptionScheduleDefaultSettingsParamAccountTaxIds accountTaxIds) {
    this.accountTaxIds = accountTaxIds;
  }

  public SubscriptionScheduleDefaultSettingsParam daysUntilDue(Integer daysUntilDue) {
    this.daysUntilDue = daysUntilDue;
    return this;
  }

   /**
   * Get daysUntilDue
   * @return daysUntilDue
  **/
  public Integer getDaysUntilDue() {
    return daysUntilDue;
  }

  public void setDaysUntilDue(Integer daysUntilDue) {
    this.daysUntilDue = daysUntilDue;
  }

  public SubscriptionScheduleDefaultSettingsParam issuer(Param3 issuer) {
    this.issuer = issuer;
    return this;
  }

   /**
   * Get issuer
   * @return issuer
  **/
  public Param3 getIssuer() {
    return issuer;
  }

  public void setIssuer(Param3 issuer) {
    this.issuer = issuer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionScheduleDefaultSettingsParam subscriptionScheduleDefaultSettingsParam = (SubscriptionScheduleDefaultSettingsParam) o;
    return Objects.equals(this.accountTaxIds, subscriptionScheduleDefaultSettingsParam.accountTaxIds) &&
        Objects.equals(this.daysUntilDue, subscriptionScheduleDefaultSettingsParam.daysUntilDue) &&
        Objects.equals(this.issuer, subscriptionScheduleDefaultSettingsParam.issuer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountTaxIds, daysUntilDue, issuer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionScheduleDefaultSettingsParam {\n");
    
    sb.append("    accountTaxIds: ").append(toIndentedString(accountTaxIds)).append("\n");
    sb.append("    daysUntilDue: ").append(toIndentedString(daysUntilDue)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
