/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * SubscriptionTransferData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class SubscriptionTransferData implements AnyOfsubscriptionTransferData, AnyOfsubscriptionSchedulePhaseConfigurationTransferData, AnyOfsubscriptionSchedulesResourceDefaultSettingsTransferData {
  @JsonProperty("amount_percent")
  private BigDecimal amountPercent = null;

  @JsonProperty("destination")
  private AnyOfsubscriptionTransferDataDestination destination = null;

  public SubscriptionTransferData amountPercent(BigDecimal amountPercent) {
    this.amountPercent = amountPercent;
    return this;
  }

   /**
   * A non-negative decimal between 0 and 100, with at most two decimal places. This represents the percentage of the subscription invoice total that will be transferred to the destination account. By default, the entire amount is transferred to the destination.
   * @return amountPercent
  **/
  public BigDecimal getAmountPercent() {
    return amountPercent;
  }

  public void setAmountPercent(BigDecimal amountPercent) {
    this.amountPercent = amountPercent;
  }

  public SubscriptionTransferData destination(AnyOfsubscriptionTransferDataDestination destination) {
    this.destination = destination;
    return this;
  }

   /**
   * The account where funds from the payment will be transferred to upon payment success.
   * @return destination
  **/
  public AnyOfsubscriptionTransferDataDestination getDestination() {
    return destination;
  }

  public void setDestination(AnyOfsubscriptionTransferDataDestination destination) {
    this.destination = destination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionTransferData subscriptionTransferData = (SubscriptionTransferData) o;
    return Objects.equals(this.amountPercent, subscriptionTransferData.amountPercent) &&
        Objects.equals(this.destination, subscriptionTransferData.destination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountPercent, destination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionTransferData {\n");
    
    sb.append("    amountPercent: ").append(toIndentedString(amountPercent)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
