/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * TaxProductRegistrationsResourceCountryOptionsEuStandard
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class TaxProductRegistrationsResourceCountryOptionsEuStandard {
  /**
   * Place of supply scheme used in an EU standard registration.
   */
  public enum PlaceOfSupplySchemeEnum {
    SMALL_SELLER("small_seller"),
    STANDARD("standard");

    private String value;

    PlaceOfSupplySchemeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static PlaceOfSupplySchemeEnum fromValue(String input) {
      for (PlaceOfSupplySchemeEnum b : PlaceOfSupplySchemeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("place_of_supply_scheme")
  private PlaceOfSupplySchemeEnum placeOfSupplyScheme = null;

  public TaxProductRegistrationsResourceCountryOptionsEuStandard placeOfSupplyScheme(PlaceOfSupplySchemeEnum placeOfSupplyScheme) {
    this.placeOfSupplyScheme = placeOfSupplyScheme;
    return this;
  }

   /**
   * Place of supply scheme used in an EU standard registration.
   * @return placeOfSupplyScheme
  **/
  public PlaceOfSupplySchemeEnum getPlaceOfSupplyScheme() {
    return placeOfSupplyScheme;
  }

  public void setPlaceOfSupplyScheme(PlaceOfSupplySchemeEnum placeOfSupplyScheme) {
    this.placeOfSupplyScheme = placeOfSupplyScheme;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxProductRegistrationsResourceCountryOptionsEuStandard taxProductRegistrationsResourceCountryOptionsEuStandard = (TaxProductRegistrationsResourceCountryOptionsEuStandard) o;
    return Objects.equals(this.placeOfSupplyScheme, taxProductRegistrationsResourceCountryOptionsEuStandard.placeOfSupplyScheme);
  }

  @Override
  public int hashCode() {
    return Objects.hash(placeOfSupplyScheme);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxProductRegistrationsResourceCountryOptionsEuStandard {\n");
    
    sb.append("    placeOfSupplyScheme: ").append(toIndentedString(placeOfSupplyScheme)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
