/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
/**
 * To top up your Stripe balance, you create a top-up object. You can retrieve individual top-ups, as well as list all top-ups. Top-ups are identified by a unique, random ID.  Related guide: [Topping up your platform account](https://stripe.com/docs/connect/top-ups)
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class Topup implements AnyOfbalanceTransactionSource {
  @JsonProperty("amount")
  private Integer amount = null;

  @JsonProperty("balance_transaction")
  private AnyOftopupBalanceTransaction balanceTransaction = null;

  @JsonProperty("created")
  private Integer created = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("expected_availability_date")
  private Integer expectedAvailabilityDate = null;

  @JsonProperty("failure_code")
  private String failureCode = null;

  @JsonProperty("failure_message")
  private String failureMessage = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("livemode")
  private Boolean livemode = null;

  @JsonProperty("metadata")
  private Map<String, String> metadata = new HashMap<>();

  /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   */
  public enum ObjectEnum {
    TOPUP("topup");

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ObjectEnum fromValue(String input) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("object")
  private ObjectEnum object = null;

  @JsonProperty("source")
  private AnyOftopupSource source = null;

  @JsonProperty("statement_descriptor")
  private String statementDescriptor = null;

  /**
   * The status of the top-up is either &#x60;canceled&#x60;, &#x60;failed&#x60;, &#x60;pending&#x60;, &#x60;reversed&#x60;, or &#x60;succeeded&#x60;.
   */
  public enum StatusEnum {
    CANCELED("canceled"),
    FAILED("failed"),
    PENDING("pending"),
    REVERSED("reversed"),
    SUCCEEDED("succeeded");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("status")
  private StatusEnum status = null;

  @JsonProperty("transfer_group")
  private String transferGroup = null;

  public Topup amount(Integer amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Amount transferred.
   * @return amount
  **/
  public Integer getAmount() {
    return amount;
  }

  public void setAmount(Integer amount) {
    this.amount = amount;
  }

  public Topup balanceTransaction(AnyOftopupBalanceTransaction balanceTransaction) {
    this.balanceTransaction = balanceTransaction;
    return this;
  }

   /**
   * ID of the balance transaction that describes the impact of this top-up on your account balance. May not be specified depending on status of top-up.
   * @return balanceTransaction
  **/
  public AnyOftopupBalanceTransaction getBalanceTransaction() {
    return balanceTransaction;
  }

  public void setBalanceTransaction(AnyOftopupBalanceTransaction balanceTransaction) {
    this.balanceTransaction = balanceTransaction;
  }

  public Topup created(Integer created) {
    this.created = created;
    return this;
  }

   /**
   * Time at which the object was created. Measured in seconds since the Unix epoch.
   * @return created
  **/
  public Integer getCreated() {
    return created;
  }

  public void setCreated(Integer created) {
    this.created = created;
  }

  public Topup currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public Topup description(String description) {
    this.description = description;
    return this;
  }

   /**
   * An arbitrary string attached to the object. Often useful for displaying to users.
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Topup expectedAvailabilityDate(Integer expectedAvailabilityDate) {
    this.expectedAvailabilityDate = expectedAvailabilityDate;
    return this;
  }

   /**
   * Date the funds are expected to arrive in your Stripe account for payouts. This factors in delays like weekends or bank holidays. May not be specified depending on status of top-up.
   * @return expectedAvailabilityDate
  **/
  public Integer getExpectedAvailabilityDate() {
    return expectedAvailabilityDate;
  }

  public void setExpectedAvailabilityDate(Integer expectedAvailabilityDate) {
    this.expectedAvailabilityDate = expectedAvailabilityDate;
  }

  public Topup failureCode(String failureCode) {
    this.failureCode = failureCode;
    return this;
  }

   /**
   * Error code explaining reason for top-up failure if available (see [the errors section](https://stripe.com/docs/api#errors) for a list of codes).
   * @return failureCode
  **/
  public String getFailureCode() {
    return failureCode;
  }

  public void setFailureCode(String failureCode) {
    this.failureCode = failureCode;
  }

  public Topup failureMessage(String failureMessage) {
    this.failureMessage = failureMessage;
    return this;
  }

   /**
   * Message to user further explaining reason for top-up failure if available.
   * @return failureMessage
  **/
  public String getFailureMessage() {
    return failureMessage;
  }

  public void setFailureMessage(String failureMessage) {
    this.failureMessage = failureMessage;
  }

  public Topup id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier for the object.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public Topup livemode(Boolean livemode) {
    this.livemode = livemode;
    return this;
  }

   /**
   * Has the value &#x60;true&#x60; if the object exists in live mode or the value &#x60;false&#x60; if the object exists in test mode.
   * @return livemode
  **/
  public Boolean isLivemode() {
    return livemode;
  }

  public void setLivemode(Boolean livemode) {
    this.livemode = livemode;
  }

  public Topup metadata(Map<String, String> metadata) {
    this.metadata = metadata;
    return this;
  }

  public Topup putMetadataItem(String key, String metadataItem) {
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
   * @return metadata
  **/
  public Map<String, String> getMetadata() {
    return metadata;
  }

  public void setMetadata(Map<String, String> metadata) {
    this.metadata = metadata;
  }

  public Topup object(ObjectEnum object) {
    this.object = object;
    return this;
  }

   /**
   * String representing the object&#x27;s type. Objects of the same type share the same value.
   * @return object
  **/
  public ObjectEnum getObject() {
    return object;
  }

  public void setObject(ObjectEnum object) {
    this.object = object;
  }

  public Topup source(AnyOftopupSource source) {
    this.source = source;
    return this;
  }

   /**
   * The source field is deprecated. It might not always be present in the API response.
   * @return source
  **/
  public AnyOftopupSource getSource() {
    return source;
  }

  public void setSource(AnyOftopupSource source) {
    this.source = source;
  }

  public Topup statementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
    return this;
  }

   /**
   * Extra information about a top-up. This will appear on your source&#x27;s bank statement. It must contain at least one letter.
   * @return statementDescriptor
  **/
  public String getStatementDescriptor() {
    return statementDescriptor;
  }

  public void setStatementDescriptor(String statementDescriptor) {
    this.statementDescriptor = statementDescriptor;
  }

  public Topup status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * The status of the top-up is either &#x60;canceled&#x60;, &#x60;failed&#x60;, &#x60;pending&#x60;, &#x60;reversed&#x60;, or &#x60;succeeded&#x60;.
   * @return status
  **/
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Topup transferGroup(String transferGroup) {
    this.transferGroup = transferGroup;
    return this;
  }

   /**
   * A string that identifies this top-up as part of a group.
   * @return transferGroup
  **/
  public String getTransferGroup() {
    return transferGroup;
  }

  public void setTransferGroup(String transferGroup) {
    this.transferGroup = transferGroup;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topup topup = (Topup) o;
    return Objects.equals(this.amount, topup.amount) &&
        Objects.equals(this.balanceTransaction, topup.balanceTransaction) &&
        Objects.equals(this.created, topup.created) &&
        Objects.equals(this.currency, topup.currency) &&
        Objects.equals(this.description, topup.description) &&
        Objects.equals(this.expectedAvailabilityDate, topup.expectedAvailabilityDate) &&
        Objects.equals(this.failureCode, topup.failureCode) &&
        Objects.equals(this.failureMessage, topup.failureMessage) &&
        Objects.equals(this.id, topup.id) &&
        Objects.equals(this.livemode, topup.livemode) &&
        Objects.equals(this.metadata, topup.metadata) &&
        Objects.equals(this.object, topup.object) &&
        Objects.equals(this.source, topup.source) &&
        Objects.equals(this.statementDescriptor, topup.statementDescriptor) &&
        Objects.equals(this.status, topup.status) &&
        Objects.equals(this.transferGroup, topup.transferGroup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, balanceTransaction, created, currency, description, expectedAvailabilityDate, failureCode, failureMessage, id, livemode, metadata, object, source, statementDescriptor, status, transferGroup);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topup {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    balanceTransaction: ").append(toIndentedString(balanceTransaction)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    expectedAvailabilityDate: ").append(toIndentedString(expectedAvailabilityDate)).append("\n");
    sb.append("    failureCode: ").append(toIndentedString(failureCode)).append("\n");
    sb.append("    failureMessage: ").append(toIndentedString(failureMessage)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    livemode: ").append(toIndentedString(livemode)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    object: ").append(toIndentedString(object)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("    statementDescriptor: ").append(toIndentedString(statementDescriptor)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    transferGroup: ").append(toIndentedString(transferGroup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
