/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.math.BigDecimal;
/**
 * If specified, the funds from the subscription&#x27;s invoices will be transferred to the destination and the ID of the resulting transfers will be found on the resulting charges.
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class TransferDataSpecs3 {
  @JsonProperty("amount_percent")
  private BigDecimal amountPercent = null;

  @JsonProperty("destination")
  private String destination = null;

  public TransferDataSpecs3 amountPercent(BigDecimal amountPercent) {
    this.amountPercent = amountPercent;
    return this;
  }

   /**
   * Get amountPercent
   * @return amountPercent
  **/
  public BigDecimal getAmountPercent() {
    return amountPercent;
  }

  public void setAmountPercent(BigDecimal amountPercent) {
    this.amountPercent = amountPercent;
  }

  public TransferDataSpecs3 destination(String destination) {
    this.destination = destination;
    return this;
  }

   /**
   * Get destination
   * @return destination
  **/
  public String getDestination() {
    return destination;
  }

  public void setDestination(String destination) {
    this.destination = destination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransferDataSpecs3 transferDataSpecs3 = (TransferDataSpecs3) o;
    return Objects.equals(this.amountPercent, transferDataSpecs3.amountPercent) &&
        Objects.equals(this.destination, transferDataSpecs3.destination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountPercent, destination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransferDataSpecs3 {\n");
    
    sb.append("    amountPercent: ").append(toIndentedString(amountPercent)).append("\n");
    sb.append("    destination: ").append(toIndentedString(destination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
