/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;
/**
 * TreasuryFinancialAccountsResourceClosedStatusDetails
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class TreasuryFinancialAccountsResourceClosedStatusDetails implements AnyOftreasuryFinancialAccountsResourceStatusDetailsClosed {
  /**
   * Gets or Sets reasons
   */
  public enum ReasonsEnum {
    ACCOUNT_REJECTED("account_rejected"),
    CLOSED_BY_PLATFORM("closed_by_platform"),
    OTHER("other");

    private String value;

    ReasonsEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static ReasonsEnum fromValue(String input) {
      for (ReasonsEnum b : ReasonsEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("reasons")
  private List<ReasonsEnum> reasons = new ArrayList<>();

  public TreasuryFinancialAccountsResourceClosedStatusDetails reasons(List<ReasonsEnum> reasons) {
    this.reasons = reasons;
    return this;
  }

  public TreasuryFinancialAccountsResourceClosedStatusDetails addReasonsItem(ReasonsEnum reasonsItem) {
    this.reasons.add(reasonsItem);
    return this;
  }

   /**
   * The array that contains reasons for a FinancialAccount closure.
   * @return reasons
  **/
  public List<ReasonsEnum> getReasons() {
    return reasons;
  }

  public void setReasons(List<ReasonsEnum> reasons) {
    this.reasons = reasons;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreasuryFinancialAccountsResourceClosedStatusDetails treasuryFinancialAccountsResourceClosedStatusDetails = (TreasuryFinancialAccountsResourceClosedStatusDetails) o;
    return Objects.equals(this.reasons, treasuryFinancialAccountsResourceClosedStatusDetails.reasons);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reasons);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreasuryFinancialAccountsResourceClosedStatusDetails {\n");
    
    sb.append("    reasons: ").append(toIndentedString(reasons)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
