/*
 * Stripe API
 * The Stripe REST API. Please see https://stripe.com/docs/api for more details.
 *
 * OpenAPI spec version: 2025-01-27.acacia
 * Contact: dev-platform@stripe.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stripe.api.client;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stripe.api.client.AppliesToParams;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * V1CouponsBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2025-01-23T08:38:25.571625600+07:00[Asia/Bangkok]")

public class V1CouponsBody {
  @JsonProperty("amount_off")
  private Integer amountOff = null;

  @JsonProperty("applies_to")
  private AppliesToParams appliesTo = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("currency_options")
  private Object currencyOptions = null;

  /**
   * Specifies how long the discount will be in effect if used on a subscription. Defaults to &#x60;once&#x60;.
   */
  public enum DurationEnum {
    FOREVER("forever"),
    ONCE("once"),
    REPEATING("repeating");

    private String value;

    DurationEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static DurationEnum fromValue(String input) {
      for (DurationEnum b : DurationEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }  @JsonProperty("duration")
  private DurationEnum duration = null;

  @JsonProperty("duration_in_months")
  private Integer durationInMonths = null;

  @JsonProperty("expand")
  private List<String> expand = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("max_redemptions")
  private Integer maxRedemptions = null;

  @JsonProperty("metadata")
  private AnyOfv1CouponsBodyMetadata metadata = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("percent_off")
  private BigDecimal percentOff = null;

  @JsonProperty("redeem_by")
  private Integer redeemBy = null;

  public V1CouponsBody amountOff(Integer amountOff) {
    this.amountOff = amountOff;
    return this;
  }

   /**
   * A positive integer representing the amount to subtract from an invoice total (required if &#x60;percent_off&#x60; is not passed).
   * @return amountOff
  **/
  public Integer getAmountOff() {
    return amountOff;
  }

  public void setAmountOff(Integer amountOff) {
    this.amountOff = amountOff;
  }

  public V1CouponsBody appliesTo(AppliesToParams appliesTo) {
    this.appliesTo = appliesTo;
    return this;
  }

   /**
   * Get appliesTo
   * @return appliesTo
  **/
  public AppliesToParams getAppliesTo() {
    return appliesTo;
  }

  public void setAppliesTo(AppliesToParams appliesTo) {
    this.appliesTo = appliesTo;
  }

  public V1CouponsBody currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) of the &#x60;amount_off&#x60; parameter (required if &#x60;amount_off&#x60; is passed).
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public V1CouponsBody currencyOptions(Object currencyOptions) {
    this.currencyOptions = currencyOptions;
    return this;
  }

   /**
   * Coupons defined in each available currency option (only supported if &#x60;amount_off&#x60; is passed). Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).
   * @return currencyOptions
  **/
  public Object getCurrencyOptions() {
    return currencyOptions;
  }

  public void setCurrencyOptions(Object currencyOptions) {
    this.currencyOptions = currencyOptions;
  }

  public V1CouponsBody duration(DurationEnum duration) {
    this.duration = duration;
    return this;
  }

   /**
   * Specifies how long the discount will be in effect if used on a subscription. Defaults to &#x60;once&#x60;.
   * @return duration
  **/
  public DurationEnum getDuration() {
    return duration;
  }

  public void setDuration(DurationEnum duration) {
    this.duration = duration;
  }

  public V1CouponsBody durationInMonths(Integer durationInMonths) {
    this.durationInMonths = durationInMonths;
    return this;
  }

   /**
   * Required only if &#x60;duration&#x60; is &#x60;repeating&#x60;, in which case it must be a positive integer that specifies the number of months the discount will be in effect.
   * @return durationInMonths
  **/
  public Integer getDurationInMonths() {
    return durationInMonths;
  }

  public void setDurationInMonths(Integer durationInMonths) {
    this.durationInMonths = durationInMonths;
  }

  public V1CouponsBody expand(List<String> expand) {
    this.expand = expand;
    return this;
  }

  public V1CouponsBody addExpandItem(String expandItem) {
    if (this.expand == null) {
      this.expand = new ArrayList<>();
    }
    this.expand.add(expandItem);
    return this;
  }

   /**
   * Specifies which fields in the response should be expanded.
   * @return expand
  **/
  public List<String> getExpand() {
    return expand;
  }

  public void setExpand(List<String> expand) {
    this.expand = expand;
  }

  public V1CouponsBody id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique string of your choice that will be used to identify this coupon when applying it to a customer. If you don&#x27;t want to specify a particular code, you can leave the ID blank and we&#x27;ll generate a random code for you.
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public V1CouponsBody maxRedemptions(Integer maxRedemptions) {
    this.maxRedemptions = maxRedemptions;
    return this;
  }

   /**
   * A positive integer specifying the number of times the coupon can be redeemed before it&#x27;s no longer valid. For example, you might have a 50% off coupon that the first 20 readers of your blog can use.
   * @return maxRedemptions
  **/
  public Integer getMaxRedemptions() {
    return maxRedemptions;
  }

  public void setMaxRedemptions(Integer maxRedemptions) {
    this.maxRedemptions = maxRedemptions;
  }

  public V1CouponsBody metadata(AnyOfv1CouponsBodyMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

   /**
   * Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to &#x60;metadata&#x60;.
   * @return metadata
  **/
  public AnyOfv1CouponsBodyMetadata getMetadata() {
    return metadata;
  }

  public void setMetadata(AnyOfv1CouponsBodyMetadata metadata) {
    this.metadata = metadata;
  }

  public V1CouponsBody name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the coupon displayed to customers on, for instance invoices, or receipts. By default the &#x60;id&#x60; is shown if &#x60;name&#x60; is not set.
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public V1CouponsBody percentOff(BigDecimal percentOff) {
    this.percentOff = percentOff;
    return this;
  }

   /**
   * A positive float larger than 0, and smaller or equal to 100, that represents the discount the coupon will apply (required if &#x60;amount_off&#x60; is not passed).
   * @return percentOff
  **/
  public BigDecimal getPercentOff() {
    return percentOff;
  }

  public void setPercentOff(BigDecimal percentOff) {
    this.percentOff = percentOff;
  }

  public V1CouponsBody redeemBy(Integer redeemBy) {
    this.redeemBy = redeemBy;
    return this;
  }

   /**
   * Unix timestamp specifying the last time at which the coupon can be redeemed. After the redeem_by date, the coupon can no longer be applied to new customers.
   * @return redeemBy
  **/
  public Integer getRedeemBy() {
    return redeemBy;
  }

  public void setRedeemBy(Integer redeemBy) {
    this.redeemBy = redeemBy;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1CouponsBody v1CouponsBody = (V1CouponsBody) o;
    return Objects.equals(this.amountOff, v1CouponsBody.amountOff) &&
        Objects.equals(this.appliesTo, v1CouponsBody.appliesTo) &&
        Objects.equals(this.currency, v1CouponsBody.currency) &&
        Objects.equals(this.currencyOptions, v1CouponsBody.currencyOptions) &&
        Objects.equals(this.duration, v1CouponsBody.duration) &&
        Objects.equals(this.durationInMonths, v1CouponsBody.durationInMonths) &&
        Objects.equals(this.expand, v1CouponsBody.expand) &&
        Objects.equals(this.id, v1CouponsBody.id) &&
        Objects.equals(this.maxRedemptions, v1CouponsBody.maxRedemptions) &&
        Objects.equals(this.metadata, v1CouponsBody.metadata) &&
        Objects.equals(this.name, v1CouponsBody.name) &&
        Objects.equals(this.percentOff, v1CouponsBody.percentOff) &&
        Objects.equals(this.redeemBy, v1CouponsBody.redeemBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amountOff, appliesTo, currency, currencyOptions, duration, durationInMonths, expand, id, maxRedemptions, metadata, name, percentOff, redeemBy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1CouponsBody {\n");
    
    sb.append("    amountOff: ").append(toIndentedString(amountOff)).append("\n");
    sb.append("    appliesTo: ").append(toIndentedString(appliesTo)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    currencyOptions: ").append(toIndentedString(currencyOptions)).append("\n");
    sb.append("    duration: ").append(toIndentedString(duration)).append("\n");
    sb.append("    durationInMonths: ").append(toIndentedString(durationInMonths)).append("\n");
    sb.append("    expand: ").append(toIndentedString(expand)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    maxRedemptions: ").append(toIndentedString(maxRedemptions)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    percentOff: ").append(toIndentedString(percentOff)).append("\n");
    sb.append("    redeemBy: ").append(toIndentedString(redeemBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
